### ISSUE TITLE
Does not work properly with nvim-tree.lua

### ISSUE THREAD

**Issue by doubleloop** [windwp/nvim-autopairs#100]
steps to reproduce:

```sh
$ cat test.vim
call plug#begin(stdpath('data').'/plugged')
Plug 'windwp/nvim-autopairs'
Plug 'kyazdani42/nvim-tree.lua'
call plug#end()

lua << EOF
require('nvim-autopairs').setup {}
EOF

$ nvim -u test.vim test.py
```

Now try multiline comments `"""` (https://github.com/windwp/nvim-autopairs/blob/master/lua/nvim-autopairs/rules/basic.lua#L29), it does not work.

Without [nvim-tree.lua](https://github.com/kyazdani42/nvim-tree.lua) this rule works as expected.

**Comment by cblessing24** [comment]
I am experiencing the same behavior. Custom rules also do not work for me as long as nvim-tree is installed.
