### ISSUE TITLE
Lazy Loading nvim-compe and nvim-autopairs creates error

### ISSUE THREAD

**Issue by FotiadisM** [windwp/nvim-autopairs#101]
Hello and thank you for your amazing work and contribution to the community.

As the title suggest if I lazy load both plugins like so: (I use packer)
```
		use {
			"hrsh7th/nvim-compe",
			event = "InsertEnter",
			config = function()
				require("plugins.nvim-compe")
			end
		}
		use {
			"windwp/nvim-autopairs",
			event = "InsertEnter",
			after = "nvim-compe",
			config = function()
				require("plugins.nvim-autopairs")
			end
		}

```
I get the error beneath
```
Error detected while processing InsertEnter Autocommands for "*":
E5108: Error executing lua ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:115: Vim(echomsg):E114: Missing quote: "Error in packer_compile: ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:52: ...t/nvim-autopairs/lua/nvim-autopairs/completion/compe.lua:2: module 'compe.completion' not found:
```
It seems as if nvim-compe is not loaded when autopairs is running despite using the `after` keyword

Note that it works completely fine when Not using lazy loading

**Comment by rebuilt** [comment]
You've defined two lazy loading strategies for autopairs.

Try removing `event = "InsertEnter",` so you only define a single lazy loading strategy.  Make sure to reload the file and recompile after making your edits.

**Comment by FotiadisM** [comment]
Yes, you are right!
Thank you for the quick response and help.
