### ISSUE TITLE
Adding %s to fast_wrap pattern

### ISSUE THREAD

**Issue by howoz** [windwp/nvim-autopairs#103]
I made fast_wrap detect space character by adding this to my config:
```lua
    fast_wrap = {
        pattern = string.gsub([[ [%'%"%)%>%]%)%}%,%s] ]], '%s+', ''),
    }
```
but the problem is when I fast wrap using space it looks like this:
    |"random-string another_string -> "random-string "another_string
is there a way to make it detect characters before space or shift the fast wrap location somehow?

**Comment by pabloariasal** [comment]
This problem still persists for me, looks like it has been broken in the mean time.
