### ISSUE TITLE
Nested pairs not completing

### ISSUE THREAD

**Issue by zegervdv** [windwp/nvim-autopairs#104]
Hi, 

I'm probably missing something in the config, but I cannot figure it out.
I want to complete nested pairs inside quotes.
For example in python:
``` python
print(f"value = {|")
```
When I type the `{` inside the string, the pair is not added.

Can you point me in the right direction to configure this behaviour?

**Comment by windwp** [comment]
are you using treesitter and  check_ts =true

**Comment by zegervdv** [comment]
Yes, that works!

Thanks a lot
