### ISSUE TITLE
Custom rules and multi-character pairs stop working after nvim-compe's documentation window pops up

### ISSUE THREAD

**Issue by cblessing24** [windwp/nvim-autopairs#107]
Hey, I am using [vim-vsnip](https://github.com/hrsh7th/vim-vsnip) for snippets and I noticed that my custom rules stop working after using a snippet for the first time. In addition to custom rules this also happens with multi-character pairs like `"""` in `python` for example.

Here is my config:

```lua
local npairs = require("nvim-autopairs")
local Rule = require("nvim-autopairs.rule")

npairs.setup()

require("nvim-autopairs.completion.compe").setup({
    map_cr = true, --  map <CR> on insert mode
    map_complete = true, -- it will auto insert `(` after select function or method item
    auto_select = true -- auto select first item
})

npairs.add_rule(Rule("|", "|", "rust"))
```

**Comment by windwp** [comment]
are you using a latest commit?  are you using nvimtree

**Comment by cblessing24** [comment]
Yeah I am using the latest commit and nvimtree. Although I just tried if the issue persists after I uninstall nvimtree and it does.

**Comment by windwp** [comment]
sorry, i can reproduce it you should check your config. the problem of nvimtree already fix before

**Comment by cblessing24** [comment]
Alright I did some experimenting and found out that snippets actually do not trigger the behavior. It is triggered by the little documentation window that pops up in nvim-compe on some of the items in the completion menu.
Once that window appeared once the custom rules and multi-character pairs stop working for me until I restart neovim. Not sure if that is a problem with my configuration or with one of the plugins...

**Comment by cblessing24** [comment]
Here is a minimal example which reproduces the behavior:

```lua
require('packer').startup(function()
  use 'wbthomason/packer.nvim'
  use 'neovim/nvim-lspconfig'
  use 'hrsh7th/nvim-compe'
  use 'windwp/nvim-autopairs'
end)

local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true
capabilities.textDocument.completion.completionItem.resolveSupport = {
  properties = {
    'documentation',
    'detail',
    'additionalTextEdits',
  }
}

require'lspconfig'.pyright.setup {
  capabilities = capabilities,
}


require'compe'.setup {
  enabled = true;
  autocomplete = true;

  source = {
    nvim_lsp = true;
  };
}

require('nvim-autopairs').setup{}

require("nvim-autopairs.completion.compe").setup({
  map_cr = true, --  map <CR> on insert mode
  map_complete = true, -- it will auto insert `(` after select function or method item
  auto_select = false,  -- auto select first item
})
```
Using this config `"""` stops working in Python files after nvim-compe's documentation window popped up once.

**Comment by cblessing24** [comment]
I switched from `nvim-compe` to `nvim-cmp` and the issue persists there as well.

**Comment by windwp** [comment]
Sorry i can't reproduce the issue so
if you have a step or video to how to reproduce that issue then i will take a look.

**Comment by cblessing24** [comment]
Here is a gif of the issue using my setup:
![nvim-autopairs-issue](https://user-images.githubusercontent.com/33834216/132094540-d59e6589-c722-4ea4-a330-d719136a415b.gif)

Note how the `"""` pair only stops working after the documentation window from `nvim-cmp` pops up when I select `def~` from the completion menu. I hope this helps.

**Comment by windwp** [comment]
Thankyou i fix that
