### ISSUE TITLE
Just only cmp_complete feature about cmp.

### ISSUE THREAD

**Issue by rhcher** [windwp/nvim-autopairs#108]
Hi, thank you for your great plugin. I'm using this plugin with cmp and meeting something confusing.
Because in cmp I use \<tab> to confirm completion items and my \<CR> map is this
``` lua
_G.my_cr = function()
  local npairs = require "nvim-autopairs"
  if vim.fn.pumvisible() ~= 0 then
    return t "<C-e><CR>"
  else
    return npairs.autopairs_cr()
  end
end
```
So what I want is just cmp_complete feature when I use tab to confirm completion.

**Comment by windwp** [comment]
sorry i am not sure this is what you want    but you can try this mapping on your tab key

      `   return _G.cmp.utils.keymap.expr('<CR>')`
if it is not work so you should open issue on nvim-cmp

**Comment by rhcher** [comment]
Sorry for my ambiguous representations. Because my habit are different from most people.
Here is my cmp setup about mapping:
``` lua
    mapping = {
      ["<C-p>"] = cmp.mapping.prev_item(),
      ["<C-n>"] = cmp.mapping.next_item(),
      ["<C-d>"] = cmp.mapping.scroll(-4),
      ["<C-f>"] = cmp.mapping.scroll(4),
      ["<C-Space>"] = cmp.mapping.complete(),
      ["<C-e>"] = cmp.mapping.close(),
      ["<C-y>"] = cmp.mapping.confirm {
        select = true,
        behavior = cmp.ConfirmBehavior.Replace,
      },
      ["<Tab>"] = cmp.mapping.mode({ "i", "s" }, function(_, fallback)
        if vim.fn.pumvisible() == 1 then
          vim.fn.feedkeys(t "<C-y>", "")
        elseif vim.fn["vsnip#available"]() == 1 then
          vim.fn.feedkeys(t "<Plug>(vsnip-expand-or-jump)", "")
        else
          fallback()
        end
      end),
    },
```
As you seen above, in fact I use tab to confirm completion item. And this is my personal \<CR> map:
``` lua
map( 'i', '<CR>', 'v:lua.my_cr()', {expr = true, silent = true, noremap= true}) -- Pseudocode
_G.my_cr = function()
  local npairs = require "nvim-autopairs"
  if vim.fn.pumvisible() ~= 0 then
    return npairs.esc "<C-e><CR>"
  else
    return npairs.autopairs_cr()
  end
end
```
And I want to have map_complete feature when I use \<tab> to confirm completion items, so I add nvim-autopair.completion.cmp setup in my config like this:
``` lua
require("nvim-autopairs.completion.cmp").setup {
   map_cr = false, --  map <CR> on insert mode
   map_complete = true, -- it will auto insert `(` after select function or method item
}
```
It will override my personal imap about <CR> key even if I make map_cr opt false. I think if I set map_cr opt to false, then autopairs should not override my confirm key setting in cmp setup.
