### ISSUE TITLE
Double quote doesn’t work in some file type

### ISSUE THREAD

**Issue by FongHou** [windwp/nvim-autopairs#114]
With treesitter installed, double quote doesn't work as other pairs in some file types, e.g. clojure, fennel or others. Every " inserts a new nested pairs, rather than move cursor over closing ". This even happened with check_ts = false. The only workaround is disable treesitter highlight for these filetypes. Strangely, this problem does not occur for certain filetype, such as lue.

**Comment by windwp** [comment]
Please provide a step on how to reproduce issue with a minium config

**Comment by FongHou** [comment]
Use whatever plugin manager you prefer, and use below plugins.lua config. 

Note the disable treesitter hightlight.disable field. Just remove either "clojure" or "fennel" from there. You'll see the problem.

```
require('nvim-treesitter.configs').setup {
  ensure_installed = "maintained",
  ignore_install = { "javascript" },
  highlight = {
    enable = true,
    disable = { "javascript", "clojure", "fennel" },
  }
}

local autopairs = require('nvim-autopairs')
autopairs.setup {
  fast_wrap = {},
}
autopairs.remove_rule("'")
autopairs.remove_rule("`")
```

**Comment by FongHou** [comment]
another note, I removed single quote, and backtick quote rules also because they are broken in a different way (i.e. insertion works, but backspace doesn't delete the pairs). strangely autopairs.remove('"') doesn't seem remove the rule at all. otherwise I could use that as a workaround for double quote instead of disabling treesitter completely.

**Comment by FongHou** [comment]
close this as the cause is that vim-sexp has a conflict " keymap.
