### ISSUE TITLE
`cmp` complete: feedkey `'('` is inserted before the completed item in some situations

### ISSUE THREAD

**Issue by JoelTari** [windwp/nvim-autopairs#115]
When I type :
```
setTim|      // | is cursor
```
`setTimeout` completion candidate from LSP is top of the cmp list.

Expected result after `cmp.mapping.confirm` (default mapping `<CR>`):
```
setTimeout(|)
```
But got:
```
(setTimeout|         // left parenthesis got inserted before, no right parenthesis
```

## To reproduce
- Have `nvim_cmp` and the `tsserver` lsp as a source
- option `map_complete` is true
- create `main.js` and `jsconfig.json` in a new folder

Not sure if this happens in other environments. I was not able to reproduce it in `c++` with `clangd` or `python` with `pyright`.
Also, if `setTimeout` completion is explicitely selected with `cmp.mapping.select_next_item`, it completes `setTimeout(|)` as expected. 

## Fix ?

https://github.com/windwp/nvim-autopairs/blob/70ed2702c988a00f65c450a6f142b7f3df2656e1/lua/nvim-autopairs/completion/cmp.lua#L47

Replace the `'i'` by `''` does the trick for me.  According to the [feedkeys doc](https://neovim.io/doc/user/eval.html#feedkeys()), this will append the string `'('` rather than insert it before.

**Comment by ashincoder** [comment]
https://github.com/hrsh7th/nvim-cmp/issues/115
