### ISSUE TITLE
i want to let latex file auto pair {} after enter a function, but now it auto pair ()

### ISSUE THREAD

**Issue by flaviusbuffon** [windwp/nvim-autopairs#124]
using neovim , and the plugin.
i need make this plugin adapt latex, to auto appear {} instead () like the picture below
![image](https://user-images.githubusercontent.com/44057232/132213585-5854d6c0-ce89-46b2-9df8-26444fd2308c.png)

**Comment by windwp** [comment]
https://github.com/windwp/nvim-autopairs/blob/master/lua/nvim-autopairs/completion/cmp.lua
you need to modify that line. if all function on latex will insert { so you can make a PR :+1:

**Comment by flaviusbuffon** [comment]
can you help to modify it to achieve the goal



-------- 原始邮件 --------
发件人： windwp ***@***.***>
日期： 2021年9月6日周一 晚上8:56
收件人： windwp/nvim-autopairs ***@***.***>
抄送： Flavius Buffon ***@***.***>, Author ***@***.***>
主 题： Re: [windwp/nvim-autopairs] i want to let latex file auto pair {} after enter a function, but now it auto pair () (#124)

https://github.com/windwp/nvim-autopairs/blob/master/lua/nvim-autopairs/completion/cmp.lua
you need to modify that line. if all function on latex will insert { so you can make a PR 👍

**Comment by flaviusbuffon** [comment]
hope to get your support!

**Comment by ChristianChiarulli** [comment]
Would it be possible to disable `map_complete` per filetype?

I would like it active for everything but latex.

**Comment by flaviusbuffon** [comment]
i also want to achieve this goal
