### ISSUE TITLE
Can the functionality of tabout.nvim be integrated to this?

### ISSUE THREAD

**Issue by IndianBoy42** [windwp/nvim-autopairs#125]
https://github.com/abecodes/tabout.nvim

Tabout allows you to use tab (or any key really)to jump out of brackets/parens/other pairs

The annoying thing is I have to tell it what are valid pairs, when really they are already defined in nvim-autopairs. Also that plugin doesn't support different file types 

It makes sense to me to have the tabout functionality in this plugin, taking into account custom pairs

**Comment by windwp** [comment]
so if you have a pair `\left( {cursor} \right)` then when you tab you want it go to `\left(    \right){cursor}` is that right?
it should implement on tabout. My plugin export all rules of the current buffer on `MPairs.state.rules` 
They can use it to do that but I think tabout use treesitter to jump out so it is not simple to do that
