### ISSUE TITLE
Rule with multibyte characters doesn't work

### ISSUE THREAD

**Issue by fenuks** [windwp/nvim-autopairs#126]
Are multibyte characters correctly supported?

I tried to add few additional rules (in my case, for closing typographic quotes, for instance I can enter `„` with `<M-v>`. It is not a vim mapping, it's shortcut in keyboard from a keyboard layout.

```lua
local Rule = require('nvim-autopairs.rule')
local npairs = require('nvim-autopairs')
npairs.add_rule(Rule("|","|"))
npairs.add_rule(Rule("a","bc"))
npairs.add_rule(Rule("„","”"))
npairs.add_rule(Rule("’","’"))
```

First two rules work correctly, but alas next two aren't. As far I can see, mapping is not created at all:

```
:inoremap „
No mapping found
```

**Comment by windwp** [comment]
Sorry, Currently it is not supported to handle multibyte characters.

the message from the readme.md is multiple characters not multibyte :cry:

**Comment by fenuks** [comment]
I see, thank you. How do you think, how difficult it would be to handle those? I might look into it.

**Comment by windwp** [comment]
firstly i am not sure is neovim support mapping multibyte character like that  

i try `imap „ „”<left>`it is not working because I use terminal to trigger Unicode but you can try on your keyboard.
if it still not working on your keyboard so you can't do that mapping on neovim.

i try that mapping and it work  `inoremap <a-v> „”<left>`.

**Comment by fenuks** [comment]
Yes, `imap „ „”<left>` does work. Prior to your plugin, I was using https://github.com/fenuks/auto-pairs (my fork of unmaintained original auto-pairs plugin), and it does work with multibyte characters as well.
Assuming you are using Linux and English keyboard layout, you count try to insert e.g. something like `ŋ` (331, U+014B LATIN SMALL LETTER ENG) with `<M-g>`, and mapping it to `imap ŋ test` should work

**Comment by fenuks** [comment]
Thank you, I can confirm that it's working now.
