### ISSUE TITLE
[ Feature Request ] Fast wrap offset

### ISSUE THREAD

**Issue by ten3roberts** [windwp/nvim-autopairs#128]
When fast wrapping, an option to specify an offset from the pattern match is needed.

This way, the inserted match could be inserted before the matched pair

Example: 
```
| denotes the cursor position
print([ | foo) -- Trigger fast wrap
print([ | fooa -- Press 'a'
print([foo)]
```

if an offset can be configured, the use can choose to prefer the square bracket to be placed before the ) by having a negative offset.

I already have a fork with this feature if it sound good and can open a Pull Request.

By default, behaviour is unchanged.

**Comment by windwp** [comment]
thank pr is welcome
