### ISSUE TITLE
Configuration question/clarification

### ISSUE THREAD

**Issue by benfrain** [windwp/nvim-autopairs#129]
Thanks for making this plugin.

The only part I'm struggling to understand is getting auto-indent working. 

I use Compe for autocomplete, and with this config from the readme:

```
require("nvim-autopairs").setup({})

require("nvim-autopairs.completion.compe").setup({
  map_cr = true, --  map <CR> on insert mode
  map_complete = true, -- it will auto insert `(` after select function or method item
  auto_select = false, -- auto select first item
})
```

I do not get auto-indent in CSS/SCSS/Lua. What part am I missing? 

I saw this: `If you have a problem with indent after press <CR> Please check setting of treesitter indent or install plugin support indent on your filetype` but what do you mean by 'install plugin support indent on your filetype'?

**Comment by windwp** [comment]
this plugin trigger indent by press key == .if that key is working then your indent will work

run command `verbose set indentexpr? to see what is the function neovim use indent if you don't have or that function is not correct so you need to find a plugin seting that function
just run help indent for more detail

**Comment by benfrain** [comment]
When I run `verbose set indentexpr`, in a TS  file the result is:
```
indentexpr=GetTypescriptIndent()                                                                                                                                                                                            
        Last set from /usr/local/Cellar/neovim/HEAD-7d2233f/share/nvim/runtime/indent/typescript.vim line 19
```

When I run it in CSS I  get:
```
indentexpr=GetCSSIndent()                                                                                                                                                                                                   
        Last set from /usr/local/Cellar/neovim/HEAD-7d2233f/share/nvim/runtime/indent/css.vim line 12
```

When I press `==` in either, the line indents. But I don't get the auto indent. Is that what you would expect?

**Comment by windwp** [comment]
hmn your issue on video is not about indent. 
it is about append newline on mapping <cr> key.
just run `verbose imap <cr>`.

about your indent setting on typescript and css. you use the default indent and it not correct for tsx.
https://github.com/windwp/nvim-autopairs/issues/66

**Comment by benfrain** [comment]
Hi @windwp I would expect a new line and auto indent. When pressing <CR> in the video I would expect to end like this:

```
.thing {
    |
}
```

Are you saying that this plugin doesn't do that? Or it does and I just have it configured wrong?

**Comment by windwp** [comment]
I already say my plugin will append new line and  call the default indent of vim. if your vim have wrong indent setting so it will wrong.

but i see in your video it is not append another line so i tell you check mapping <cr>.

so the final answer is  my plugin can do that and you have wrong config.

**Comment by sirbrillig** [comment]
If it's helpful, I also was unable to get the newline (+indent) added when I pressed <CR>. As suggested above I ran `:verbose imap <cr>` and it told me that it was mapped by `vim-endwise`. I removed that plugin and now it works correctly in scss, css, and javascript!

**Comment by benfrain** [comment]
@sirbrillig thanks for the hint. Mine spits out:

```
<CR>        &@<SNR>43_AutoPairsOldCRWrapper73<SNR>43_AutoPairsReturn                                                                                               
        Last set from ~/.local/share/nvim/site/pack/paqs/start/auto-pairs/plugin/auto-pairs.vim line 662                                                              
i  <CR>          compe#confirm({ 'keys': '<CR>', 'select': v:true })                                                                                                  
        Last set from ~/.config/nvim/init.lua
```

Unsure whether that is what is expected here as this is about making AutoPairs run with Compe ??

**Comment by benfrain** [comment]
I have tried undoing the mapping for <CR> for compe which was this:

```
vim.api.nvim_set_keymap("i", "<CR>", "compe#confirm({ 'keys': '<CR>', 'select': v:true })", { expr = true })
```

And now auto pairs works as expected but selecting the first item from the autocomplete list with `<CR>` doesn't work. Is there some way to reconcile there two?

**Comment by benfrain** [comment]
For any future travellers. My problem was solved by amending the default config for Compe:

```
require("nvim-autopairs").setup({})
require("nvim-autopairs.completion.compe").setup({
  map_cr = true, --  map <CR> on insert mode
  map_complete = true, -- it will auto insert `(` after select function or method item
  auto_select = true, -- auto select first item
})
```

Note that `auto_select` is set to `true`!!

Then ensure you don't have `vim.api.nvim_set_keymap("i", "<CR>", "compe#confirm({ 'keys': '<CR>', 'select': v:true })", { expr = true })
` in your init.
