### ISSUE TITLE
Auto-closing quotes with common prefix

### ISSUE THREAD

**Issue by doubleloop** [windwp/nvim-autopairs#13]
I do not consider this to be extra feature but rather improvement on base feature. 

Currently this configuration:
```
require('nvim-autopairs').setup({
    pairs_map = {
        ['`'] = '`',
        ['```'] = '```',
    }
})
```

Does not work as expected (expected behavior: `` `| `` -> `` `|` `` , `` ```| `` -> `` ```|``` ``).

**Comment by windwp** [comment]
you should check in  a readme page. i already say it doesn't support more than 1 character.

**Comment by windwp** [comment]
#14
