### ISSUE TITLE
Endwise breaks Visual Block insertion

### ISSUE THREAD

**Issue by voyeg3r** [windwp/nvim-autopairs#135]
### Description

    add "{" over a visual block area → `Ctrl-v`, `4j`,`I{`
	        │
	        │
        use │'shaunsingh/doom-vibrant.nvim'
        use │'flrnprz/plastic.vim'
        use │'joshdick/onedark.vim' -- Theme inspired by Atom
        use │'arcticicestudio/nord-vim'
        use │'mhartington/oceanic-next'

What happens is that 'endwise' adds the } at the end of the first line
and stops, leaving all the rest of the lines with no changing

The end result should be:

        use {'shaunsingh/doom-vibrant.nvim'}
        use {'flrnprz/plastic.vim'}
        use {'joshdick/onedark.vim'} -- Theme inspired by Atom
        use {'arcticicestudio/nord-vim'}
        use {'mhartington/oceanic-next'}

It also does not repeat the last insertion when using normal 'i' 

### Mapping <cr> bug

1.If you report a bug about indent. Please remember that plugin doesn't do anything about indent.
  It just trigger the indent of your vim config so if you have wrong indent config then it will do wrong indent.
  You can check by select a block of code and press `==`
2. provide result of command `:verbose imap <cr>`.

### Steps to reproduce

Just try to insert {, ( in a visual block area

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'windwp/nvim-autopairs',
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('nvim-autopairs').setup()
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing nvim-autopairs and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by windwp** [comment]
that feature will execute when you set option enable_afterquote=true.

it can't be working on visual block mode because it use an api to set the whole line text.
it will try to disable that option after visual block mode. but make it working to what you want is not possible now.
