### ISSUE TITLE
Multi-character pairs stop working after which-key window appears for the first time

### ISSUE THREAD

**Issue by cblessing24** [windwp/nvim-autopairs#137]
### Description

Hello,

as the title says multi-character pairs (e.g. `"""` in Python) stop working after the [which-key](https://github.com/folke/which-key.nvim) menu appears for the first time.

The filetype of the aforementioned menu is `"WhichKey"`. Therefore I tried adding `"WhichKey"` to the list of disabled filetypes   but that did not fix the issue.

One fix that works for me is adding the following  check to [this function](https://github.com/windwp/nvim-autopairs/blob/e465f581f9dce556a37366587ab1fabd2bb75fbf/lua/nvim-autopairs.lua#L137):
```lua
local function is_disable()
    if vim.bo.filetype == "WhichKey" then
        -- disable for which-key menu
        return true
    end
    -- snip
end
```
I am not sure if this is the best way to fix this issue. If it is I'd be happy to open a pull request.

Cheers!

### Steps to reproduce

Here is a gif demonstrating the issue:

![nvim-autopairs-which-key-issue](https://user-images.githubusercontent.com/33834216/133928574-a55249f4-4265-41ef-a4d5-ccfe81d4c35d.gif)

**Comment by windwp** [comment]
Thank for your report it is really help.
 i already see that issue happen with floating window on nvim-cmp but that filetype is empty.
i think i will check the issue with the floating window because maybe it will happen with another filetype.
