### ISSUE TITLE
autopair on/off by vim.o.autopair

### ISSUE THREAD

**Issue by osamuaoki** [windwp/nvim-autopairs#139]
**Is your feature request related to a problem? Please describe.**
I sometimes want to disable autopair for a buffer when editing existing code.
autopair interfere sometimes.

**Describe the solution you'd like**
Just check vim.o.autopair to be true or not.
If you want to be backward compatible, nil should be treated as true.

**Describe alternatives you've considered**
I don't want to install/uninstall package to turn on/off this.

**Additional context**
I am thinking to assign keybinding to toggle this behavior.
With which-key, this is nice to have.

**Comment by osamuaoki** [comment]
Am I .... 
```
  require('nvim-autopairs').disable()
  require('nvim-autopairs').enable()
```
Looks like ...

**Comment by windwp** [comment]
vim.o belong to the  default vim.option and you can  add more filed on that . 
and you already know a  function to disable or enable. if you want to check that buffer is disable or not you can try

```lua
lua print(MPairs.state.disabled)
```

**Comment by osamuaoki** [comment]
Thanks.  It was not in the README but it was in the source.  Nice.  Now I can toggle.  Thanks.

**Comment by osamuaoki** [comment]
Just for the record, since we are using on demand loading, a bit more twist was needed.  Basically, this is what was needed.

```
-- toggle_autopairs() -- <leader>tp -- toggle autopairs
M.toggle_autopairs = function()
  local ok, autopairs = pcall(require, "nvim-autopairs")
  if ok then
    if autopairs.state.disabled then
      autopairs.enable()
      print("autopairs on")
    else
      autopairs.disable()
      print("autopairs off")
    end
  else
    print("autopairs not available")
  end
end
```
with which-key hinting this kind of non-essential bindings, it is quite useful.  Thanks again.
