### ISSUE TITLE
add support pairs with more than 2 character

### ISSUE THREAD

**Issue by doubleloop** [windwp/nvim-autopairs#14]
With this configuration:
```
require('nvim-autopairs').setup({
    pairs_map = {
        ["'"] = "'",
        ['"'] = '"',
        ['('] = ')',
        ['['] = ']',
        ['{'] = '}',
        ['`'] = '`',
        -- python strings (working)
        ["b'"] = "'",
        ["f'"] = "'",
        ["r'"] = "'",
        -- python strings (error)
        ['b"'] = '"',
        ['f"'] = '"',
        ['r"'] = '"',
    }
})
```
I get error when typing `f"`.
`E116: Invalid arguments for function MPairs.autopairs("f"",""")`

Btw, is there any way to configure extra autoclose rules based on filetype?

**Comment by windwp** [comment]
sorry my plugin is not support to check 2 character.
 

maybe I will update it when i have time.

**Comment by windwp** [comment]
it is support pair with multiple character now
