### ISSUE TITLE
Problems with vim-xkbswitch + nvim-autopairs: cannot type the letter "э"

### ISSUE THREAD

**Issue by algor512** [windwp/nvim-autopairs#146]
### Description

I use vim-xkbswitch plugin, and when russian keyboard layout is on I cannot type the letter "э" (it is ' in english layout). Instead of this, I obtain `v:lua.MPairs.autopairs_map(1,"'")`.

### Steps to reproduce

See gif (sorry for low quality):
![out2](https://user-images.githubusercontent.com/446041/135618973-3d42b641-762a-4887-bd8a-2e916e8cdb32.gif)

### Minimal config

```Lua
local install_path = vim.fn.stdpath('data') .. '/site/pack/paqs/start/paq-nvim'
if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
  vim.fn.system({'git', 'clone', '--depth=1', 'https://github.com/savq/paq-nvim.git', install_path})
end

require('paq'){
    'lyokha/vim-xkbswitch',
    'windwp/nvim-autopairs',
}

vim.opt.keymap = 'russian-jcukenwin'
vim.g.XkbSwitchLib = '/usr/lib/libxkbswitch.so'
vim.g.XkbSwitchEnabled = 1
vim.g.XkbSwitchIMappings = {'ru'}

require('nvim-autopairs').setup()
```

**Comment by windwp** [comment]
maybe you can your remove that rule '
```lua
require('nvim-autopairs').remove_rule("'")
```

**Comment by algor512** [comment]
Yes, it fixes this bug for ', but I have the same problem when I try to type Э (" in en layout) , ё (` in en layout), х ([ in en layout) and so on...

**Comment by windwp** [comment]
can you test it with a simple mapping like this
```lua
local install_path = vim.fn.stdpath('data') .. '/site/pack/paqs/start/paq-nvim'
if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
  vim.fn.system({'git', 'clone', '--depth=1', 'https://github.com/savq/paq-nvim.git', install_path})
end
require('paq'){
    'lyokha/vim-xkbswitch',
}
vim.opt.keymap = 'russian-jcukenwin'
vim.g.XkbSwitchLib = '/usr/lib/libxkbswitch.so'
vim.g.XkbSwitchEnabled = 1
vim.g.XkbSwitchIMappings = {'ru'}

_G.checkmap_quote = function()
    return vim.api.nvim_replace_termcodes("''<left>", true, false, true)
end
vim.api.nvim_buf_set_keymap(
    0,
    'i',
    "'",
    'v:lua.checkmap_quote()',
    { expr = true, noremap = true }
)
```
if that issue still happen i think you should make an issue on neovim

**Comment by algor512** [comment]
To be honest, I don't know about the status of the problem since I've stopped using neovim (so I've stopped using nvim-autopairs too).
Sorry for this.
