### ISSUE TITLE
Expand braces on <cr> and quick jump to closed pair

### ISSUE THREAD

**Issue by pianocomposer321** [windwp/nvim-autopairs#147]
Currently, if I have the following (`|` is cursor):

`use |“test”`

and I insert `{`, I get

`use {|“test”}`

If I then press `<cr>`, I would like to get something like

```
use {
    |”test”
}
```

but instead I get

```
use {
    |”test”}
```

Additionally, if I have

```
use {
    “test”|
}
```

and I type `}`, I would like it to jump to the closing `}`, like it does with https://github.com/jiangmiao/auto-pairs

If this is currently possible with the rules api, that would be sufficient.

Thanks in advance!

**Comment by windwp** [comment]
the second use case can  be implement with rule like this
```lua
local utils = require('nvim-autopairs.utils')
npairs.add_rules({
    Rule('', '}')
        :use_key('}')
        :with_cr(cond.none())
        :with_move(cond.none())
        :with_pair(function()
            local row, col = utils.get_cursor()
            local line = utils.text_get_current_line()
            -- check you are is on the end of line
            if #line ~= col then
                return false
            end
            local next_line = utils.text_get_line(0, row + 1)
            -- check the next line is '}'
            if next_line == '}' then
                return true
            end
            return false
        end)
        :set_end_pair_length(0)
        :replace_endpair(function()
            --move to next line and insert
            return '<bs><esc>ja'
        end),
 })
```

currently, the rule doesn't have a function to replace_key mapping on `<cr>` but even I add this function you still need to create your own condition to check and create your mapping key.

**Comment by pianocomposer321** [comment]
This doesn't seem to work when I use `require("nvim-autopairs.completion.cmp").setup({map_cr = true})`.
