### ISSUE TITLE
get_rule("'") returns nil: attempt to call method 'with_pair' (a nil value)

### ISSUE THREAD

**Issue by toan2406** [windwp/nvim-autopairs#148]
### Description

After update the plugin after this commit https://github.com/windwp/nvim-autopairs/commit/ff985c71417bceb168c5415813e40e656e3ea9ed, I got an error from `get_rule("'"):with_pair`. 

```
E5113: Error while calling lua chunk: /Users/name/.config/nvim/lua/plugins/autopairs.lua:5: attempt to call method 'with_pair' (a nil value)
```

This is my usage

```lua
npairs.get_rule("'"):with_pair(function()
  if vim.bo.filetype == 'reason' then
    return false
  end
end)
```

### Mapping <cr> bug

1.If you report a bug about indent. Please remember that plugin doesn't do anything about indent.
  It just trigger the indent of your vim config so if you have wrong indent config then it will do wrong indent.
  You can check by select a block of code and press `==`
2. provide result of command `:verbose imap <cr>`.

### Minimal config

```Lua
local npairs = require('nvim-autopairs')

npairs.setup()

npairs.get_rule("'"):with_pair(function()
  if vim.bo.filetype == 'reason' then
    return false
  end
end)
```

**Comment by windwp** [comment]
now there have 2 rules use single quote 1 rule specify for rust

so that function is a return to a table  of rules not a single rule
```lua
npairs.get_rule("'")[1]:with_pair(function()
  if vim.bo.filetype == 'reason' then
    return false
  end
end)
```

**Comment by toan2406** [comment]
Thank you, I will close this.
