### ISSUE TITLE
enable break line rule for all filetypes

### ISSUE THREAD

**Issue by elianiva** [windwp/nvim-autopairs#15]
Is there a way to enable break line rule for *all* filetypes without having to list the filetypes manually? I'd love to be able to set something like `break_line_filetype = { "*" }` and it enables the rule for all filetypes. Thanks in advance!

**Comment by windwp** [comment]
fix it
check readme

**Comment by smithbm2316** [comment]
Hey @windwp! Thank you so much for this plugin, it seems to be exactly what I've been wanting for months now after trying jiangmiao/autopairs and lexima.vim and feeling as both were a bit overkill for me. 

I am a bit confused by the readme on how to enable `break_line_filetype` for all files. In the [readme talking about breaking line inside pairs or html](https://github.com/windwp/nvim-autopairs#break-line-on-html-or-inside-pairs), it says:
> By default nvim-autopairs don't mapping <CR> on insert mode if you want to do that you need to mapping it by your self
If we have to manually set `<CR>` to break lines like this:

```
Before                  Input         After
----------------------------------------------------
function {|}           <CR>         function {
                                       |
                                    }
```
where my cursor will be auto-indented inside the function when I press `<CR>`, why do you have the `break_line_filetype` option? At the moment I have left the setup in my config as default, but my cursor does not end up indented, it ends up like this:
```
Before                  Input         After
----------------------------------------------------
function {|}           <CR>         function {
                                    |}
```
I was wondering if you could just explain to me what the `break_line_filetype` options is doing? I am happy to configure my own setup if necessary, I just am a bit new to writing Lua 🙂. Thank you so much for the plugin and your help!

**Comment by windwp** [comment]
you need to map `<cr`  with your completion to make a break line  function working


 reademe have 2 sample to mapping cr with nvim-compe and completion nvim

a breakline list filetype is a list of filetype to enable this function

**Comment by smithbm2316** [comment]
> you need to map `<cr` with your completion to make a break line function working
> 
> reademe have 2 sample to mapping cr with nvim-compe and completion nvim
> 
> a breakline list filetype is a list of filetype to enable this function

🤦 I totally didn't see that part of the readme. Thank you so much!
