### ISSUE TITLE
Nested block issue where closing pair is not generated.

### ISSUE THREAD

**Issue by ckipp01** [windwp/nvim-autopairs#16]
My apologies for the bad title, but unsure how to accurately name this situation. However, when you open a block, hit new line and attempt to open another where the closing for the first is directly after your cursor the closing pair isn't generated.

### An example

```
val x = {
|}
```
At the `|` if I was to enter `{` I'd expect the following:

```
val x = {
{|}}`
```
However, I'm instead left with the following:
```
val x = {
{|}`
```

Note that this doesn't happen if there is a space between the cursor and the closing pair.

```
val x = {
| }
````

The example above would correctly produce:

```
val x = {
{|} }
```

**Comment by windwp** [comment]
hi it is a feature to smart close pair.
my code only check pair in same line and it think you want to close pair because you don't have a { before the cursor on the same line.
it will not check it if the next character is not }
```
|} ==> {|}
{          |} ==> {{      |}}


````

**Comment by ckipp01** [comment]
> my code only check pair in same line and it think you want to close pair because you don't have a { before the cursor on the same line.

But this won't always be the case right? There may be plenty of times that the opening pair is on the line above?

**Comment by windwp** [comment]
I add an option for disable that 

https://github.com/windwp/nvim-autopairs#dont-add-pairs-if-it-already-have-a-close-pairs-in-same-line

**Comment by ckipp01** [comment]
> I add an option for disable that
> 
> [windwp/nvim-autopairs#dont-add-pairs-if-it-already-have-a-close-pairs-in-same-line](https://github.com/windwp/nvim-autopairs#dont-add-pairs-if-it-already-have-a-close-pairs-in-same-line)

Ah great, is it possible to set that per filetype? Or is it an all or nothing?

**Comment by windwp** [comment]
it will disable all filetype

**Comment by davidsierradz** [comment]
Hi. Is this setting available? I'm reading the link above, but don't see the actual code for it. Thanks.

**Comment by windwp** [comment]
@davidsierradz what do you want ? 
this setting is not available in a new version.  You can add space before you open bracket. 
if you still want this options you can make a new issue
