### ISSUE TITLE
Change setup option locally for a certain filetype

### ISSUE THREAD

**Issue by davidsierradz** [windwp/nvim-autopairs#163]
Hi!

**Is your feature request related to a problem? Please describe.**
I would like to deactivate `enable_check_bracket_line` in a certain filetype, keeping the default behavior in all other ones.

**Describe the solution you'd like**
Actually, I'm not really sure how the feature would look like or even if it's possible.

**Describe alternatives you've considered**
I though of using an autocommand (or `after/ftplugin/...`), but then I lost all base customizations:

```lua
-- init.lua
local npairs = require('nvim-autopairs')
local cond = require('nvim-autopairs.conds')
npairs.setup {enable_check_bracket_line = true}
npairs.get_rule("'")[1]:with_pair(cond.not_filetypes({'clojure'})) -- [1]

-- after/ftplugin/clojure.lua
local npairs = require('nvim-autopairs')
npairs.setup {enable_check_bracket_line = false}
```

The rule in `[1]` is lost.

Thank you

**Comment by windwp** [comment]
i think you can write a custom condition
on setup you call npairs.setup {enable_check_bracket_line = false}
```lua
            local conds = require('nvim-autopairs.conds')
            local function combine_ft_and_bracket()
                local check_bracket = conds.check_is_bracket_line()
                return function (opts)
                    if vim.bo.filetype ~= 'clojure' then
                        return check_bracket(opts)
                    end
                end
            end
```

 then add a new condition on every bracket rule
