### ISSUE TITLE
Using `<CR>` doesn't create the extra line

### ISSUE THREAD

**Issue by nimeco** [windwp/nvim-autopairs#174]
### Description

Greetings,

This is my first time trying to configure Neovim to suit my needs, and have been struggling to make autopairs work.

https://user-images.githubusercontent.com/20692282/139613600-a89b2c94-319c-4be0-b009-5417b768aef2.mp4

I'm using O to open a new line above, what I wanted is that there was a new line and the cursor stayed at one line above, like vscode does. I've read multiple closed issue requests here, about `<CR>` mapping, but tried a lot of stuff/combinations and I couldn't make it work.
I don't really understand the interaction between:

`['<CR>'] = cmp.mapping.confirm...` inside cmp setup
`map_cr = false` option at autopairs setup, tried with true as well
`cmp.event:on('confirm_done', cmp_autopairs.on_confirm_done...`
what should and what shouldn't be there, and how one replaces another.
I tried many combinations with all these, enabling/disabling the [<CR>] mapping, enabling/disabling the map_cr, the confirm_done was always on though because that's what it seemed right from README.

So starting from this:
`{|}` and `<CR>`
I'm getting this:
```
{
|}
```
Where I wanted this:
```
{
|
}
```

Indentation seems right, but from what I read, it might be the indentation's fault that the new line isn't created or something?
Autopairs setup is called after cmp.
`indentexpr` gives me ` indentexpr=nvim_treesitter#indent()`.
`verbose map <cr>` is:
```
i  <CR>        *@<Cmd>call v:lua.cmp.utils.keymap.listen.run(155875069)<CR>
i  <CR>        * v:lua.MPairs.completion_confirm()
        Last set from ~\AppData\Local\nvim\init.vim line 307
```
There was a time only the line above was showing up. I don't know which one is correct, if both should show up, or only one, and which one in this case.
Tried setting `check_ts` to true/false as well, but it seems it doesn't make a difference.
Indentation is alraight, but from what I read from other posts that it might be the indentation's fault that the new line isn't created or something?
Weirdly enough, I've tried some custom rules to check if they would work, to see if I could add the same thing I'm trying to do as a custom rule, but for some reason some rules worked and others didn't.
I'm on Neovim on Windows 10.

Some of init.vim for cmp/autopairs/treesitter
```
    -- Setup cmp --
    local cmp = require'cmp'
    cmp.setup({
        snippet = {
            expand = function(args)
                vim.fn["vsnip#anonymous"](args.body)
            end,
        },
        mapping = {
            ['<C-d>'] = cmp.mapping(cmp.mapping.scroll_docs(-4), { 'i', 'c' }),
            ['<C-f>'] = cmp.mapping(cmp.mapping.scroll_docs(4), { 'i', 'c' }),
            ['<C-Space>'] = cmp.mapping(cmp.mapping.complete(), { 'i', 'c' }),
            ['<C-y>'] = cmp.config.disable, -- If you want to remove the default `<C-y>` mapping, You can specify `cmp.config.disable` value.
            ['<C-e>'] = cmp.mapping({
                i = cmp.mapping.abort(),
                c = cmp.mapping.close(),
            }),
            ['<CR>'] = cmp.mapping.confirm({
                behavior = cmp.ConfirmBehavior.Insert,
                select = false
            }),
            ["<Tab>"] = cmp.mapping(function(fallback)
            if cmp.visible() then
                cmp.select_next_item()
            elseif has_words_before() then
                cmp.complete()
            else
                fallback()
            end
            end, { "i", "s" }),
        },
        sources = cmp.config.sources({
            { name = 'nvim_lsp' },
            { name = 'vsnip' },
        },
        {
            { name = 'buffer' },
        })
    })


    -- Setup autopairs --
    local npairs = require('nvim-autopairs')
    npairs.setup({
        check_ts = true,
        ts_config = {
            javascript = {'string'},
        },
        map_complete = true,
        map_cr = false,
        auto_select = true,
    })
    local Rule = require('nvim-autopairs.rule')
    local cond = require('nvim-autopairs.conds')
    local utils = require('nvim-autopairs.utils')

    local cmp_autopairs = require('nvim-autopairs.completion.cmp')
    cmp.event:on('confirm_done', cmp_autopairs.on_confirm_done({
        map_char = {
            tex = '',
            javascript = '{'
        }
    }))


    -- Setup lspconfig --
    local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
    require('lspconfig').tsserver.setup {
        on_attach = on_attach,
        capabilities = capabilities,
        flags = {
            debounce_text_changes = 150,
        },
        cmd = { "typescript-language-server.cmd", "--stdio" },
    }
  

    -- Setup treesitter --
    require'nvim-treesitter.configs'.setup {
        ensure_installed = "all",
        highlight = {
            enable = true,
            additional_vim_regex_highlighting = false,
        },
        indent = {
            enable = true
        },
        refactor = {
            highlight_definitions = { enable = true },
            highlight_current_scope = { enable = true },
            smart_rename = {
                enable = true,
                keymaps = {
                    smart_rename = "grr",
                },
            },
            navigation = {
                enable = true,
                keymaps = {
                    goto_definition = "gnd",
                    list_definitions = "gnD",
                    list_definitions_toc = "gO",
                    goto_next_usage = "<a-*>",
                    goto_previous_usage = "<a-#>",
                },
            },
        },
        autopairs = {enable = true},
    }
```

The whole init file is here: [init.txt](https://github.com/windwp/nvim-autopairs/files/7450410/init.txt)

Thanks a lot in advance!

### Mapping <cr> bug

1.If you report a bug about indent. Please remember that plugin doesn't do anything about indent.
  It just trigger the indent of your vim config so if you have wrong indent config then it will do wrong indent.
  You can check by select a block of code and press `==`
2. provide result of command `:verbose imap <cr>`.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'windwp/nvim-autopairs',
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('nvim-autopairs').setup()
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing nvim-autopairs and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by windwp** [comment]
-- Setup autopairs --
    local npairs = require('nvim-autopairs')
    npairs.setup({
        check_ts = true,
        ts_config = {
            javascript = {'string'},
        },
        map_complete = true,    -----------------  it doesn't have map_complete
        map_cr = false, -----------------------------------------------> WRONG change to true ? where do you get that ??
        auto_select = true,  --- ---------- it doesn't have auto_select
    })

**Comment by nimeco** [comment]
You mean if I use check_ts, it doesn't have map_complete and auto_select? Those are only if you opt for not using treesitter?

https://github.com/windwp/nvim-autopairs/issues/127 was trying this

Changed it to true back again, but all the same.

**Comment by windwp** [comment]
map_complete and auto_select is use for cmp.setup but it is deprecate.
try to call the default setup() without option

**Comment by nimeco** [comment]
Still the same.
After reloading init.vim, is there any case where a modification would only take place after RESTARTING vim altogether? Because I'm only reloading init.vim and testing.

**Comment by windwp** [comment]
cmp.event:on('confirm_done', cmp_autopairs.on_confirm_done({
        map_char = {
            tex = '',
            javascript = '{'
        }
    }))


because you do this

**Comment by nimeco** [comment]
Ahhh, yeah, that was me trying to mess with the previous issue.
Just removed it.
Thanks a lot!!
