### ISSUE TITLE
Wrap lisp function instead of appending `()`

### ISSUE THREAD

**Issue by tami5** [windwp/nvim-autopairs#175]
**Is your feature request related to a problem? Please describe.**

I find my self disabling the simple yet awesome cmp addition, as you may know, in lisp functions get wrapped wtih parentheses instead of having `()`  appended it to it.

**Describe the solution you'd like**

Wrap function names with () in lisp filetypes `{ "clojure", "clojurescript", "fennel", "janet", ........}`.

**Comment by windwp** [comment]
https://github.com/windwp/nvim-autopairs/blob/master/lua/nvim-autopairs/completion/cmp.lua

the code for append ( is simple . i think you  can write that wrapper

**Comment by tami5** [comment]
I'm going to try to fix it and open a pr, hopefully I get right 😆

**Comment by tami5** [comment]
@windwp 

```lua
if map_cr then
        cmp_setup.mapping = {
            ['<CR>'] = cmp.mapping.confirm({
                behavior = behavior,
                select = opt.auto_select,
            }),
        }
        vim.api.nvim_set_keymap(
            'i',
            '<CR>',
            'v:lua.MPairs.autopairs_cr()',
            { expr = true, noremap = true }
        )
    end
```

What is this part for? I see both map_cr and map_complete
