### ISSUE TITLE
cond.not_filetype does not work

### ISSUE THREAD

**Issue by tami5** [windwp/nvim-autopairs#177]
### Description

Hello there, I tried to have `'` disabled in a number of file types, but didn't work. 

### Minimal config

```Lua
function()
  local npairs = require "nvim-autopairs"
  local Rule = require "nvim-autopairs.rule"
  local cond = require "nvim-autopairs.conds"
  npairs.setup {
    blank_line_filetype = nil,
    pairs_map = {
      -- ["'"] = "'",
      ['"'] = '"',
      ["("] = ")",
      ["["] = "]",
      ["{"] = "}",
      ["`"] = "`",
    },
    disable_filetype = { "TelescopePrompt" },
    html_break_line_filetype = { "html", "vue" },
    ignore_next_char = "[%w%.%+%-%=%/%,\"'{}%[%]]",
  }

  npairs.add_rule(Rule("'", "'"):with_pair(cond.not_filetypes { "clojure", "clojurescript", "fennel", "markdown" }))
  npairs.add_rule(Rule("|", "|", "rust"))
end
```

**Comment by windwp** [comment]
you need to  remove the rule on basic rule first
https://github.com/windwp/nvim-autopairs/blob/master/lua/nvim-autopairs/rules/basic.lua

``` lua 
all that option is deprecated
 blank_line_filetype = nil,
    pairs_map = {
      -- ["'"] = "'",
      ['"'] = '"',
      ["("] = ")",
      ["["] = "]",
      ["{"] = "}",
      ["`"] = "`",
    },
html_break_line_filetype = { "html", "vue" },
```

**Comment by tami5** [comment]
okay I see what was happening 😆, it's been so long I didn't update my config. It's a bit wired though, having to call add_rule/remove rule.

it would've been better, I believe if we all stick to declarative approach, e.g.

Before:
```lua 
  npairs.remove_rule "'"
  npairs.remove_rule "`"

  npairs.add_rule(Rule("`", "`"):with_pair(Cond.not_filetypes {
    "clojure",
    "clojurescript",
    "fennel",
  }))
  npairs.add_rule(Rule("'", "'"):with_pair(Cond.not_filetypes {
    "clojure",
    "clojurescript",
    "fennel",
    "markdown",
  }))
  npairs.add_rule(Rule("%(.*%)%s*%=$", "> {}", {
    "typescript",
    "typescriptreact",
    "javascript",
    "javascriptreact",
  }):use_regex(true):set_end_pair_length(1))

  npairs.add_rule(Rule("|", "|", "rust"))
```

After:
```lua
npairs.setup {
    rules = {
      ["%(.*%)%s*%=$"] = {
        rhs = "> {}", -- custom?
        typescript = true,
        javascript = true,
        javascriptreact = true,
        typescriptreact = true,
        opts = {
          regex = true,
          pair_length = 1,
        },
      },
      ["{"] = false, -- disable globally
      ["|"] = { rust = true },
      [{ "'", "`" }] = { -- overwrite
        clojure = false,
        clojurescript = false,
        fennel = false,
        markdown = false,
      },
    },
  }
```

**Comment by windwp** [comment]
i use chaining because i can combine a multiple condition and re use it.
On bracket function i can easy reuse it from basic and rule. 
https://github.com/windwp/nvim-autopairs/blob/master/lua/nvim-autopairs/rules/basic.lua#L18
you can't not do that when you create only 1 object

```lua
 [{ "'", "`" }] = { -- overwrite
        clojure = false,
        clojurescript = false,
        fennel = false,
        markdown = false,
      },
it is not better than
 Rule({ "'", '`', { '-clojure', '-clojurescript', '-fennel', '-markdown' } })

and set it "{"=false is not better than complete remove it and how do you handle when it have multiple rule with {.
```

**Comment by tami5** [comment]
> i use chaining because i can combine a multiple condition and re use it.
I understand from developer point of view and btw I think it's very smart. But my focus on the api and configuration level.

> it is not better than Rule({ "'", '`', { '-clojure', '-clojurescript', '-fennel', '-markdown' } })

I meant by this 
```lua
 [{ "'", "`" }] = {..}-- overwrite
``` 
that it applies to both `'` and `\\`` rule
\=\=\=
```lua
npairs.add_rule(Rule("`", "`"):with_pair(Cond.not_filetypes {
    "clojure",
    "clojurescript",
    "fennel",
  }))
  npairs.add_rule(Rule("'", "'"):with_pair(Cond.not_filetypes {
    "clojure",
    "clojurescript",
    "fennel",
    "markdown",
  }))
```

> and we have function add_rules to add multiple rule

I understand, but `setup { rules = { [ overwrite_defaults, change_defaults, disable_rules ]} }` is much cleaner and easy to grasp 

Also pairs/rhs should be default to lhs, because of the plugin being auto-pairs, unless maybe user provide `opts.rhs or rhs` explicitly

anyways this just me expressing my ideals, and it's not a critical right now

**Comment by windwp** [comment]
it is similar to vim.api.nvim_set_keymap we have many lua custom library to mapping key but result is same.

you can try print(vim.inspect(any-rule)). lt is not difficult to convert it to what you want.
you can clear all rule then create your own creator but i am happy with it now so I will not change it.

PS: you can check on wiki I am not prefer to use cond.not_filetypes
