### ISSUE TITLE
Auto <CR> doesn't work. Reason unknown.

### ISSUE THREAD

**Issue by zim0369** [windwp/nvim-autopairs#179]
### Description

```
Before        Input         After
------------------------------------
{|}           <CR>          {
                                |
                            }
------------------------------------
```
This feature doesn't work becuase of treesitter or maybe because of lua configs. I'm not sure the cause. I tried to find it but in vain.

Also the auto-pairs for three backticks(codeblocks) doesn't work.

### Mapping <cr> bug

1.If you report a bug about indent. Please remember that plugin doesn't do anything about indent.
  It just trigger the indent of your vim config so if you have wrong indent config then it will do wrong indent.
  You can check by select a block of code and press `==`
2. provide result of command `:verbose imap <cr>`.

### Steps to reproduce

-

### Minimal config

```Lua
https://github.com/zim0369/dotfiles/tree/main/config/nvim
```

**Comment by windwp** [comment]
not follow issue template

**Comment by arpangreat** [comment]
> ### Description
> 
> ```
> Before        Input         After
> ------------------------------------
> {|}           <CR>          {
>                                 |
>                             }
> ------------------------------------
> ```
> This feature doesn't work becuase of treesitter or maybe because of lua configs. I'm not sure the cause. I tried to find it but in vain.
> 
> Also the auto-pairs for three backticks(codeblocks) doesn't work.
> 
> ### Mapping <cr> bug
> 
> 1.If you report a bug about indent. Please remember that plugin doesn't do anything about indent.
>   It just trigger the indent of your vim config so if you have wrong indent config then it will do wrong indent.
>   You can check by select a block of code and press `==`
> 2. provide result of command `:verbose imap <cr>`.
> 
> 
> ### Steps to reproduce
> 
> -
> 
> ### Minimal config
> 
> ```Lua
> https://github.com/zim0369/dotfiles/tree/main/config/nvim
> ```
> 

@zim0369 because you are using nvim-cmp can you put this block of code in your config ?

```lua
local cmp_autopairs = require('nvim-autopairs.completion.cmp')
local cmp = require('cmp')
cmp.event:on( 'confirm_done', cmp_autopairs
```

**Comment by zim0369** [comment]
> ```lua
> local cmp_autopairs = require('nvim-autopairs.completion.cmp')
> local cmp = require('cmp')
> cmp.event:on( 'confirm_done', cmp_autopairs
> ```

That solved my problem. Thank you so much!!!!
