### ISSUE TITLE
Rule arguments

### ISSUE THREAD

**Issue by sarmong** [windwp/nvim-autopairs#186]
It is not very clear from the doc (neither readme, nor wiki) what the arguments for `Rule` function are.

E.g.
```lua
Rule("$$","$$","tex") -- not very clear what `$$` are. 3rd argument is file extension? 

-- disable for .vim files, but it work for another filetypes
Rule("a","a","-vim") -- what is "a", "a"? What rules does it disable for vim files
```

Would appreciate some help.

**Comment by windwp** [comment]
1st and second argument is a pairs and 3rd is a filetype.  You can use string or a table(array).
If you add minus "-" before filetype mean that rule is not working on that filetype.

maybe it is not clear but when you understand it is make easy to add new rule .
