### ISSUE TITLE
Why is pairs not working inside quote?

### ISSUE THREAD

**Issue by budimanjojo** [windwp/nvim-autopairs#189]
Hello, here's what I want:
`"|"` insert `{` => `"{|}"`
How do I create this rule? Thanks before.

**Comment by windwp** [comment]
```
local ignored_next_char = string.gsub([[ [%w%%%'%[%"%.] ]],"%s+", "")
```
you can add bracket inside quote but the default option is skip " quote on next character 
so  on your example  it is not working. 
if you add  space inside quote that you can add bracket.

**Comment by budimanjojo** [comment]
Add space inside quote is still not working though. Is there any way I can override this rule?

**Comment by budimanjojo** [comment]
https://github.com/windwp/nvim-autopairs/blob/master/lua/nvim-autopairs/rules/basic.lua
Is this the default rule?

**Comment by windwp** [comment]
Yes. basic.lua has all the default rule

"  |   "  input  " {|}  "   i think it should work if you use a default setup
 you can remove double quote on ignored_next_char

**Comment by budimanjojo** [comment]
Thank you! I got it working now.. But I want to ask when do I need `"` or `'` in ignored_next_char? Because you must have a reason to put them there right?

**Comment by windwp** [comment]
try to add bracket here |"aa"

**Comment by budimanjojo** [comment]
okay I so that's the reason. maybe I should make my own custom rule for specific filetype then. Because my current problem only occurs when I'm templating. Need a lot of `"{{ var }}"`. Thanks for the help 😊
