### ISSUE TITLE
Help with tab?

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [windwp/nvim-autopairs#19]
So this doesn't really have anything to do with autopairs really but I am using nvim-autopairs's esc function to try and write a mapping for tab and shift-tab with completion-nvim and vsnip and was hoping you could help me and/or are maybe using something similar for your personal neovim setup.

This is what I am using. Whe

```lua
MUtils.tab=function()
    if vim.fn.pumvisible() ~= 0  then
        return npairs.esc("<C-n>")
    else
        if vim.fn["vsnip#available"](1) ~= 0 then
            return npairs.esc("<Plug>(vsnip-expand-or-jump)")
        else
            return npairs.esc("<Tab>")
        end
    end
end

MUtils.s_tab=function()
    if vim.fn.pumvisible() ~= 0  then
        return npairs.esc("<C-p>")
    else
        if vim.fn["vsnip#jumpable"](-1) ~= 0 then
            return npairs.esc("<Plug>(vsnip-jump-prev)")
        else
            return npairs.esc("<C-h>")
        end
    end
end
```

**Comment by windwp** [comment]
you can't use plug in esc

https://www.reddit.com/r/neovim/comments/kup1g0/feedkey_plug_in_lua_how/?utm_medium=android_app&utm_source=share

**Comment by Th3Whit3Wolf** [comment]
Ahhh, this is the first I've heard of feedkeys

**Comment by windwp** [comment]
function _G.MUtils.tab_completion()
  if vim.fn['vsnip#jumpable'](1) > 0 then
    return MUtils.esc('<Plug>(vsnip-jump-next)')
  end
  if vim.fn['vsnip#expandable']() > 0 then
    return MUtils.esc('<Plug>(vsnip-expand)')
  end
  
end


it is my setup i think it is very similar to you
