### ISSUE TITLE
Add mapping to skip over closing pair

### ISSUE THREAD

**Issue by noib3** [windwp/nvim-autopairs#190]
In `delimitMate` typing `<S-Tab>` after a closing bracket/quote will skip that character, e.g. `(<S-Tab>` becomes `()|`. Is there a way to get the same effect with this plugin?

**Comment by windwp** [comment]
sorry tab and <s-tab>  mapping it not provide default because it can be conflict with completion like nvim-cmp.
you can create a customrule to do that or use another plugin.

https://github.com/windwp/nvim-autopairs/issues/167

**Comment by noib3** [comment]
You wouldn't need to actually map `<Tab>`, just expose something like a `<Plug>autopairs-skip-closing` mapping that users can use if they want to.

**Comment by windwp** [comment]
Are you try a tabout plugin it can jump cross multiple line and text by treesitter.
if i do that on this plugin by rule it only move  cursor left or right with 1 step.
