### ISSUE TITLE
Make <BS> work over multiple lines

### ISSUE THREAD

**Issue by noib3** [windwp/nvim-autopairs#191]
It'd be nice if `<BS>` could group pairs together over multiple lines, for example

```
{
|<BS>
}
```
becomes
```
{|}
```
instead of the current behavior:
```
{|
}
```

**Comment by jakubkaczor** [comment]
Yes, that would be very nice to have, but I would like to suggest more general approach. That is one working with `<BS>`, `<C-h>` and `<C-w>`.
