### ISSUE TITLE
Cannot update

### ISSUE THREAD

**Issue by bryant-the-coder** [windwp/nvim-autopairs#192]
### Description

When i run `:PackerSync` or `:PackerUpdate`, it say that 
```
✗ Failed to update windwp\nvim-autopairs
```
How can i fix that?

### Mapping <cr> bug

1.If you report a bug about indent. Please remember that plugin doesn't do anything about indent.
  It just trigger the indent of your vim config so if you have wrong indent config then it will do wrong indent.
  You can check by select a block of code and press `==`
2. provide result of command `:verbose imap <cr>`.

### Steps to reproduce

Just type in `:PackerSync` or `:PackerUpdate`, then error pops out... 

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'windwp/nvim-autopairs',
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('nvim-autopairs').setup()
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing nvim-autopairs and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by windwp** [comment]
you can remove it  and install again

**Comment by bryant-the-coder** [comment]
It works now thx

**Comment by bryant-the-coder** [comment]
The error is still here after wuitting nvim

**Comment by windwp** [comment]
are you try delete the folder ?

**Comment by bryant-the-coder** [comment]
I did and it solved it

**Comment by bryant-the-coder** [comment]
Can u share your nvim conf?

**Comment by windwp** [comment]
no 😋😋

**Comment by bryant-the-coder** [comment]
why???

**Comment by DartMitai** [comment]
> no 😋😋
we can ask you to add an example configuration for lua to the documentation
