### ISSUE TITLE
Add `map_c_h` option

### ISSUE THREAD

**Issue by jakubkaczor** [windwp/nvim-autopairs#193]
It would be very nice to have an option analogical to `map_bs` and `map_c_w`, but for `<C-h>`, that is `map_c_h`. I don't know if my configuration is close to efficient, but for me, `map_c_w` simplified it very much. `map_c_h` is the only one missing. Also, for the sake of completeness and intuitiveness it would be good to have. I can imagine a user discovering `map_bs`, `map_c_w` and then being surprised by the `map_c_h` not working.

**Comment by windwp** [comment]
you can do that by add this.
`imap <c-h> <bs>`

**Comment by jakubkaczor** [comment]
It may seem equivalent at first, but this disables a user from mapping `<BS>` to something else.
