### ISSUE TITLE
Don't autocomplete `#'` to `#''` for r files 

### ISSUE THREAD

**Issue by sebffischer** [windwp/nvim-autopairs#196]
In `R`, `#'` has a special meaning. Can you please change the defaults to add this rule, (see title)? I tried to fix it myself but I was unable to do so and had to resort to the following 

```lua
local npairs = require("nvim-autopairs")
local cond = require('nvim-autopairs.conds')
local cmp_autopairs = require('nvim-autopairs.completion.cmp')
local cmp = require('cmp')


npairs.setup({
  break_line_filetype = nil,
  check_ts = true,
  disable_filetype = {"TelescopePrompt"}
})

npairs.remove_rule("'")
npairs.add_rules({
  Rule("'", "'", "^#$")
    :with_pair(cond.not_before_regex("^#$"))
})
```

This is of course undesirable but I was unable to change the rule for `#'` for R files while keeping the existing rules for `'`.

**Comment by windwp** [comment]
Rule("'", "'", "^#$")  
you set wrong file type the third argument should be a file type of R language   lua print(vim.bo.filetype)

```
npairs.add_rules({
  Rule("'", "'", "R")
    :with_pair(cond.not_before_regex("^#$"))
})
```

Or you can use 
```lua
--- get the first rule of '
require('nvim-autopairs').get_rule("'")[1] 
:with_pair(cond.not_before_regex("^#$"))
```

**Comment by sebffischer** [comment]
Ups, that was a typo (I used "r" instead of "^#$" before).
The second solution is the one I was looking for, thanks!
