### ISSUE TITLE
Map <CR> on coc-nvim doc

### ISSUE THREAD

**Issue by vpeopleonatank** [windwp/nvim-autopairs#197]
**Is your feature request related to a problem? Please describe.**
After installing nvim-autopairs, I can't use enter to select item from coc-nvim 's autocompletion menu, and the cursor will be in the next line 

**Describe the solution you'd like**
Use enter select item from coc-nvim 's autocompletion menu normally

**Describe alternatives you've considered**

**Additional context**
- Unexpected behaviour

https://user-images.githubusercontent.com/30976876/147313458-a4064546-9958-4bfc-abf2-0c57992f1f5d.mp4

**Comment by windwp** [comment]
you can try set option map_cr = false on setup

**Comment by vpeopleonatank** [comment]
It works, but lose this ability. Thank you.
```
Before        Input         After
------------------------------------
{|}           <CR>          {
                                |
                            }
------------------------------------
```

**Comment by windwp** [comment]
i forget about this
I am not test but i think it should work

```lua
local remap = vim.api.nvim_set_keymap
local npairs = require('nvim-autopairs')
npairs.setup({map_cr=false})

-- skip it, if you use another global object
_G.MUtils= {}

MUtils.completion_confirm=function()
  if vim.fn.pumvisible() ~= 0  then
    vim.fn[" coc#_select_confirm"]()
  else
    return npairs.autopairs_cr()
  end
end

remap('i' , '<CR>','v:lua.MUtils.completion_confirm()', {expr = true , noremap = true})
```

**Comment by vpeopleonatank** [comment]
> 

It works, thank you :D

**Comment by vpeopleonatank** [comment]
> i forget about this I am not test but i think it should work
> 
> ```lua
> local remap = vim.api.nvim_set_keymap
> local npairs = require('nvim-autopairs')
> npairs.setup({map_cr=false})
> 
> -- skip it, if you use another global object
> _G.MUtils= {}
> 
> MUtils.completion_confirm=function()
>   if vim.fn.pumvisible() ~= 0  then
>     vim.fn["coc#_select_confirm"]()
>   else
>     return npairs.autopairs_cr()
>   end
> end
> 
> remap('i' , '<CR>','v:lua.MUtils.completion_confirm()', {expr = true , noremap = true})
> ```

I think `vim.fn["coc#_select_confirm"]()` line should change to `return vim.fn["coc#_select_confirm"]()`
without it, when I press <CR> on completion menu, it return null string.
