### ISSUE TITLE
I have a good idea for auto pairs mode

### ISSUE THREAD

**Issue by steven-jostar** [windwp/nvim-autopairs#198]
Yeah, if you use C++ or other languages that use braces, you should meet some problem. Such as semicolon at statement ended  and more.So I have a good idea to help them.
As you see("|" means cursor):
```javascript
const a = () => {|
```
Then, we can get:
```javascript
const a = () => {|}
```
But in my idea, this will do noting:
```javascript
const a = () => {|
```
Until you press "enter":
```javascript
const a = () => {
  |
}
```
This is somewhat similar to endwise, but it has more features, such as following ones:

```javascript
|
```
Press `"`:
```javascript
"|
```
Then press `enter`:
```javascript
""
|
```
This is useful in some languages that doesn't need semicolon.

**Comment by steven-jostar** [comment]
Oh, one thing I forgot. Try to imagine you have these codes:
```cpp
class Demo |
```
You want to complete this class, then you press `{`:
```cpp
class Demo {|
```
Because C++ need a semicolon after class defintion, so you try to add one:
```cpp
class Demo {;|
```
That's right! As you see, you just need to press a semicolon after the brace! After, you just need to press `enter`:
```cpp
class Demo {
  |
};
```
If you don't want to wrap:
```cpp
// You just need to add a `}` and complete your semicolon!
class Demo {};|
```

**Comment by steven-jostar** [comment]
What do you think of this?

**Comment by windwp** [comment]
it is good idea maybe you can do that and add to a custom rules page
https://github.com/windwp/nvim-autopairs/wiki/Custom-rules

**Comment by steven-jostar** [comment]
Can  I create a PR?

**Comment by windwp** [comment]
you can add your rule on wiki page it don't need to create a PR.

if you need to modify the main function to  create  that rule i will accept a PR to modify that 
but I will not merge some specify custom rule.
