### ISSUE TITLE
Markdown Code Fence Block Support

### ISSUE THREAD

**Issue by axieax** [windwp/nvim-autopairs#201]
### Description

I've originally filed an issue on nvim-treesitter [here](https://github.com/nvim-treesitter/nvim-treesitter/issues/2178), but upon further inspection, I'm not sure if this is a treesitter issue anymore. It seems that the end pair isn't being indented appropriately, although the indent size should be ok.

### Mapping <cr> bug

1.If you report a bug about indent. Please remember that plugin doesn't do anything about indent.
  It just trigger the indent of your vim config so if you have wrong indent config then it will do wrong indent.
  You can check by select a block of code and press `==`
2. provide result of command `:verbose imap <cr>`.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'windwp/nvim-autopairs',
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('nvim-autopairs').setup()
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing nvim-autopairs and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by windwp** [comment]
Read please.
> .If you report a bug about indent. Please remember that plugin doesn't do anything about indent.
> It just trigger the indent of your vim config so if you have wrong indent config then it will do wrong indent.
> You can check by select a block of code and press ==

**Comment by axieax** [comment]
Hi @windwp, I think you've misunderstood my issue. I've clarified that this is not due to incorrect indentings, but rather the endwise pair not being placed appropriately :)
