### ISSUE TITLE
Error with cmp integration

### ISSUE THREAD

**Issue by lu5je0** [windwp/nvim-autopairs#202]
### Description

After commit https://github.com/hrsh7th/nvim-cmp/commit/3f7b7b258ab4e5cbe96ad98355b45f7753aa6f64, the following errors were reported in the completion.

Error executing vim.schedule lua callback: ...opt/nvim-autopairs/lua/nvim-autopairs/completion/cmp.lua:37: attempt to call method 'get_completion_item' (a nil value)
stack traceback:
        ...opt/nvim-autopairs/lua/nvim-autopairs/completion/cmp.lua:37: in function 'callback'
        ...im/site/pack/packer/opt/nvim-cmp/lua/cmp/utils/event.lua:47: in function 'emit'
        ...hare/nvim/site/pack/packer/opt/nvim-cmp/lua/cmp/core.lua:431: in function 'cb'
        vim.lua:285: in function <vim.lua:285>

### Minimal config

```Lua
None
```

**Comment by amistyrain** [comment]
me too
