### ISSUE TITLE
Add matching <space> after brackets

### ISSUE THREAD

**Issue by kuntau** [windwp/nvim-autopairs#205]
**Is your feature request related to a problem? Please describe.**
More often than not after creating pair, I want to add space after them like `{ val = true }`, current behavior produce `{ val = true}`

**Describe the solution you'd like**
After a pair is created if I insert ` `, I want the matching ` ` on the other end to it become `{ | }` or `( | )`. `|` is the cursor

**Describe alternatives you've considered**
I have to manually put ` ` on the other side.

**Additional context**
I would be great if I <kbd>Backspace</kbd>, it will also delete the matching <kbd>space</kbd>

Thank you!

**Comment by windwp** [comment]
https://github.com/windwp/nvim-autopairs/wiki/Custom-rules

**Comment by kuntau** [comment]
Thank you. I missed that 🙇🏽

**Comment by colepeters** [comment]
I can't get any of the provided solutions in the Wiki to work for me. However, I've noticed that if I explicitly source the file with the rules config in it after opening Neovim, the rule starts working. 🧐

Here's my full configuration:

```lua
local status_ok, npairs = pcall(require, 'nvim-autopairs')
if not status_ok then
  return
end

npairs.setup({
  disable_filetype = { 'TelescopePrompt' },
})

local cmp_autopairs = require('nvim-autopairs.completion.cmp')
local cmp_status_ok, cmp = pcall(require, 'cmp')
if not cmp_status_ok then
  return
end

cmp.event:on('confirm_done', cmp_autopairs.on_confirm_done())

local npairs = require'nvim-autopairs'
local Rule   = require'nvim-autopairs.rule'

npairs.add_rules {
  Rule(' ', ' ')
    :with_pair(function (opts)
      local pair = opts.line:sub(opts.col - 1, opts.col)
      return vim.tbl_contains({ '()', '[]', '{}' }, pair)
    end),
  Rule('( ', ' )')
      :with_pair(function() return false end)
      :with_move(function(opts)
          return opts.prev_char:match('.%)') ~= nil
      end)
      :use_key(')'),
  Rule('{ ', ' }')
      :with_pair(function() return false end)
      :with_move(function(opts)
          return opts.prev_char:match('.%}') ~= nil
      end)
      :use_key('}'),
  Rule('[ ', ' ]')
      :with_pair(function() return false end)
      :with_move(function(opts)
          return opts.prev_char:match('.%]') ~= nil
      end)
      :use_key(']')
}
```

Any advice would be greatly appreciated! :)
