### ISSUE TITLE
Don't add () when autocompleting import of functions

### ISSUE THREAD

**Issue by bellini666** [windwp/nvim-autopairs#206]
I have nvim-cmp configured with the `confirm_done` event as described in the README.

When trying to autocomplete a function, it does the right thing and transforms, for example, `cas|` to `cast(|)`. Now, when trying to import that function I don't want `from typing import cas|` to be expanded to `from typing import cast()`

Maybe there's a way to configure autopairs to avoid that, but I didn't find exactly how. Also, this probably happens for other languages as well, but python is one that I know for sure that happens always.

**Comment by smartinellimarco** [comment]
I'm still experiencing this issue.
Already tried modifying the handler shown in "cmp" section of the Wiki, in order to check if the current node parent is of type "from_import_statement" without success.
Is there any workaround?

**Comment by ShIRannx** [comment]
@smartinellimarco 

The code from #212 has been relocated to lua/nvim-autopairs/completion/handlers.lua and substituted with the line: `item.data and type(item.data) == 'table' and item.data.funcParensDisabled.`

I attempted to integrate the code from #212, and the issue was resolved.

**Comment by smartinellimarco** [comment]
> @smartinellimarco
> 
> The code from #212 has been relocated to lua/nvim-autopairs/completion/handlers.lua and substituted with the line: `item.data and type(item.data) == 'table' and item.data.funcParensDisabled.`
> 
> I attempted to integrate the code from #212, and the issue was resolved.

Sorry, I don't understand what that means. Do you have by chance, an example snippet to solve this issue?

**Comment by ShIRannx** [comment]
@smartinellimarco 
```    
local cmp_autopairs = require("nvim-autopairs.completion.cmp")
    local python_handler = cmp_autopairs.filetypes["python"]["("].handler
    cmp_autopairs.filetypes["python"]["("].handler = function(char, item, bufnr, rules, commit_character)
        local utils = require('nvim-autopairs.utils')
        local line = utils.text_get_current_line(bufnr)
        if line:match("^(from.*import.*)$") then
            return
        end
        python_handler(char, item, bufnr, rules, commit_character)
    end
```
I suppose it's not the best practice, but it's works.
