### ISSUE TITLE
feat: toggle to deactivate+activate bracket creation

### ISSUE THREAD

**Issue by matu3ba** [windwp/nvim-autopairs#21]
Hey, nice plugin so far.

```lua
'b3nj5m1n/kommentary'
-- insert I
-- insert {
{}'b3nj5m1n/kommentary'
-- Thats bad, I wanted to set the bracket after I am done with configuring the plugin options
```

Can you make a toggle to deactivate the behavior?
Or how do you work with this plugin?
Being forced to delete the bracket is very unfortunate for usability.

**Comment by windwp** [comment]
https://github.com/windwp/nvim-autopairs#dont-add-pairs-if-the-next-char-is-alphanumeric

you can add ' or "  to apply that. I am not testing this maybe it will break a pairs with quote
