### ISSUE TITLE
Can I disable key mappings for <CR> ?

### ISSUE THREAD

**Issue by linrongbin16** [windwp/nvim-autopairs#214]
I'm using coc-snippets with coc.nvim, it needs `imap <CR>`, so I want to disable nvim-autopairs key mappings for `<CR>`

**Comment by MrZLeo** [comment]
why this close? So do you know the solution? I am coc.nvim user as well. I use <CR> to confirm a completion, so it's important  to me to disable this remap.

**Comment by cscherrNT** [comment]
This is a duplicate. See  #252
