### ISSUE TITLE
Do add closing parenthesis `)`, `}` if there's a an open matching parenthesis in the same line

### ISSUE THREAD

**Issue by Bekaboo** [windwp/nvim-autopairs#215]
First thanks for this amazing plugin, I've used it for several weeks and it works near perfectly.
I use `<M-l>` to move my cursor right in insert mode, so I do not need to type a closing bracket to escape the pair, but I frequently find that when I type a closing parenthesis/bracket (`)`, `]`, `}`) to pair an open one in the same line, the plugin brings my cursor forward instead of instantly insert what I've typed:

```
Before        Input         After
------------------------------------
((  |)         )            ((  )|
```
Then I have to type `)` again to close the pair:
```
Before        Input         After
------------------------------------
((  )|         )            ((  ))
```
This is not that pleasant when you have:
```
Before                    Input                 After              ...
------------------------------------------------------------------------
{{{{{{  |}}}}}             }                {{{{{{  }|}}}}         ...
```

Currently `enable_check_bracket_line` only applies to open parenthesis like `(`, is it possible to let it work with closing  parenthesis (that is, insert the closing parenthesis/bracket instead of moving the cursor forward)?

**Additional context**
P.S. This feature is a bit like vscode's `Auto Closing Overtype` option:
![image](https://user-images.githubusercontent.com/76579810/156038746-1051b45e-c125-4221-92ce-d80fb31d3967.png)
By default vscode has the same behavior as this plugin, but vscode allows you to turn it off.

**Comment by windwp** [comment]
this commit above will try to not move right when have an open bracket on same line.

if you want that option like vscode you can use  function `get_rule()` and add condtion `with_move(cond.none())` 
or set enable_moveright=false( it will disable move right on quote too )
