### ISSUE TITLE
Don't complete on import

### ISSUE THREAD

**Issue by Davincible** [windwp/nvim-autopairs#219]
I'm trying to create a rule where it does not complete on import, specifically for javascript.

How can I do this?

I tried the following, but it does not seem to work:
```lua
        Rule("$$", "$$"):with_pair(ts_conds.is_not_ts_node({"import_statement", "import_specifier"}))
        Rule("$", "$"):with_pair(ts_conds.is_not_ts_node({"import_statement", "import_specifier"}))

        ts_config = {
            lua = {"string"},
            -- it will not add pair on that treesitter node
            javascript = {"template_string", "import_statement", "import_specifier"},
            -- don't check treesitter on java
            java = false
        }

```

**Comment by windwp** [comment]
how do you get that node name "import_statement" ?
if you want to disable insert autopair inside a string after autopair then that node name is string not import_statement.

that condition only check current node if you want to check a 'string' node inside 'import' node you need to write a new condition

**Comment by windwp** [comment]
you need write a custom condition

**Comment by Davincible** [comment]
How would I do that?

**Comment by windwp** [comment]
https://github.com/windwp/nvim-autopairs/blob/master/lua/nvim-autopairs/ts-conds.lua#L79
that condition is check type on current node you need loop and jump to parent node and  check type too.

**Comment by aspeddro** [comment]
@Davincible you can share a example?

**Comment by ahhshm** [comment]
I have the same problem. Did anyone find a solution?

**Comment by Davincible** [comment]
Nope

**Comment by ahhshm** [comment]
@Davincible This works for me:
```lua
  local ts_utils = prequire("nvim-treesitter.ts_utils")

  cmp.event:on("confirm_done", function(evt)
    local name = ts_utils.get_node_at_cursor():type()
    if name ~= "named_imports" then
      cmp_autopairs.on_confirm_done()(evt)
    end
  end)

```

**Comment by Davincible** [comment]
Oeh neat. I'll try that out, thanks

**Comment by Drew-Daniels** [comment]
Almost 2 years later and this worked perfectly for me. Thanks @amirhhashemi

**Comment by ZeyadMoustafaKamal** [comment]
Any suggestions for how to do this for python ? specifically pyright.
