### ISSUE TITLE
npairs.autopairs_cr() has no effect

### ISSUE THREAD

**Issue by tim-hilt** [windwp/nvim-autopairs#221]
### Description

I tried to manually call the action that nvim-autopairs calls when pressing `<CR>`, which is `npairs.autopairs_cr()` as far as I understand it. You can take a look at how I'm calling the function [here](https://github.com/tim-hilt/nvim/blob/main/ftplugin/markdown.lua#L215).

I use the default config, so this shouldn't be the problem. I'm pretty sure, that I either have a wrong understanding of what to call there or I forgot to set up something specific to make that work. I think this should be easy to answer.

### Mapping <cr> bug

1.If you report a bug about indent. Please remember that plugin doesn't do anything about indent.
  It just trigger the indent of your vim config so if you have wrong indent config then it will do wrong indent.
  You can check by select a block of code and press `==`
2. provide result of command `:verbose imap <cr>`.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]url
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'windwp/nvim-autopairs',
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('nvim-autopairs').setup()
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing nvim-autopairs and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by windwp** [comment]
it use mapping on expr mode.
so if you want to do that you need get a result of autopairs_cr() then you nvim_feedkey to excute that

**Comment by tim-hilt** [comment]
So something like this?

``` lua
local key = require("nvim-autopairs").autopairs_cr()
vim.api.nvim_feedkeys(key, "m", true)
```

This doesn't work though. You can take a look at what I'm doing and how I'm calling `autopairs_cr()` [here](https://github.com/tim-hilt/nvim/blob/main/ftplugin/markdown.lua#L215).

**Comment by windwp** [comment]
vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes(key, true, true, true), "i", true)

you need convert special character and use mode "i"

**Comment by tim-hilt** [comment]
ok thanks. Now I understand a bit more how it works. I have the following now:

``` lua
    local npairs = require("nvim-autopairs")
    local key = npairs.autopairs_cr()
    print(key)
    local key_no_termcodes = vim.api.nvim_replace_termcodes(key, true, true, true)
    print(key_no_termcodes)
    -- vim.api.nvim_feedkeys(key, "i", true)
```

I do get printouts, when running it like this. The printouts look like this:

```
^M                                                                                                                              
^M (outside pair)
^Gu^M^CO                                                                                                                        
^Gu^M^CO (inside brace-pair)
```

However, when I comment in the last line, nvim is frozen and unresponsive. Did I trigger an infinite loop or a recursion or something?

**Comment by windwp** [comment]
the mode should be "ni" :cry:

**Comment by tim-hilt** [comment]
Yesssss!!! That’s what finally made it work. Thanks for your patience and your help!
