### ISSUE TITLE
< > feature

### ISSUE THREAD

**Issue by bryant-the-coder** [windwp/nvim-autopairs#227]
**Is your feature request related to a problem? Please describe.**
You know there are some language like C++ requires `< >` right? 

**Describe the solution you'd like**
It is the same as the parenthesis function

**Describe alternatives you've considered**
I tried adding this but it didnt work. EDIT: this is for adding space
```
	Rule("", " >")
		:with_pair(cond.none())
		:with_move(function(opts)
			return opts.char == ">"
		end)
		:with_cr(cond.none())
		:with_del(cond.none())
		:use_key(">"),
```

**Additional context**
If there is any code that can do this favor, I'd be happy =)

**Comment by windwp** [comment]
can you provide a input and output

**Comment by davawen** [comment]
That would make working with templates a lot harder:
```
before           input      after
-------------------------------
std::vector|    <           std::vector<<|>>
```

**Comment by bryant-the-coder** [comment]
ye i knew that after some tries. so i gave this idea up xD
