### ISSUE TITLE
Autopairs doesnot work after I update Neovim to version 0.7.0

### ISSUE THREAD

**Issue by z4yw0o** [windwp/nvim-autopairs#235]
### Description

I cannot get autopairs working after updating Neovim to version 0.7.0.
No error messages. It just doesn't work.

### Minimal config

```Lua
-- Setup function
require("nvim-autopairs").setup() -- very very simple
```

**Comment by prncss-xyz** [comment]
Experimenting a similar situation, I might detail a little more. In my case, with neovim 0.7, fastwrap works properly and autopairs works  for [], {} and ``, but do not work for "", '' and (). The `imap`command confirm there is proper mappings for all pairs, and no rules have been set in my configuration. When I roll back to neovim 0.6 with the same configuration, autopairs works perfectly fine again.

**Comment by rockorager** [comment]
I have the same issue, but I do have some pairing working (just single quotes and square brackets)

However, if I launch neovim in any vterm (tmux, composer in aerc), all of the pairing works like normal.

**Comment by prncss-xyz** [comment]
For me, it's happening with foot terminal, but not kitty. Probably a neovim issue with fixterm encoding and not an issue of nvim-neopairs. (I have also tried another pair plugin and had the same issue).

https://gpanders.com/blog/whats-new-in-neovim-0-7/

**Comment by z4yw0o** [comment]
> For me, it's happening with foot terminal, but not kitty. Probably a neovim issue with fixterm encoding and not an issue of nvim-neopairs. (I have also tried another pair plugin and had the same issue).
> 
> https://gpanders.com/blog/whats-new-in-neovim-0-7/

 Thank you for your nice answer. I temporarily switch to alacritty now and it's working.

**Comment by z4yw0o** [comment]
This is problem of fixterm encoding on foot terminal. Not nvim-autopairs.

**Comment by dnkl** [comment]
This should be fixed on latest master of foot.

**Comment by prncss-xyz** [comment]
By the way, so much appreciation for everybody's word (foot termial, autopairs and neovim). Thank you so much for those great tools!
