### ISSUE TITLE
How to get the new line behaviour with round brackets?

### ISSUE THREAD

**Issue by EthicalCoder99** [windwp/nvim-autopairs#24]
```
before    on     after
 (|)     <CR>    (
                     |
                 )
```
how can I get this behavior? With curly and square brackets I have this behavior. I don't have any completion enable.

**Comment by windwp** [comment]
Do you setup a mapping to  that function `npairs.check_break_line_char()` ?
If you already do that and a new line is working with another bracket. I think you have a problem with indent setting .

**Comment by EthicalCoder99** [comment]
```
vim.cmd[[packadd nvim-autopairs]]
local npairs = require('nvim-autopairs')
local remap = vim.api.nvim_set_keymap

npairs.setup{
  break_line_filetype = nil, -- enable this rule for all filetypes
  pairs_map = {
    ["'"] = "'",
    ['"'] = '"',
    ['('] = ')',
    ['['] = ']',
    ['{'] = '}',
    ['`'] = '`',
  },
  disable_filetype = { "TelescopePrompt" },
  html_break_line_filetype = {
    'html' , 'vue' , 'typescriptreact' , 'svelte' , 'javascriptreact'
  },
  -- ignore alphanumeric, operators, quote, curly brace, and square bracket
  ignored_next_char = "[%w%.%+%-%=%/%,\"'{%[]"
}
```

I've these settings enabled.

**Comment by windwp** [comment]
what filetype are you testing ? 
is that file work with { or [ brackets?

**Comment by EthicalCoder99** [comment]
I have tested on .txt, .cpp, .java
{ and [ works in all these files.
Is there any way shiftwidth, tabstop, softtabstop messing things.
I have set them to 4.
```
With { and [ , I'm getting this behaviour 
{
    |
}

[
    |
]

But with ( I get this
(
 |
 )
```

**Comment by windwp** [comment]
a`cr` mapping depend on indent setting of vim .

you can try to remove some part of your config.

 I already test it on an empty vimrc with round bracket.

**Comment by EthicalCoder99** [comment]
I am using a nightly build of nvim. I'm using init.lua. I am using packer for package management and I have only one plugin i.e autopairs. Can you confirm the issue on the nightly nvim?

**Comment by windwp** [comment]
I use neovim build from master too and I can confirm It work same with any neovim version

the method is very very simple it with automatic add key **O** after you press <CR>  
https://github.com/windwp/nvim-autopairs/blob/master/lua/nvim-autopairs.lua#L213-L216
the key O use indent of vim to get correct cursor.

```
(
 |
  )
or in some filetype you have this
{
 |
  }
```
you  get this because the indent newline of filetype do it. Plugin only add newline with key `O` . that it.

If you want to fix your indent try to download language pack of vim for your filetype or if you use treesitter use treesitter indent.

**Comment by EthicalCoder99** [comment]
Thank You for replying. I will start messing around with the tree-sitter now.
