### ISSUE TITLE
Replace string.gsub with  [=[...]=]

### ISSUE THREAD

**Issue by alohaia** [windwp/nvim-autopairs#245]
https://github.com/windwp/nvim-autopairs/blob/aea913109d30c87df329ec9b8fea9aed6ef9f52a/README.md?plain=1#L18

https://github.com/windwp/nvim-autopairs/blob/aea913109d30c87df329ec9b8fea9aed6ef9f52a/README.md?plain=1#L304

I believe it's okay to use `[=[...]=]`, the users are familiar enough with Lua grammar, or you can add this link https://www.lua.org/manual/5.0/manual.html#2.1.

```lua
local ignored_next_char = [=[[%w%%%'%[%"%.]]=]
```

**Comment by windwp** [comment]
thank PR is welcome :smile:
