### ISSUE TITLE
Make fast wrap befor punctuation

### ISSUE THREAD

**Issue by fgheng** [windwp/nvim-autopairs#247]
**Is your feature request related to a problem? Please describe.**
Hello, I am always frustrated when I use fast wrap, the example is as below:
input: `|hello, how are you;`
`|` is where the cursor at, and now I input `"` at `|` then input <M-e> to fast wrap
output: `'helloq howwareeyou$`
if I input $, the result will be
`'hello, how are you;'`
buf what I want is
`'hello, how are you';`

**Describe the solution you'd like**
put wrap before punctuation.

**Describe alternatives you've considered**
I have added `%;` to `fast_wrap.pattern`, but it can not help

**Additional context**

**Comment by PCJPablo** [comment]
I am facing a similar issue with fast wrap, when making json objects I sometimes forget to wrap the properties in quotes so I wanna use fast wrap to fix it but I wants to add the quotes after the colon not before

**Comment by FT-Labs** [comment]
I need this too, please give us this feature!

**Comment by williamhCode** [comment]
I need this too 🥺

**Comment by davawen** [comment]
This should be fixed, issue can be closed :)
