### ISSUE TITLE
The filetype exception doesn't work as I expect, it still creates mapping.

### ISSUE THREAD

**Issue by name-snrl** [windwp/nvim-autopairs#263]
### Description

I recently added a custom rule that adds spaces between parentheses. I also have mapping in markdown ftplugin for \<Space\>, but it does not work even if I add '-markdown' to my rule. Because autopairs still add mapping

![screen_06_08](https://user-images.githubusercontent.com/72071763/183260561-23448097-4b75-4eb9-a44f-b9dbcc94c3c9.png)

### Steps to reproduce

- add a rule, but exclude some filetype
- add a mapping to the same button for the excluded filetype
- your mapping won't work

### Minimal config

```Lua
local np = require 'nvim-autopairs'
local rl = require 'nvim-autopairs.rule'
local cond = require'nvim-autopairs.conds'

np.setup {
  disable_in_macro = true,
  ignored_next_char = '[%w%.]',
  map_c_w = true,
  fast_wrap = {
    map = '<C-g>e',
    chars = { '{', '[', '(', '"', "'" },
    pattern = [=[[%s%'%"%)%>%]%)%}%,]]=],
    end_key = 'e',
    keys = 'fjdkslwoia;vngh',
  },
}

np.add_rules {
  rl(' ', ' ', '-markdown')
    :with_pair(function (opts)
      local pair = opts.line:sub(opts.col - 1, opts.col)
      return vim.tbl_contains({ '()', '[]', '{}' }, pair)
    end),
  rl('( ', ' )', '-markdown')
      :with_pair(function() return false end)
      :with_move(function(opts)
          return opts.prev_char:match('.%)') ~= nil
      end)
      :use_key(')'),
  rl('{ ', ' }', '-markdown')
      :with_pair(function() return false end)
      :with_move(function(opts)
          return opts.prev_char:match('.%}') ~= nil
      end)
      :use_key('}'),
  rl('[ ', ' ]', '-markdown')
      :with_pair(function() return false end)
      :with_move(function(opts)
          return opts.prev_char:match('.%]') ~= nil
      end)
      :use_key(']')
}
```

**Comment by windwp** [comment]
are you clear default rule?

**Comment by name-snrl** [comment]
> is this rule still working? it creates a mapping but the rule is not working on another file type.

No, no, in my case the rule doesn't work in markdown. The problem is that my mapping for markdown doesn't work. It would be great if the rule did not create a mapping for excluded filetypes. Or maybe recursive mapping could solve this problem.

Now instead of excluding filetypes, I've added a filetypes where the rule should work, and it works as I expected, creating a mapping only for those filetypes.

**Comment by cvuuhk** [comment]
Same problem, and here are my config:
```lua
    local npairs = require('nvim-autopairs')
    local Rule = require('nvim-autopairs.rule')
    local cond = require('nvim-autopairs.conds')
    local cmp_autopairs = require("nvim-autopairs.completion.cmp")
    local cmp = require("cmp")

    npairs.setup {
        disable_in_macro = true,
        disable_in_visualblock = true,
    }

    npairs.add_rule(Rule("`", "`", "markdown"):with_pair(cond.none()))

    cmp.event:on("confirm_done", cmp_autopairs.on_confirm_done({map_char = {tex = ""}}))
```

When I edit markdown files, it behaves like this:

https://user-images.githubusercontent.com/36870468/184499385-1efa54d4-6a2a-401b-9943-7bcc73c29cca.mp4

**Comment by name-snrl** [comment]
@cvuuhk 
> Same problem

I don't think so. My problem is that my markdown mapping(<C-g>u<Space>) doesn't work even if I exclude markdown in the rule. Because the rule keeps creating mapping for the excluded filetype.
