### ISSUE TITLE
unable to map `autopairs_cr()` using full lua code

### ISSUE THREAD

**Issue by carlosala** [windwp/nvim-autopairs#266]
I want to map `<M-CR>` to `autopairs_cr()` with lua config, but I am unable to do so actually using full lua code. My actual vimscript config works properly:
```vim
inoremap <expr> <M-CR> v:lua.Npairs.autopairs_cr()
```
and this one is equivalent and works:
```lua
map("i", "<M-CR>", "v:lua.Npairs.autopairs_cr()", { expr = true, noremap = true })
```
Is there any option to just call the lua function without going inside vim script, and having to do `v:lua`?
Thanks!

**Comment by windwp** [comment]
i think it should be MPairs not Npairs

**Comment by carlosala** [comment]
I exported the variable as Npairs
```lua
Npairs = require("nvim-autopairs")
```

**Comment by carlosala** [comment]
That option works, but I want to know if I can escape that `v:lua...`

**Comment by windwp** [comment]
https://github.com/nanotee/nvim-lua-guide you can use vim.keymap.set
