### ISSUE TITLE
Any typed text when pum is visible is deleted when typing an auto-paired character

### ISSUE THREAD

**Issue by urandom** [windwp/nvim-autopairs#27]
If a user has a typed word, and the completion menu is also opened, pressing a paired character , such as '(' or '{' will delete the user's text, including the character, and instead insert the closing character from the pair.

For example, if the user has typed `Upload|` and the pum is visible, pressing `(` would result in `)`. Instead, it should have resulted in `Upload(|)`

**Comment by windwp** [comment]
maybe it happen because another plugin.
you should use nvim-compe for auto compeletion.

**Comment by urandom** [comment]
@windwp 
This happens with the regular omni-completion, as well as nvim-compe

**Comment by windwp** [comment]
Hi can you provide minimal vim config or at least give more information 
My plugin don't have any code to delete text

**Comment by urandom** [comment]
@windwp 
I've narrowed it down to the completeopt+=longest option. With it, things break, but without it, everything seems fine.

**Comment by sirbrillig** [comment]
Thank you for figuring this out, @urandom! I had this same problem and it was very confusing.

It might be worth putting this in the FAQ, maybe? Something like "Not compatible with `longest` option in `completeopt`"?
