### ISSUE TITLE
Option to disable all default rules

### ISSUE THREAD

**Issue by WhiteBlackGoose** [windwp/nvim-autopairs#277]
Hello, and great plugin!

**Is your feature request related to a problem? Please describe.**

I only need closing parentheses, however, [from default values](https://github.com/windwp/nvim-autopairs#default-values) I don't see any opportunity to disable all default rules.

**Describe the solution you'd like**

I'd like to have option `no_rules = true` option, so that I could add the necessary rules myself.

**Describe alternatives you've considered**

Another option would be to have no rules by default, and then the user can add a recommended list, if they want. That makes the configuration much more transparent.

**Additional context**

I tried disabling auto completion of quotes but had no success. I basically want only parents and brackets, and only for a certain file type.

I also tried not writing `require("nvim-autopairs").setup {}` in the beginning, but then it doesn't start (`attempt to index field 'config' (a nil value)`)

**Comment by windwp** [comment]
https://github.com/windwp/nvim-autopairs#plugin-integration

it is clear_rules

**Comment by WhiteBlackGoose** [comment]
Nice, thanks!
