### ISSUE TITLE
Support for angle brackets?

### ISSUE THREAD

**Issue by MordechaiHadad** [windwp/nvim-autopairs#28]
I wonder if there is any plan to support angle brackets or `<>`

**Comment by windwp** [comment]
you can add that in config
but it will make difficult to add <= 
if you want to use it on html  to write tag you can try my plugin nvim-ts-autotag

**Comment by windwp** [comment]
check READMe you can add in pair_maps

**Comment by MordechaiHadad** [comment]
> 
> 
> check READMe you can add in pair_maps

In pair_maps I added 

'local pairs_map = {
    ['<'] = '>',
}'
and it didnt do anything

**Comment by windwp** [comment]
remove local and add that pair map text in setup funtion

**Comment by MordechaiHadad** [comment]
> 
> 
> remove local and add that pair map text in setup funtion .
> checking override default value

thank you for the clarification.
best regards.
