### ISSUE TITLE
Unable to accomplish some mappings

### ISSUE THREAD

**Issue by ignamartinoli** [windwp/nvim-autopairs#280]
Hi, I really like this plugin, but between deprecations and after doing some trial-and-error I am left a bit confused on how to set some custom mapping.

I was trying to achieve this mappings (if I achieve to make them work I will try to open a PR since they can be considered default behaviour for those filetypes)

- Disable `'` pair on **Haskell**, **Scheme**, **Clojure** and **Common Lisp**

I tried

```lua
require 'nvim-autopairs'.setup {
	pairs_map = {
		['"'] = '"',
		['('] = ')',
		['['] = ']',
		['{'] = '}',
		['`'] = '`'
	}
}

local Rule = require 'nvim-autopairs.rule'

require 'nvim-autopairs'.add_rules {
	Rule([[']], [[']], { '-clojure', '-haskell', '-lisp', '-scheme' })
}
```

but it doesn't work at all.

- Add `|` pair on **Rust**

I tried

```lua
require 'nvim-autopairs'.setup()

local Rule = require 'nvim-autopairs.rule'

require 'nvim-autopairs'.add_rules {
	rule('|', '|', 'rust')
}
```

but the result is

```
Before      Input   After
--------------------------------
|<cursor>   |       ||<cursor>||
--------------------------------
```

Also I see the option `html_break_line_filetype` around a lot of configuration files but I cannot find what it does

**Comment by windwp** [comment]
options pairs_maps and html_breakline is deprecated .
all options display on readme.md is valid.


require 'nvim-autopairs'.add_rules {
	Rule([[']], [[']], { '-clojure', '-haskell', '-lisp', '-scheme' })
}

 it is not working because it already have another rule for quote. you need remove that rule then add your new rule or use .get_rule("'"):with_pair(cond.not_filetypes(      )) to modify the existing rule

**Comment by windwp** [comment]
https://github.com/windwp/nvim-autopairs/blob/master/lua/nvim-autopairs/rules/basic.lua

you can check that to view all rules

**Comment by ignamartinoli** [comment]
```lua
require('nvim-autopairs').get_rule([[']]):with_pair(require 'nvim-autopairs.conds'.not_filetypes({ 'clojure' }))
```

returns the error

```lua
packer.nvim: Error running config for nvim-autopairs: [string "..."]:0: attempt to call method 'with_pair' (a nil value)
```
