### ISSUE TITLE
Remove existing rules for specific filetypes?

### ISSUE THREAD

**Issue by glyh** [windwp/nvim-autopairs#281]
**Is your feature request related to a problem? Please describe.**

For example, I'd like to remove `'` pairing entirely for Lisps without removing its default behavior for rust lifetimes.

**Describe the solution you'd like**
Add some APIs to exclude filetypes for existing rules.

**Comment by glyh** [comment]
BTW I know I could remove the rule entirely and insert my own rule. But if I choose to do that I need to manually update my rules whenever the rules in this repo is updated.

**Comment by sindrets** [comment]
This worked for me:

```lua
require("nvim-autopairs").get_rule("'")[1].not_filetypes = { "scheme", "lisp" }
```

**Comment by sumanchapai** [comment]
I am having the issue where this isn't working for me when I put this at the end of my nvim lazy config for the plugin.

> This worked for me:
> 
> ```lua
> require("nvim-autopairs").get_rule("'")[1].not_filetypes = { "scheme", "lisp" }
> ```

For example when my `autopairs.lua` is as follows (see the customization around the end):
```autopairs.lua
return {
  "windwp/nvim-autopairs",
  event = { "InsertEnter" },
  dependencies = {
    "hrsh7th/nvim-cmp",
  },
  config = function()
    -- import nvim-autopairs
    local autopairs = require("nvim-autopairs")

    -- configure autopairs
    autopairs.setup({
      check_ts = true, -- enable treesitter
      ts_config = {
        lua = { "string" }, -- don't add pairs in lua string treesitter nodes
        javascript = { "template_string" }, -- don't add pairs in javscript template_string treesitter nodes
        java = false, -- don't check treesitter on java
      },
    })

    -- import nvim-autopairs completion functionality
    local cmp_autopairs = require("nvim-autopairs.completion.cmp")

    -- import nvim-cmp plugin (completions plugin)
    local cmp = require("cmp")

    -- make autopairs and completion work together
    cmp.event:on("confirm_done", cmp_autopairs.on_confirm_done())

    --- SEE HERE ---
    autopairs.get_rules("'")[1].not_filetypes = { "scheme", "lisp", "ocaml", "ml" }
  end,
}
```
it doesn't work, meaning the autopair rule for `'` doesn't get removed when working  `.ml` files. However, when i add it to `init.lua` file it works:

```init.lua
local autopairs = require("nvim-autopairs")
autopairs.get_rules("'")[1].not_filetypes = { "scheme", "lisp", "ocaml", "ml" }
```
I spent some time debugging this, for example placing the customization in autocommand, or deferred function, but doesn't work. Any suggestions would be appreciated.

**Comment by dragove** [comment]
@sumanchapai try following
```lua
autopairs.get_rules("'")[1]:with_pair(cond.not_filetypes({ "scheme", "lisp", "ocaml", "ml" }))
```
