### ISSUE TITLE
Can not take effect after installed 

### ISSUE THREAD

**Issue by jinfagang** [windwp/nvim-autopairs#284]
### Description

I have installed nvim-autopairs.

But  can not make it effect (append auto after " ` or { [ 

How to resolve it?

### Mapping <cr> bug

1.If you report a bug about indent. Please remember that plugin doesn't do anything about indent.
  It just trigger the indent of your vim config so if you have wrong indent config then it will do wrong indent.
  You can check by select a block of code and press `==`
2. provide result of command `:verbose imap <cr>`.

### Steps to reproduce

this is my simple config:

```
local ensure_packer = function()
    local fn = vim.fn
    local install_path = fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'
    if fn.empty(fn.glob(install_path)) > 0 then
      fn.system({'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path})
      vim.cmd [[packadd packer.nvim]]
      return true
    end
    return false
  end
  
local packer_bootstrap = ensure_packer()

return require('packer').startup(function()
    use 'wbthomason/packer.nvim'

    use 'glepnir/zephyr-nvim'
    use("folke/tokyonight.nvim")
    use 'bluz71/vim-moonfly-colors'

    -- nvim-tree (新增)
    use {
        'kyazdani42/nvim-tree.lua',
        requires = 'kyazdani42/nvim-web-devicons'
    }
    
    use { "beauwilliams/focus.nvim", config = function() require("focus").setup() end }
    
    -- for this completion
    use "ms-jpq/coq_nvim"
    use "ms-jpq/coq.artifacts"

    -- auto pairs
    use {
      "windwp/nvim-autopairs",
      config = function() require("nvim-autopairs").setup {} end
    }

end)

```

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'windwp/nvim-autopairs',
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('nvim-autopairs').setup()
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing nvim-autopairs and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by windwp** [comment]
it should work on nvim 0.7

**Comment by jinfagang** [comment]
@windwp hello, my nvim is just `0.7`. Does there need any further configuration after required in packer?

**Comment by bthooper** [comment]
I just wanted to note that I am also having this issue.  I have a very minimal set up as I am configuring neovim from scratch.  I'm not sure why, but it just doesn't seem to work. I'm using 0.7.2 of neovim.

**Comment by jinfagang** [comment]
Strangely after I restart terminal or something else setup, it now seems can autopair my [ or { etc. not sure if it was autopairs's functionality or others. I also have COQ installed.

**Comment by windwp** [comment]
@bthooper you can check by running `verbose imap [` or running `:lua require("nvim-autopairs).setup()` on command and test again.
maybe it have some problem with your config.

**Comment by bthooper** [comment]
@windwp  Thanks. When I run the command from the nvim command line, it works....so something must be wrong with my config.....even though I thought it was simple :)

**Comment by bthooper** [comment]
so strange to me. I have this line in my init file:
`use { "windwp/nvim-autopairs",  config = function() require("nvim-autopairs").setup()  end }`

Is it clear what could be wrong? When I run that require command it works, but it isn't running it when I start nvim.

**Comment by tecbeast42** [comment]
I had the same problem too. Restarting the terminal, not just closing and opening neovim solved it.

**Comment by jougene** [comment]
I have the same problem, neovim version: `NVIM v0.9.1`

**Comment by Boltzmachine** [comment]
Same problem here

**Comment by EnricoSteez** [comment]
NVIM 0.9.1, I couldn't get it to work either, so I tried doing `require("nvim-autopairs").setup {}` ouside of the Packer `use` directive and it activates it correctly.

**Comment by papierkorp** [comment]
Had the same problem, forgot to use `opts = {} -- this is equalent to setup({}) function` in my lazy Installation.

**Comment by AndrejPatak** [comment]
Can someone who made it work provide their whole init.vim? I did everything right in theory, but it is still not working
