### ISSUE TITLE
Race condition with the `<CR>` mapping

### ISSUE THREAD

**Issue by bnjbvr** [windwp/nvim-autopairs#287]
### Description

First of all, thanks for this great plugin!

I've enabled the `<cr>` mapping. Here's in fact my entire setup for this plugin:

```lua
require('nvim-autopairs').setup({
    map_cr = true
})
```

I've noticed that if I'm into e.g. a Rust source file, and if I type `fn lol() {|}` then `<CR>`:

- if I pressed `<CR>` quickly after typing the `{`, then I get this: (not the expected result)
```
fn lol() {
|}
```
- if I wait half a second before pressing `<CR>`, then I get the expected result:
```
fn lol() {
    |
}
```

Does this ring a bell? Is that a bug?

### Mapping <cr> bug

1. Indent is correct, I'm using treesitter on this installation.
2. `:verbose imap <cr>` returns `<CR>        * v:lua.MPairs.completion_confirm()`                                                                                                

### Steps to reproduce

https://user-images.githubusercontent.com/1180019/194433937-9bcc8070-cbcb-4001-9d5c-66c660de4ad9.mp4

### Minimal config

```Lua
local ensure_packer = function()
  local fn = vim.fn
  local install_path = fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'
  if fn.empty(fn.glob(install_path)) > 0 then
    fn.system({'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path})
    vim.cmd [[packadd packer.nvim]]
    return true
  end
  return false
end

local packer_bootstrap = ensure_packer()

require('packer').startup(function(use)
    use 'wbthomason/packer.nvim'
    use {
        'nvim-treesitter/nvim-treesitter',
        run = ':TSUpdate'
    }
    use "windwp/nvim-autopairs"
    if packer_bootstrap then
        require('packer').sync()
    end
end)

require'nvim-treesitter.configs'.setup {
  sync_install = false,
  auto_install = true,
  indent = {
    enable = true,
  },
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },
}

require('nvim-autopairs').setup({
    map_cr = true
})
```

**Comment by windwp** [comment]
can you run `verbose imap <cr>`

**Comment by bnjbvr** [comment]
Sure:

:verbose imap <cr> returns <CR> * v:lua.MPairs.completion_confirm()

**Comment by windwp** [comment]
are you use any auto completion plugin nvim-cmp or coc.nvim?
I can't reproduce with that  minimal config above even i type it really fast

**Comment by bnjbvr** [comment]
No, I managed to reproduce this with the minimal config above, having disabled every other plugin and all. 

For what it's worth, my neovim version is:

```
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
```

**Comment by blinky39** [comment]
same issue, same version and feature of nvim, same :verbose imap <CR> output

**Comment by blinky39** [comment]
I found  LunarWatcher/auto-pairs works @bnjbvr

**Comment by asmodeus812** [comment]
Same issue, but i am noticing that it breaks telescope select_default action for me, same behaviour, sometimes it maps <CR> to the telescope sometimes i get the v:lus.MPairs.completion_confirm() instead when i look at imap when i have the telescope prompt open.

**Comment by bnjbvr** [comment]
Fwiw, I'm still affected by this bug.

**Comment by duarm** [comment]
What I noticed is that this happens because you're typing ''{", which is inputted by pressing SHIFT+[, you're typing too fast and end up typing <S-[><S-CR> instead of just <S-[><CR>.

```
{|} 
<CR> produces 

{
   |
}

{|}
<S-CR> produces:

{
|}
```
whatever the speed you type, try reproducing with just brackets [ ], instead of parenthesis

**Comment by bnjbvr** [comment]
Wow, great find, you're absolutely right, thanks sir :bow: 

I've snooped in the code and could reproduce a mapping for `<S-CR>`, putting it here in case it helps others:

```
-- Map shift+enter to autopairs too.
vim.api.nvim_set_keymap(
    'i',
    '<S-CR>',
    'v:lua.MPairs.completion_confirm()',
    { expr = true, noremap = true }
)
```
