### ISSUE TITLE
Corrupted undo file when typing quote in inccommand preview callback

### ISSUE THREAD

**Issue by smjonas** [windwp/nvim-autopairs#288]
### Description

Initially reported here: https://github.com/smjonas/live-command.nvim/issues/16. This is essentially the same issue as https://github.com/neovim/neovim/issues/20248. I just modified the `Test` command in the minimal init below.

### Steps to reproduce

1. Type the `:Test` command defined below.
2. Observe how ` = '' = 'hey'` is inserted into the buffer.

## Suggestion
Could there maybe be an option which will disable the undo functionality in command line mode until the Neovim issue is fixed?

### Minimal config

```Lua
local function command_preview(_, _, _)
  vim.cmd("norm A'hey")
  return 0
end

vim.api.nvim_create_user_command("Test", function() end, { preview = command_preview, nargs = 0 })

vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'windwp/nvim-autopairs',
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('nvim-autopairs').setup()
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing nvim-autopairs and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by smjonas** [comment]
A workaround is to use 
```lua
require("nvim-autopairs").setup {
  break_undo = false,
}
```
but I think it would be nicer to disnable undo in commandline mode only.

**Comment by windwp** [comment]
what is the flag to check incommand is running

**Comment by smjonas** [comment]
I don't think there is way to check that without manually setting a global variable in the callback.

**Comment by smjonas** [comment]
Do you have any other idea how this can be fixed? I can set a global variable like `vim.g.cmd_preview = true` in the preview callback which you could use in `nvim-autopairs`.

**Comment by windwp** [comment]
maybe you can try to call disable and enable function
require('nvim-autopairs').disable()
 require('nvim-autopairs').enable()
