### ISSUE TITLE
How to disable in REPLACE mode?

### ISSUE THREAD

**Issue by sbeyer** [windwp/nvim-autopairs#289]
**Is your feature request related to a problem? Please describe.**
autopairs in REPLACE mode overwrites the next character. For example (real example), the text says `" #"`, I position the cursor on `#` go in REPLACE mode and press `[`, then the following `"` is replaced by `]`, leaving me with `" []` instead of `" ["`

**Describe the solution you'd like**
In REPLACE mode, autopairs should do nothing. At least there should be a config option to disable autopairs in REPLACE mode. (But: are there even use-cases for autopairs in REPLACE mode?)

Alternatively and even better: it should work in REPLACE mode as it works when actually replacing a pair in INSERT mode (which is really cool!), and do nothing when not replacing a pair.

**Describe alternatives you've considered**
Either, or:
* Replace the overwritten character by its original character again, however, it largely disturbs the workflow, especially when I have to undo first to see what the original character was.
* Remove nvim-autopairs

**Additional context**
Nope.

**Comment by windwp** [comment]
close 6b6e35fc9aca1030a74cc022220bc22ea6c5daf4
