### ISSUE TITLE
Disabling nvim-autopairs for single quote in Clojure not working

### ISSUE THREAD

**Issue by okeefe77** [windwp/nvim-autopairs#290]
### Description

I'm coding Clojure in nvim and would like to disable autopairing for single quote characters.  The docs indicate this is possible, but the indicated way isn't working.  Can anyone shed some light on what I might be doing wrong?  The extension is loaded via Packer and I have the following in my `init.lua` as the setup code for autopairs:

```lua
require('nvim-autopairs').setup({
    disable_filetype = { 'TelescopePrompt' }
})

local Rule = require('nvim-autopairs.rule')
local npairs = require('nvim-autopairs')

npairs.add_rule(Rule("'","'","-clojure"))
```

**Comment by windwp** [comment]
https://github.com/windwp/nvim-autopairs#plugin-integration

it need get the rule then modify it

**Comment by okeefe77** [comment]
That did the trick.  Thanks!  Apologies for not RTFM.  I wouldn't have thought to look for the solution under that heading, but next time I'll read more carefully.  Thanks again!
