### ISSUE TITLE
Error when hitting enter in a vim buffer

### ISSUE THREAD

**Issue by AlexRipoll** [windwp/nvim-autopairs#297]
### Description

Once installed `nvim-autopairs` (I used paccker), when openning a vim buffer and hitting enter the foloowing error appears:
![image](https://user-images.githubusercontent.com/26032012/205269872-b6ac0a0e-fc28-4c54-b374-caf612ed79d8.png)

I am using Nvim 0.8.0.

### Steps to reproduce

1. Install windwp/nvim-autopairs using packer
2. Create a file autopairs.lua with minimal config.
3. Require autopairs.lua in main init.lua file
4. Save and relaod Nvim (v0.8.0)
5. Open any buffer, enter Insert mode and hit enter <CR> key

### Minimal config

```Lua
-- import nvim-autopairs safely
local autopairs_setup, autopairs = pcall(require, "nvim-autopairs")
if not autopairs_setup then
  return
end

-- configure autopairs
autopairs.setup({
    ignored_next_char = "[%w%.]" -- will ignore alphanumeric and `.` symbol
})
```

**Comment by windwp** [comment]
the error log message occur on nvim-cmp . you should  reading that message

**Comment by AlexRipoll** [comment]
I've noticed that, but cmp was working fine until I added autopairs. Thanks anyway.
