### ISSUE TITLE
Does not auto-pair when cursor is surrounded by '$'

### ISSUE THREAD

**Issue by Bekaboo** [windwp/nvim-autopairs#298]
### Description

Auto-pair does not triggers when cursor is surrounded by '$'.

### Mapping <cr> bug

1.If you report a bug about indent. Please remember that plugin doesn't do anything about indent.
  It just trigger the indent of your vim config so if you have wrong indent config then it will do wrong indent.
  You can check by select a block of code and press `==`
2. provide result of command `:verbose imap <cr>`.

### Steps to reproduce

`|` represents current location of the cursor.

1.
```
$|$
```

2. Press `(`, `{`, or `[`, etc.

3. The result is like this:
```
$(|$
```

### Minimal config

```Lua
Zero config about nvim-autopairs (only called the setup function from nvim-autopairs).
```

**Comment by windwp** [comment]
local ignored_next_char = [=[[%w%%%'%[%"%.%`%$]]=]

 your need change the default value of ignored_next_char

**Comment by Bekaboo** [comment]
> local ignored_next_char = [=[[%w%%%'%[%"%.%`%$]]=]
> 
> your need change the default value of ignored_next_char

Removing `%$` from the pattern solves this issue. Thanks!
