### ISSUE TITLE
Quotes within other pairs are not properly skipped

### ISSUE THREAD

**Issue by garcia5** [windwp/nvim-autopairs#3]
When pressing any of the keys ``',`,"`` within any other pairs, a single symbol is added rather than skipping the closing symbol

For example, starting at this position where the cursor is `|`
`("|")`

Expected behavior:
`(""|)`

Actual behavior:
`(""|")`

This is with default configuration settings

**Comment by garcia5** [comment]
Thank you! I've been maintaining my own hacky autopairs for years, and this does everything I've been wanting mine to do

**Comment by YorickPeterse** [comment]
@windwp I think this is still/again a problem using the latest version. Using commit 0da518e, when I have this as input:

```
foo("|")
```

Pressing `"` results in this:

```
foo(""|")
```

instead of this:

```
foo(""|)
```

This only seems to apply so quotes (single, double or backticks), not brackets.
