### ISSUE TITLE
How to make <> behave exactly like ()

### ISSUE THREAD

**Issue by onsails** [windwp/nvim-autopairs#301]
### Description

I have default npairs setup with a single custom rule to autopair `<` with `>`. I've reused exactly the same functions which nvim-autopairs uses for `()`.

However when, given
```
<|>
```
I press `>`, I am getting:
```
<>|>
```

While given `(|)` I press `)` I am getting `()|`. How to make `<>` behave the same way?

### Mapping <cr> bug

1.If you report a bug about indent. Please remember that plugin doesn't do anything about indent.
  It just trigger the indent of your vim config so if you have wrong indent config then it will do wrong indent.
  You can check by select a block of code and press `==`
2. provide result of command `:verbose imap <cr>`.

### Minimal config

```Lua
local Rule = require('nvim-autopairs.rule');
local npairs = require('nvim-autopairs');
local cond = require('nvim-autopairs.conds')

local basic = function(...)
  local opt = require('nvim-autopairs').config

  local move_func = opt.enable_moveright and cond.move_right or cond.none
  local rule = Rule(...)
      :with_move(move_func())
      :with_pair(cond.not_add_quote_inside_quote())
  print('move_func')

  if #opt.ignored_next_char > 1 then
    rule:with_pair(cond.not_after_regex(opt.ignored_next_char))
  end
  rule:use_undo(opt.break_undo)
  return rule
end

local bracket = function(...)
  local opt = require('nvim-autopairs').config

  local rule = basic(...)
  if opt.enable_check_bracket_line == true then
    rule
        :with_pair(cond.is_bracket_line())
        :with_move(cond.is_bracket_line_move())
  end
  if opt.enable_bracket_in_quote then
    -- still add bracket if text is quote "|" and next_char have "
    rule:with_pair(cond.is_bracket_in_quote(), 1)
  end
  return rule
end

npairs.setup {
  disable_filetype = { "TelescopePrompt", "vim" },
}

npairs.add_rules({
  -- https://github.com/windwp/nvim-autopairs/blob/master/lua/nvim-autopairs/rules/basic.lua#L4
  bracket("<", ">")
})
```

**Comment by windwp** [comment]
:with_move(cond.is_bracket_line_move())

you need modify a condition for with_move. it is check the character is bracket so you can't use it with >

**Comment by onsails** [comment]
> ```
>     :with_move(cond.is_bracket_line_move())
> ```
> 
> you need modify a condition for with_move. it will check the character is bracket so you can't use it with >

But it's already there in `bracket` function (I double checked that `enable_bracket_in_quote` is true with `lua print(vim.inspect(require('nvim-autopairs').config.enable_bracket_in_quote))`).

**Comment by thecontinium** [comment]
see [here](https://github.com/windwp/nvim-autopairs/blob/b5994e6547d64f781cfca853a1aa6174d238fe0e/lua/nvim-autopairs/utils.lua#L33)

**Comment by onsails** [comment]
Thanks for the help! Now with [this PR](https://github.com/windwp/nvim-autopairs/pull/303) I've been able to fix my problem with:
```lua
local opt = require('nvim-autopairs').config

local basic = require('nvim-autopairs.rules.basic')

local utils = require('nvim-autopairs.utils')
local original_is_close_bracket = utils.is_close_bracket
function utils.is_close_bracket(char)
  return original_is_close_bracket(char) or char == '>'
end

local bracket = basic.bracket_creator(opt)

npairs.add_rules({
  bracket("<", ">")
})
```

**Comment by Jaehaks** [comment]
@onsails 

It cannot do this behavior . how to do this?

input
```lua
<|>
```

output
```lua
<
  |
>
```

**Comment by Jaehaks** [comment]
I find the solution 

```lua
  -- additional rules
  npairs.add_rules({
    Rule('<','>')
    :with_cr(cond.done())
    :replace_map_cr(function ()
      return '<C-g>u<CR><C-c>O<Tab>'
    end)
  })
```
