### ISSUE TITLE
Don't add pair if it already has a closing pair in a multi-line context

### ISSUE THREAD

**Issue by stevanmilic** [windwp/nvim-autopairs#305]
**Is your feature request related to a problem? Please describe.**
If there's a closing pair on a different line, then we don't need to add a closing pair. Example where we don't need to add a closing pair since there's a closing parenthesis:

https://user-images.githubusercontent.com/6879030/209446713-c2628708-5fad-487b-a07e-a5fd25bb0b33.mov

**Describe the solution you'd like**
To not add a closing pair if it already exists on a different line.

**Comment by bew** [comment]
Please no?

**Comment by bew** [comment]
Please no?

**Comment by bew** [comment]
@stale why close as completed?
@windwp could you re-open maybe?
