### ISSUE TITLE
How can I prevent an autopair if next character is NOT whitespace?

### ISSUE THREAD

**Issue by sdemura** [windwp/nvim-autopairs#306]
As the title says, if the character immediately following the cursor is NOT whitespace, how can I prevent a pair from being created? Thanks.

**Comment by HerCerM** [comment]
You could use the existent option `ignored_next_char` and the non-whitespace class `%S`:

```lua
require("nvim-autopairs").setup {
  ignored_next_char = "%S",
}
``` 

From <https://www.lua.org/manual/5.1/manual.html#5.4.1>:

> For all classes represented by single letters (%a, %c, etc.), the corresponding uppercase letter represents the complement of the class. For instance, %S represents all non-space characters.
