### ISSUE TITLE
how to stop pair when doing function assignment with nvim-cmp confirm

### ISSUE THREAD

**Issue by y1rn** [windwp/nvim-autopairs#308]
### Description

As title, field ```ErrorHandler```  is a function which match with function ```errorHandler```

![image](https://user-images.githubusercontent.com/70128797/209808612-c6a9a9ce-c51f-450f-8271-aa75d1b1f3dc.png)

### Minimal config

```Lua
require('nvim-autopairs').setup()

local cmp_autopairs = require('nvim-autopairs.completion.cmp')
cmp.event:on( 'confirm_done', cmp_autopairs.on_confirm_done({  
  map_char = { tex = '' },
}))
```

**Comment by aspeddro** [comment]
See https://github.com/windwp/nvim-autopairs#mapping-cr
