### ISSUE TITLE
map_space and map_bs

### ISSUE THREAD

**Issue by jguddas** [windwp/nvim-autopairs#310]
**Is your feature request related to a problem? Please describe.**
`map_cr` already exists, `map_space` would do `(|)` -> `( | )` and `map_bs` would do `( | )` -> `()` or `<a>\n  |\n<\a>` -> `<a></a>`

**Describe the solution you'd like**
create a `is_expandable` and `is_collapsable` function that are publicly exposed and can be reused.

**Solution for `map_space` is detailed in the wiki**
https://github.com/windwp/nvim-autopairs/wiki/Custom-rules#add-spaces-between-parentheses

**Comment by jguddas** [comment]
Something like `Rule(' ', ' '):useKey('<Plug>autopairs_space')` would be awesome.
I currently my custom space mapping is getting overwritten :disappointed:

**Comment by jguddas** [comment]
This code seams to work for the muliline `map_bs` case.
```lua
vim.keymap.set('i', '<c-bs>', '<bs>')
vim.api.nvim_set_keymap('i', '<Plug>autopairs_bs', 'v:lua.MPairs.autopairs_bs()', {
  expr = true,
  noremap = true,
})
vim.keymap.set('i', '<bs>', function()
  if vim.fn.foldclosed('.') > -1 then
    return '<C-o>zo'
  end

  local line = vim.fn.getline('.')
  if line == '' then
    local prev_line = vim.fn.getline(vim.fn.line('.') - 1)
    local next_line = vim.fn.getline(vim.fn.line('.') + 1)
    local trimmed_next_line = next_line:gsub('^ *', '')
    local rules = npairs.get_buf_rules()
    for _, rule in pairs(rules) do
      if rule.start_pair then
        local prev_char, next_char = utils.text_cusor_line(
          prev_line .. trimmed_next_line,
          #prev_line,
          #rule.start_pair,
          #rule.end_pair,
          rule.is_regex
        )
        if utils.compare(rule.start_pair, prev_char, rule.is_regex)
          and utils.compare(rule.end_pair, next_char, rule.is_regex)
        then
          return string.rep('<del>', #next_line - #trimmed_next_line + 1) .. '<bs>'
        end
      end
    end
  end

  return '<Plug>autopairs_bs'
end, { expr = true, silent = true, noremap = true })
```

**Comment by andrevmatos** [comment]
Yes, space would be nice! Still important to me

**Comment by jguddas** [comment]
> Yes, space would be nice! Still important to me 

https://github.com/jguddas/dotfiles/blob/02a3579256e53f4c64bccbc9d15d40ee4953f913/neovim/init.lua#L395-L397
