### ISSUE TITLE
Pressing backspace in quotes causes deletion of content in front of pair

### ISSUE THREAD

**Issue by fidelski** [windwp/nvim-autopairs#313]
### Description

When pressing backspace within a pair of empty quotes the content of the text in front of the quotes gets deleted. Instead, just the quotes should get deleted.

## Observed behavior

After pressing `<BS>` on `{cursor}`
```c++
std::cout << "{cursor}"
```

I get
```c++
std::c{cursor}"
```

## Expected behavior

After pressing `<BS>` on `{cursor}`
```c++
std::cout << "{cursor}"
```

I expect
```c++
std::cout << {cursor}
```

### Steps to reproduce

![nvim-autopairs-deletes-too-much](https://user-images.githubusercontent.com/858144/211306851-0b2a6c60-50ce-49e0-9077-73c15c59d0e8.gif)

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'windwp/nvim-autopairs',
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('nvim-autopairs').setup{check_ts=true}
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing nvim-autopairs and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by windwp** [comment]
check your mapping `imap <bs>`

**Comment by fidelski** [comment]
`<BS>` in insert mode is mapped to:

```
i  ▏<BS>                                   ▏*@▏v:lua.MPairs.autopairs_bs()
```

**Comment by windwp** [comment]
I can't reproduce

**Comment by fidelski** [comment]
It turned out that the problem was a faulty rule configuration that caused the issue:

```lua
local npairs = require ('nvim-autopairs')
npairs.setup {check_ts = true}
local Rule = require ('nvim-autopairs.rule')
npairs.add_rules {
    Rule ('[{["\']+$', ''):use_regex (true, '<cr>'):replace_endpair (function ()
        return '<cr><esc>O'
    end)
}
```

I wanted to realize what is explained in https://github.com/windwp/nvim-autopairs#you-need-to-add-mapping-cr-on-nvim-cmp-setupcheck-readmemd-on-nvim-cmp-repo - it seems I haven't read / seen this. Removing the rule fixes the problem and brings the desired behavior.

Sorry for the noise and thanks a lot for the great plugin!
