### ISSUE TITLE
Ability to disable auto fast-wrap

### ISSUE THREAD

**Issue by bew** [windwp/nvim-autopairs#317]
**Is your feature request related to a problem? Please describe.**

With this text: `foo |"str"` (with `|` being the cursor)

Doing `{` currently does:
`foo {"str"}`

But I simply want:
`foo {"str"`

**Describe the solution you'd like**

A way to disable auto-wrap like this, I want the fast wrap system only when I ask for it!

**Describe alternatives you've considered**

Manually remove the `}` but that's not really a solution...

**Comment by windwp** [comment]
it already have that option 'enable_afterquote'

**Comment by bew** [comment]
Thanks!
