### ISSUE TITLE
LaTeX

### ISSUE THREAD

**Issue by aloispichler** [windwp/nvim-autopairs#320]
### Description

What is the correct syntax to pair $ with $ and \\[ with \\] in LaTeX?
```
    before      type    result
1   let |         $     let $|$
2   let $x=4|     $     let $x=4$|
3   let $x=4|$    $     let $x=4$|

4   let \|        [     let \[|\]
5   let \[x=4|    \]    let \[x=4\]|
6   let \[x=4|\]  \]    let \[x=4\]|

```
??
Thanks.

**Comment by FrancoRav** [comment]
Check the [Rule section in the README](https://github.com/windwp/nvim-autopairs#rule), and check the [Rule API in the wiki](https://github.com/windwp/nvim-autopairs/wiki/Rules-API).

From my testing, this seems to work
```
local npairs = require("nvim-autopairs")
local Rule = require("nvim-autopairs.rule")

npairs.add_rules({
    Rule("$$","$$","tex"),
    Rule("\\[","\\]","tex")
})
```
Try it out, but you might have to add exceptions to the rule so it works correctly.
In the Rule section in the README there are a few examples for latex, so check those out. The rule for $|$ should be good there.

**Comment by aloispichler** [comment]
Thanks, but this does not solve 3, for example…

**Comment by FrancoRav** [comment]
For 3, you need to set the `with_move()` method for the Rule. I've set it to `done()` so it is always true, so 3 would work. Try with that, and if there's unexpected behaviour try replacing the condition (maybe `is_ts_node({"inline_formula"})` would work correctly)
For 2, I had issues getting it to work without tree-sitter, as I couldn't find the correct regex. So what I did was setting the condition for `with_pair()` to `is_not_ts_node({"inline_formula"})`
You need treesitter for this, so if you are not using it and do not want to use it, you have to find the correct regex for the rule.
Here is the full Rule
```
local npairs = require("nvim-autopairs")
local Rule = require("nvim-autopairs.rule")
local cond = require("nvim-autopairs.conds")
local ts_conds = require("nvim-autopairs.ts-conds")

npairs.add_rules({
    Rule("$", "$",{"tex", "latex"})
    -- add a pair if it's not already in an inline_formula (example 2)
    :with_pair(ts_conds.is_not_ts_node({"inline_formula"}))
    -- move right when repeating $
    :with_move(cond.done())
    -- disable adding a newline when you press <cr>
    :with_cr(cond.none()),
})
```

**Comment by aloispichler** [comment]
This is a pretty useful extension.
Now it works – thank you indeed for your detailed explanation here!

**Comment by FrancoRav** [comment]
> This is a pretty useful extension.
> Now it works, at least for `$` – thank you indeed for your detailed explanation here!
> Perhaps we should add this to the docs.
> 
> What remains are 6 and 5  :-)

I think you can use the same methods and conditions for the second rule, but you should replace the "inline_formula" part with "displayed_equation", which is treesitter's node for a \[...\] block
Try that and let me know how it works. From what I tried, the with_move() method to done() moves over the entire end string when pressing \
So, instead of
`6   let \[x=4|\]  \]    let \[x=4\]|`
It would be
`6   let \[x=4|\]  \    let \[x=4\]|`

I'll see if I can find a condition that moves on \], but I'm not sure it is possible.

5 should work fine I think

**Comment by aloispichler** [comment]
Hello again!
it works, but with unacceptable side effects, as every LaTeX command starts with `\`. Using `\` to escape thus is not a possible option.
writing `   let \[ \alpha=    \]`, for example, would destroy to workflow (as it escapes on `\ (alpha)`.
Hmm.

**Comment by aloispichler** [comment]
Okay, here is a small trick I did not know before: `)` leaves any pair :-)

**Comment by aloispichler** [comment]
The next problem is to write the simple formula `$\alpha=3$`
because `$\$` exits autopairs.
I am getting desperate, and I start to think that autopairs does not work with LaTeX.

**Comment by haoming-li-ling** [comment]
I suggest before the issue is fixed, use auto-expanding snippets to do the trick. Then you can use the tab key to get out of the math environment.
