### ISSUE TITLE
Manual pairs?

### ISSUE THREAD

**Issue by kiyoon** [windwp/nvim-autopairs#326]
**Is your feature request related to a problem? Please describe.**
I like this plugin but as a vim user I also sometimes want to do things manually. I want manual pairs, or undo the triggered autopairs on key.

**Describe the solution you'd like**
1. Manual pairs. On key (like `<M-p>`) I want the autopairs to activate and make a closing pair.
2. Undo pairs. On key (like `<M-u>`) I want to undo the autopairs so only the closing bracket will be removed. Currently `<BS>` will remove both opening and closing.
3. I don't need the keymap to fallback to something else. So I don't want <M-p> to suddenly paste something which I don't want. It would be good if a function is exposed so I can configure it myself. It's the same for `<M-e>` now because I often find this moving my cursor when all I want is to just perform fast-wrap.

**Describe alternatives you've considered**
I found a solution to "1" that I can just use LuaSnip. However, it won't have features like fast wrap and undo pairs ("2").

**Additional context**

**Comment by windwp** [comment]
If you want to customize something for personal use, you should read the rule API
The rule API is highly customizable. It is an improvement over nvim_set_keymap with support for binding multiple actions to one key and checking multiple conditions. Additionally, it supports filetypes out of the box.

1:
```lua
require("nvim-autopairs").get_rule("'")[1]
    :use_key("<m-p>")
    :replace_endpair(function()
        return "'<left>"
    end)
```
2: create a new rule and map to key  then delete a right char.
3. There isn't a perfect solution now.

**Comment by kiyoon** [comment]
Thanks for this. It seems promising. For (2) is there no way but to remap every rule? For example the char may not be on the right (e.g. fast wrap)
