### ISSUE TITLE
Indent is off in Svelte files

### ISSUE THREAD

**Issue by Everduin94** [windwp/nvim-autopairs#328]
### Description

When expanding a curly brace in a svelte file I would expect:

```
    Before        Input         After
    ------------------------------------
    {|}           <CR>          {
                                    |
                                }
    ------------------------------------
```

However, it returns
```
    Before        Input         After
    ------------------------------------
    {|}           <CR>          {
                                      |
                                    }
    ------------------------------------
```

**What I've Tried**: I've searched issues, tried turning treesitter/`check_ts` on/off. Tried to look at how I might write a custom rule to fix, but wasn't exactly sure since I just want the default behavior for curly braces.

### Steps to reproduce

Using a minimal config, open a `svelte` file. Type a `{`, press `enter`/`CR`. -- I've left the minimal config as is below. As just calling `require('nvim-autopairs').setup()` is how I've reproduced the issue.

https://user-images.githubusercontent.com/14320878/220717299-a1f8e6a7-bf89-4eba-8ab3-2fefe3606cc1.mov

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'windwp/nvim-autopairs',
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('nvim-autopairs').setup()
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing nvim-autopairs and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by windwp** [comment]
it is treesitter bug. my plugin don't do anything about indent here.

**Comment by Everduin94** [comment]
@windwp -- Sorry about that. That's my bad. I was testing thinking treesitter was off, but I guess the parsers are still working even if you remove the treesitter setup function. And so then I turned autopairs off and basically did a test like this (see video). But I see what you mean now.


https://user-images.githubusercontent.com/14320878/220908420-3f207145-c854-4885-b28b-6f2cbfa2c999.mov
