### ISSUE TITLE
Autopair angle brackets

### ISSUE THREAD

**Issue by musjj** [windwp/nvim-autopairs#330]
Trying to get completion for angle brackets, but it's not working quite right:
```lua
autopairs.add_rules { Rule { start_pair = "%a+<", end_pair = ">", is_regex = true } }
```
Basically, I want it to only complete brackets when preceded by alphanumeric characters (e.g. `FooBar<Type>`)
But it keeps adding the end pair when typing inside it, and deleting the bracket will also remove text behind it.

**Comment by musjj** [comment]
Figured it out, it's:
```lua
local autopairs = require("nvim-autopairs")
local cond = require("nvim-autopairs.conds")
autopairs.add_rules { Rule("<", ">"):with_pair(cond.before_regex("%a+")) }
```

**Comment by bew** [comment]
@musjj Your solution seems to have a bug (or maybe it's a bug with the plugin?):

When I try to write `Option<|>` (`|` is the cursor), typing any of `(`, `)`, `<`, `>`, `]`, `}` will simply move cursor after `>` (so I get `Option<>|`), making it quite hard to write `Option<(Foo)>` in Rust..

**Comment by musjj** [comment]
That's a really funny coincidence, I just fixed a bug related to this literally a few minutes ago:
```lua
local autopairs = require("nvim-autopairs")
local Rule = require("nvim-autopairs.rule")
local cond = require("nvim-autopairs.conds")
                                                                                                                    
autopairs.add_rules {
  Rule("<", ">"):with_pair(cond.before_regex("%a+")):with_move(function(opts) return opts.char == ">" end),
}
```
This will only move the cursor if you type `>`. But it looks like you don't even want that, so you might as well remove `:with_move()` entirely.

**Comment by bew** [comment]
Fun times :stuck_out_tongue: 

However it looks like a bug to me, the documentation of `with_move` [states](https://github.com/windwp/nvim-autopairs/wiki/Rules-API#with_movecond):
> `with_move(cond)`
>
> If `cond` is true, the cursor is simply moved right when typing the ending part of the pair and the next character is also the ending part, e.g. `foo|"` => `foo"|` when typing `"`. If `cond` returns false, the ending part is inserted as normal instead.

So it should be only when typing the ending part (`>`), not when typing all the other keys I mentioned, isn't that right?

**Comment by bew** [comment]
Yeah, I [updated the wiki page](https://github.com/windwp/nvim-autopairs/wiki/Rules-API/_compare/ca8673daeb8a35b904a0020e0eb6810c2dd9e95c...40544de53b9eb24100809d9d9b9cf8f3caa3af7e) to be more explicit about that and the options the functions get (looking at the code for reference)

**Comment by bew** [comment]
The bug I'm mentioning was already reported at #331

**Comment by bew** [comment]
Great coincidence again, I just recently realized it didn't work with `foo::`, now it's all perfect 🤗

**Comment by mrjones2014** [comment]
I went ahead and added to the wiki

https://github.com/windwp/nvim-autopairs/wiki/Custom-rules#auto-pair--for-generics-but-not-as-greater-thanless-than-operators

**Comment by MariaSolOs** [comment]
I don't understand why but for some reason the rule from the wiki doesn't apply the right move work in TypeScript files. If I type `Foo<`, the closing `>` is inserted, but typing `>` doesn't move the cursor and inserts another bracket instead.
