### ISSUE TITLE
Move with other pairs

### ISSUE THREAD

**Issue by jakubkaczor** [windwp/nvim-autopairs#331]
### Description

Using `Rule` the cursor moves independent of the type of ending pair. That is having
``` lua
Rule("$", "$", "markdown"):with_move(conds.done())
```
in the configuration, the cursor is moved with `"`, `)`, etc., even with `(`, which is an opening bracket, while this behavior is expected only with `$`.

### Mapping <cr> bug

nil

### Steps to reproduce

1. Run `nvim -u minimal.lua test.md` to open a new markdown file with a minimal config.
2. Enter insert mode.
3. Type `$a`. The state of the buffer is `$a|$`, where `|` is the cursor. After pressing other ending pair, such as `"` it moves to the state `$a$|`.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'windwp/nvim-autopairs',
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  local autopairs = require('nvim-autopairs')
  autopairs.setup()
  local Rule = require "nvim-autopairs.rule"
  local conds = require "nvim-autopairs.conds"

  autopairs.add_rule(
    Rule("$", "$", "markdown"):with_move(conds.done())
  )
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing nvim-autopairs and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by TheOmegaCarrot** [comment]
I am also experiencing this issue.

**Comment by haoming-li-ling** [comment]
I suggest before the issue is fixed, use auto-expanding snippets to do the trick. Then you can use the tab key to get out of the math environment.

**Comment by TheOmegaCarrot** [comment]
Any new information or workarounds regarding this bug?

**Comment by bew** [comment]
Well I opened a PR yesterday at #357, I think it would help if you can test it :smiley:

Or if someone can understand why one of the test doesn't work as I expected
