### ISSUE TITLE
Implement `ultimate-autopair.nvim`'s fastwarp

### ISSUE THREAD

**Issue by altermo** [windwp/nvim-autopairs#337]
[ultimate-autopair.nvim](https://github.com/altermo/ultimate-autopair.nvim) has a fastwarp (not fastwrap) feature which I would like to be implemented as an alternative to fastwrap. There are some situations (like `{(|){{foo}}}`) where the fastwrap does not cut it.

**Comment by bew** [comment]
Could you describe what it does?

**Comment by altermo** [comment]
It moves the next closing parentheses to the next predefined position. This position includes end of word, beginning of bracket, and end of bracket, end of line, beginning of line...
Example: `(|)foo,{[bar]}` > `(foo|),{[bar]}` > `(foo,|){[bar]}` > `(foo,{[bar]}|)`
There are also stopping predefined positions like end of bracket at which point the closing parentheses can't go past...
Example: `{(|);;;}` > `{(;;;|)}`

**Comment by windwp** [comment]
Current fastwrap can jump to a destination. If you press a lowercase of character it only add a bracket but if you press a uppercase of that character if will add a bracket and jump to that point too.
an automatic add wrap bracket is not correct 100% most of case it place wrong .

**Comment by altermo** [comment]
It wouldn't be automatic, it would be a keybinding.
