### ISSUE TITLE
Wrong indent with curly braces and coq_nvim

### ISSUE THREAD

**Issue by EnricoSteez** [windwp/nvim-autopairs#339]
### Description

I used the recommended [config](https://github.com/windwp/nvim-autopairs#mapping-cr) for mapping <CR> when using COQ_nvim.
Before pressing `<CR>`:
<img width="496" alt="Screenshot 2023-03-12 at 19 07 37" src="https://user-images.githubusercontent.com/50551517/224564003-3a693697-c64c-4f7d-8e63-8797fa5874ca.png">
After pressing `<CR>`:
<img width="336" alt="Screenshot 2023-03-12 at 19 07 49" src="https://user-images.githubusercontent.com/50551517/224564025-94bd726f-7dd1-40eb-a7c2-a0c50f4911e1.png">
The indentation is off.
`:verbose imap <cr>` -> `i  <CR>        * v:lua.MUtils.CR()`

**Comment by windwp** [comment]
you should reading the issue template  and search indent  issue
