### ISSUE TITLE
Also catch `<C-w>` in insert mode

### ISSUE THREAD

**Issue by Bekaboo** [windwp/nvim-autopairs#344]
**Is your feature request related to a problem? Please describe.**
Currently nvim-autopairs will catch `<BS>` in insert mode and delete paired parenthesis, however it will not respond when the opening parenthesis is deleted by `<C-w>`. For instance:

1. Press `(`: `(|)`
2. Press `<BS>`: `|` (desired)

1. Press `(`: `(|)`
2. Press `<C-w>`: `|)` (undesired)

**Describe the solution you'd like**
Also catch `<C-w>` in insert mode.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by windwp** [comment]
it have option map_c_w
https://github.com/windwp/nvim-autopairs#default-values

**Comment by Bekaboo** [comment]
Thanks.
