### ISSUE TITLE
attempt to call field 'autopairs_cr' (a nil value)

### ISSUE THREAD

**Issue by rafamadriz** [windwp/nvim-autopairs#35]
The sample mapping with nvim-compe gives the error `attempt to call field 'autopairs_cr' (a nil value)` when `CR` is pressed and it types a zero instead.

![2021-Apr-18](https://user-images.githubusercontent.com/67771985/115149070-ecc41280-a051-11eb-832d-5d0caf6ff6dd.png)

This is the config (taken from the README)
```lua
local remap = vim.api.nvim_set_keymap
local npairs = require('nvim-autopairs')

-- skip it, if you use another global object
_G.MUtils= {}

vim.g.completion_confirm_key = ""
MUtils.completion_confirm=function()
  if vim.fn.pumvisible() ~= 0  then
    if vim.fn.complete_info()["selected"] ~= -1 then
      return vim.fn["compe#confirm"](npairs.esc("<c-r>"))
    else
      return npairs.esc("<cr>")
    end
  else
    return npairs.autopairs_cr()
  end
end


remap('i' , '<CR>','v:lua.MUtils.completion_confirm()', {expr = true , noremap = true})
```

**Comment by windwp** [comment]
can you pull a latest version and test again?
 
thank

**Comment by rafamadriz** [comment]
My bad I always forget to update the damn plugins. It's working.
