### ISSUE TITLE
get_rules for quotes returns nil

### ISSUE THREAD

**Issue by TomLebeda** [windwp/nvim-autopairs#354]
### Description

This issue originates from #353 

I want to disable rule for double quotes in TeX and LaTeX files, so I use:
`require('nvim-autopairs').get_rules('"')[1].not_filetypes = { "tex", "latex" }`
but the get_rules returns nill so I get error on the indexing. 

The same thing happens when I uncomment this snippet:
```
-- this will fix the problem where cursor jumps over closing quote when the char is escaped (writing "\"" will work as expected instead of jumping over and leaving just "\")
for _, char in ipairs({ "'", '"', "`" }) do
for _, r in ipairs(autopairs.get_rules(char)) do
	r:with_move(cond.not_before_text('\\'))
		:with_del(function(opts)
			local prev_col = vim.api.nvim_win_get_cursor(0)[2] - 1
			return opts.line:sub(prev_col, prev_col) ~= '\\'
		end)
end
end
```

Both worked in previous version with "get_rule". 

Or did something change and I am just using it wrong now? I checked the readme and it seems like the usage is the same as mine.  

### Steps to reproduce

1. update plugin to the last version
2. use this line somewhere in config: 
`require('nvim-autopairs').get_rules('"')[1].not_filetypes = { "tex", "latex" }`

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'windwp/nvim-autopairs',
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('nvim-autopairs').setup()
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing nvim-autopairs and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]

-- this line was added:
`require('nvim-autopairs').get_rules('"')[1].not_filetypes = { "tex", "latex" }`
```

**Comment by mkalinski** [comment]
The root cause is here.

https://github.com/windwp/nvim-autopairs/commit/1748b0a11149b5fcdda2c4e0185c1ab991592f59#diff-b487aba2c13ea447570cfe05334d00e05c4c001ee0bcf65cc2cc457ccc3527d9L92

`get_rules` is broken because the whole section that returned values was moved to `get_rule` (which is itself broken because of a typo) without replacing it with anything, so it always returns `nil` because there's no return statement.
