### ISSUE TITLE
wrong position of closing apostrophe and quote symbols

### ISSUE THREAD

**Issue by shabaev** [windwp/nvim-autopairs#356]
### Description

The plugin puts apostrophe and quote symbols in the same position whatever I press as an anchor.

### Steps to reproduce

an initial line. insert mode. **|** is a cursor position:
`|string1 string2`

I press **(** and **Alt+e** and it appears as:
`(string1qstring2$`

I press **$** and it's changed to:
`(|string1 string2)`

correct. now I press **'** and **Alt+e** and it appears as:
`('string1qstring2w$`

I may press **w** or **$**, but the result is the same:
`('|string1 string2)'`

in case I press **$** it's the correct position, in case I press **w** it's wrong position and I expect the apostrophe to be place before the closing bracket.

it does not behave such way with a brackets - one more example - after each opened bracket/quote/apostrophe I pressed **Alt+e** and **q** to pick the closest position:
`({["'string]'"})`
what looks wrong coz logically it should be...
`({["'string'"]})`

I reproduced such behavior in neovim 0.7, 0.8 and 0.9 with the autopair commit 7747bbae60074acf0b9e3a4c13950be7a2dff444

What did I do wrong? Thank you in advance!

### Minimal config

```Lua
call plug#begin()
Plug 'windwp/nvim-autopairs'
call plug#end()

lua << EOF
require("nvim-autopairs").setup({
  fast_wrap = {},
})
EOF
```

**Comment by nieomylnieja** [comment]
Same here :/ There's no way to close the parentheses inside brackets right now, both `q` and `$` have the same effect, i.e. the parentheses are placed after the bracket.
![2023-05-20_12-11_1](https://github.com/windwp/nvim-autopairs/assets/48822818/c5b5d53d-9313-41e6-bf60-745da4dd94b0)
![2023-05-20_12-11](https://github.com/windwp/nvim-autopairs/assets/48822818/77bb1964-5d31-4c42-b1b2-0e198e644d49)
