### ISSUE TITLE
bug after update pairs are inserted backwards )( ][

### ISSUE THREAD

**Issue by argapost** [windwp/nvim-autopairs#36]
Hello,

After I did a PackerUpdate today the pairs are inserted the other way around )( ][.

Can you reproduce?

Thank you in advance.

**Comment by JoseConseco** [comment]
I have this error too. Please fix windwp

**Comment by windwp** [comment]
i am not sure about this but you can update and test again

**Comment by 1bharat** [comment]
It is working now. I updated to the latest.

**Comment by argapost** [comment]
Yeap it's working now thanks.
