### ISSUE TITLE
Automatically add padding to opposite side

### ISSUE THREAD

**Issue by vinnydiehl** [windwp/nvim-autopairs#360]
It would be nice if, after typing e.g. "{ " so that there is whitespace padding the inside of the braces, an equal amount of whitespace were automatically added to the other side, and then removed if the user were to remove the padding. Once there is content in there other than the whitespace, this would no longer be monitored as that would be IMO outside the scope of this plugin.

**Comment by v3s1e** [comment]
Just to make sure, you're talking about the following feature, correct?

```
input: {|} (press <SPACE> at |)
output: { | }

input: {|} (press <SPACE>foo} at |)
output: { foo }|

input: '|' (press <SPACE> at |)
output: ' |'
``

**Comment by vinnydiehl** [comment]
@v3s1e Yes, exactly right. I think this feature would make sense to employ only on `{}`, `[]`, and `()` pairs by default.

**Comment by windwp** [comment]
https://github.com/windwp/nvim-autopairs/wiki/Custom-rules
it already  there

**Comment by vinnydiehl** [comment]
Amazing! Guess I should have dug deeper. Thank you.

**Comment by v3s1e** [comment]
Shouldn't this be a default rule?
