### ISSUE TITLE
Make fast wrap more configurable

### ISSUE THREAD

**Issue by asmodeus812** [windwp/nvim-autopairs#361]
**Is your feature request related to a problem? Please describe.**
Improvement on top of existing feature of fast wrap

**Describe the solution you'd like**
Hi, as it is fast wrap is a very cool feature of this plugin, but i find myself wanting to have more flexibility in the way we move to the second element of the pair. Currently, it is hard coded that upper case characters is what move you to the pair, i find myself wanting to go to that final pair more often than not, and wanting to use for example a lower case character instead of upper since it's faster to type and work with, maybe we can have the current property key be extended, to be not just be a string of alphas, but rather array of pair {start,end} symbols, where pressing the start symbol will move you to the start, pressing the end symbol will move you to the end. We can still support type == string for that property for backwards compatibility.

Another related feature, allow the cursor to land on different positions, as it is now the cursor lands before the second symbol of the pair `"text|"` i find myself that when you wrap things usually you want to continue to write outside after the wrapped text `"text"|` like that. So it could be configurable, before or after for example.

**Describe alternatives you've considered**
Well, i have considered overriding the move to always pass `true` to move the cursor to the second part of the pair. But it is a messy solution.

```lua
local fastwrap = require("nvim-autopairs.fastwrap")
local move_bracket = fastwrap.move_bracket
---@diagnostic disable-next-line: duplicate-set-field
fastwrap.move_bracket = function(line, pos, pair, _)
        move_bracket(line, pos, pair, true)
end

```
**Additional context**
None.

**Comment by windwp** [comment]
can you add 
npairs.setup({
fast_wrap={
        manual_position = true,
}}

it will open another option to select position after first key.

**Comment by asmodeus812** [comment]
Yeah, i have tried, That works , but introduces more keypresses as it is now the default wrap is biased t(o auto position) towards a single assumption where both are equally right.
