### ISSUE TITLE
Is there a way to configure nvim-autopairs for Groovy?

### ISSUE THREAD

**Issue by rootex-** [windwp/nvim-autopairs#366]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when in Groovy I type:
```
def func() {|}
```
and get this:
```
def func() {
        |
    }
```
I know there has always been a problem with indentation for Groovy in vim/nvim. 
The language is poorly maintained in Neovim ecosystem. 
Even [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) does not offer any groovy support at this moment. 
Yet, it's  already in the wishlist: 

* https://github.com/nvim-treesitter/nvim-treesitter/issues/3938
* https://github.com/nvim-treesitter/nvim-treesitter/issues/2282

But, perhaps, there is a way to write a Rule that solves this kind of problem? 

**Describe the solution you'd like**
Coming up with a solution that would help to indent closing brackets for Groovy properly. By properly I mean: 
```
def func() {
    |
}
```

**Describe alternatives you've considered**
As far as I know, there is a tool capable for linting and indenting groovy built with npm: 
https://www.npmjs.com/package/npm-groovy-lint
It is supported by null-ls:
https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/formatting/npm_groovy_lint.lua
Perhaps, nvim-autopairs could rely on this if npm-groovy-lint handles auto-indentation properly.

**Comment by windwp** [comment]
This plugin depend on setting of editor indentexpr  it only auto press == for trigger  that  default indent of vim. So you need find a plugin to do that

Search groovy vim indent.

**Comment by rootex-** [comment]
@windwp Thanks, I have finally switched to Treesitter identation since it's already implemented for Groovy.
