### ISSUE TITLE
Bad indentation when it comes to React coding with neovim and lua config

### ISSUE THREAD

**Issue by Ngomana** [windwp/nvim-autopairs#367]
### Description

I've noticed that auto indent doesn't work when i use `()` and then hit `<CR>` indent stays in once place and aligned with the bracket. I sometimes have to hit `<TAB>` just to have proper indentation. 

i'm using macos: high sierra 
neovim verions: 8.4

https://github.com/windwp/nvim-autopairs/assets/61317733/594e256a-c610-4c14-8820-2640861ca7bc

### Mapping <cr> bug

1.If you report a bug about indent. Please remember that plugin doesn't do anything about indent.
  It just trigger the indent of your vim config so if you have wrong indent config then it will do wrong indent.
  You can check by select a block of code and press `==`
2. provide result of command `:verbose imap <cr>`.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'windwp/nvim-autopairs',
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('nvim-autopairs').setup()
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing nvim-autopairs and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by windwp** [comment]
from an issue  template
```
1.If you report a bug about indent. Please remember that plugin doesn't do anything about indent.
It just trigger the indent of your vim config so if you have wrong indent config then it will do wrong indent.
You can check by select a block of code and press ==
2. provide result of command :verbose imap <cr>.
```

that issue come from treesitter indent. if you press `o` when cursor on ` |return` text it will have wrong indent too
 return (
 )

**Comment by Ngomana** [comment]
i do have treesitter installed, what can i do to fix the issue?

**Comment by windwp** [comment]
asking on  nvim-treesitter repo?
my plugin is only automatic  press O after you press <CR> so nothing i can do here.
