### ISSUE TITLE
Can we have the same deletion behavior as jiangmiao/auto-pairs?

### ISSUE THREAD

**Issue by TroySigX** [windwp/nvim-autopairs#369]
**Is your feature request related to a problem? Please describe.**
For some pair of brackets where the only characters between them are space or newline, when deleting the opening bracket, it's best to also delete the ending bracket.
E.g:
```
{|   
}
```
where `|` is the current cursor, after pressing `<BS>`, it's expected to also delete the ending bracket.

**Describe the solution you'd like**
continuously checking the characters from the current cursor to the ending bracket, if there are only spaces and newlines, enable deleting in pair.

**Describe alternatives you've considered**
None

**Comment by 9mm** [comment]
I tried that plugin because of this issue @TroySigX ... after i did that it doesnt even seem to backspace across newlines.

When you use that plugin, does it actually do that?

**Comment by TroySigX** [comment]
Yes, it does delete across newlines. Here's my config:
``` lua
require('nvim-treesitter.configs').setup({
  endwise = {
    enable = true,
  },

  autotag = {
    enable = true,
  },
})

require('npairs-int-upair').setup({
  bs = 'u',
  map = 'n',
})

local Rule = require('nvim-autopairs.rule')
local npairs = require('nvim-autopairs')
local cond = require('nvim-autopairs.conds')
npairs.add_rules({
  Rule('$', '$', { 'tex', 'latex' }):with_move(cond.none()):with_del(cond.done()):with_cr(cond.done()),
})
```
