### ISSUE TITLE
Backreferences from end_pair to begin_pair

### ISSUE THREAD

**Issue by usertzuiop** [windwp/nvim-autopairs#371]
**Is your feature request related to a problem? Please describe.**
LaTeX and ConTeXt have environments in which certain macros work. I would love to be able to pair them. 

ConTeXt:
```
\startitemize
   \item First item
   \item Second item
\stopitemize
```

**Describe the solution you'd like**

press `\starttext │` → `\starttext │ \stoptext`
```
npairs.add_rules({
    Rule("\\start(%w*)", "\\stop%1", "context")
      :use_regex(true)
})
```

**Describe alternatives you've considered**
The same can be done using snippets, but it is not so convenient, since you will have to press Tab many times to select the desired one.

**Comment by windwp** [comment]
```lua
npairs.add_rules({
    Rule("\\start(%w*) $", "")
        :replace_endpair(function(opts)
            local beforeText = string.sub(opts.line, 0, opts.col)
            local _, _, match = beforeText:find("\\start(%w*)")
            if match and #match > 0 then
                return " \\stop" .. match
            end
            return ''
        end)
        :with_move(cond.none())
        :use_key("<space>")
        :use_regex(true)
})
```
you can map to space.

**Comment by usertzuiop** [comment]
It works. However, I don't quite understand how. I will read the documentation.
