### ISSUE TITLE
Plugin doesn't work unless manually setup

### ISSUE THREAD

**Issue by Boltzmachine** [windwp/nvim-autopairs#378]
### Description

The plugin doen't work (does not auto pair my "(") unless manually doing `:lua require("nvim-autopairs").setup()` in command (or adding an extra line after the plugin manager). 

NVIM: 0.9.1

### Steps to reproduce

1. open nvim
2. enter insert mode
3. type "("

### Minimal config

```Lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)
require("lazy").setup({
        "windwp/nvim-autopairs"
})
```

If I append an extra line
```
require("nvim-autopairs").setup()
```
it works.

**Comment by windwp** [comment]
Most of neovim plugin require to call a setup function. 
so it can easy add a custom config or lazy load.

**Comment by Boltzmachine** [comment]
but is it called by the plugin manger, i.e. lazy.nvim here?

**Comment by gruvw** [comment]
I have the same problem here, idk why setup isn't called automatically by lazy

**Comment by Dioprz** [comment]
If you will not pass arguments to setup through the `opts` option of lazy, you should add the `config = true` option so that lazy knows to do the `require('...').setup()` call. 

```
return {
  'windwp/nvim-autopairs',
  config = true,
}
```

Alternatively you can set `opts = {}`

See here: [plugin spec](https://github.com/folke/lazy.nvim#-plugin-spec)
