### ISSUE TITLE
Support for React fragments

### ISSUE THREAD

**Issue by ZyriabDsgn** [windwp/nvim-autopairs#391]
**Is your feature request related to a problem? Please describe.**
I have the basic setup, using cmp (see below).
When I work on React projects, I often use fragments `<> ... </>` 
When I open a fragment, it does not close automatically

**Describe the solution you'd like**
Autoclose the fragments

**Additional context**
I guess there's a way to do it but I could not find it in the readme... I'd be happy to open a PR if not

My autopairs config:
```lua
local autopairs = require("nvim-autopairs")
local cmp_autopairs = require('nvim-autopairs.completion.cmp')
local cmp = require('cmp')

cmp.event:on(
    'confirm_done',
    cmp_autopairs.on_confirm_done()
)

autopairs.setup()
```

Cheers

**Comment by DonMiller9294** [comment]
you could download the extension emmet. make sure you have it set to auto close in the settings of that extension.

**Comment by Sam-programs** [comment]
wouldn't this work ?
```lua
npairs.add_rules({
   rule("<>","</>")
})
```
here is a basic autopairs cmp example read cmp's types lua/cmp/types if u want to learn more
```lua
local function pair_on_confirm(event)
   local entry = event.entry
   local item = entry:get_completion_item()
   local pairs = '()'
   local functionsig = item.label
   local _, c = unpack(vim.api.nvim_win_get_cursor(0))
   local line = vim.api.nvim_get_current_line()
   print("item label:",functionsig)
   if line:sub(c, c) ~= ')' and
       item.kind == kind.Function or item.kind == kind.Method
       then
       pairs = pairs .. '<left>'
       pairs = vim.api.nvim_replace_termcodes(pairs, true, false, true)
      vim.api.nvim_feedkeys(pairs, "n", false)
   end
end
```
i don't really know much about react and i don't have much time to create this
