### ISSUE TITLE
Bug: commit `f611dc2` breaks `<CR>` when having a `=` keymap

### ISSUE THREAD

**Issue by chrisgrieser** [windwp/nvim-autopairs#395]
### Description

commit `f611dc2` breaks `<CR>` when having a `=` keymap

### Steps to reproduce

- be on `f611dc2`
- add something like `vim.keymap.set("n", "=", "kkk")`
- use this snippet:

```lua
-- | = cursor location
foobar = {|}
```

- Press `enter`

Result: the `=` mapping takes effect, moving the cursor incorrectly upwards.

Issue does not occur for me on `3b664e8`

### Minimal config

```Lua
local root = vim.fn.fnamemodify("./.repro", ":p")
for _, name in ipairs { "config", "data", "state", "cache" } do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

--------------------------------------------------------------------------------

local plugins = {
	{ "windwp/nvim-autopairs", opts = true }
}

vim.keymap.set("n", "=", "kkk")

--------------------------------------------------------------------------------


local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system {
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		"--branch=stable",
		lazypath,
	}
end
vim.opt.runtimepath:prepend(lazypath)
require("lazy").setup(plugins)
```

**Comment by Sam-programs** [comment]
i used recursive mapping for = just incase a formatter uses it
i didn't know it would lead to issues like this i think it's better using the default mapping
ill just remove all recursive mapping in my current pr

**Comment by bew** [comment]
> just incase a formatter uses it

Formatter normally plugs themself into neovim using `formatexpr` or `formatprg` options, not by hijacking key mappings, so it is the right behavior to use noremap here.

**Comment by Sam-programs** [comment]
yea and `equalprg'`
i forgot about that when i read `:normal`'s docs
i just learnt everything i know about vim plugin development in like 4 days so it's a got a bit overwhelming
nevertheless i should have probably thought twice before adding recursive mapping to the pr

**Comment by Sam-programs** [comment]
fixed https://github.com/windwp/nvim-autopairs/commit/de4f7138a68d5d5063170f2182fd27faf06b0b54
again sorry everyone

**Comment by chrisgrieser** [comment]
thanks, issue is fixed with that commit 👍
