### ISSUE TITLE
Control Backspace doesn't delete a pair

### ISSUE THREAD

**Issue by jfab20** [windwp/nvim-autopairs#397]
### Description

I have
```
lua require("nvim-autopairs").setup({map_c_w=true,map_c_h=true})
```
in init.vim. I also have mapped ```<C-BS>``` to delete a word with 
```
noremap! <C-BS> <C-w>
noremap! <C-h> <C-w>
```
This makes ```<C-BS>``` behave like ```<C-w>``` . I want for control backspace to delete a pair and a word, just like ```<C-w>``` does. This functionality is not present and furthermore after installing the plugin, control backspace gets unmapped and no longer works. 

Hopefully this can be fixed, thanks!

### Steps to reproduce

Add the commands
```
lua require("nvim-autopairs").setup({map_c_w=true,map_c_h=true})
```
in init.vim or init.lua.  Map ```<C-BS>``` to delete a word with 
```
noremap! <C-BS> <C-w>
noremap! <C-h> <C-w>
```
Note that control space no longer deletes full words. After that, delete the options ```map_c_w=true``` and ```map_c_h=true```.  You can see how control backspace deletes a word.

**Comment by windwp** [comment]
are you try nmap?

**Comment by jfab-123** [comment]
> are you try nmap?

What? Do you mean that if I have tried using ```nmap <C-BS> <C-w>``` and ```nmap <C-h> <C-w>``` ?  If I put that in my config it maps ```<C-BS``` to ```<C-w>``` but in normal mode, so it doesn't do anything.

**Comment by windwp** [comment]
sorry i mean imap.
you need make sure your terminal can remap <c-bs>.  you can try `imap <c-bs> hello`.
`on my terminal it treat <c-bs> to <c-h>  when i press <c-bs> nvim  will receive <c-h>`
 
maybe you can map it to lua function  https://github.com/windwp/nvim-autopairs/blob/de4f7138a68d5d5063170f2182fd27faf06b0b54/lua/nvim-autopairs.lua#L334
