### ISSUE TITLE
Fast wrap to the end of the line doesn't put end pair to the very end

### ISSUE THREAD

**Issue by bew** [windwp/nvim-autopairs#398]
### Description

When trying to use the fast wrap feature I'm getting unexpected behaviors.

### Steps to reproduce

![Peek 2023-09-24 12-47](https://github.com/windwp/nvim-autopairs/assets/9730330/ff9fa4d6-1191-4cb4-9f8e-4fd5e1866e86)

On the first line when I fast wrap to the end, the `)` is immediately put before the end instead of the very end.
On the second line, when I fast wrap to the end (after the existing brace), I get to choose where to put the new `)`.

I think the first case should put the end pair at the very end.

Although I'm not found of the difference of behavior between the 2 lines.
:point_right: I want that when I wrap to the end of line with `$` hint, it _always_ put the end pair at the very end, without asking to put it before/after the last char.
To that end, I think the `$` hint should be after the last char to show it'll always put end pair at the very end.

### Minimal config

```Lua
-- example line
-- example line (with braces already)
vim.opt.rtp:append("/home/bew/.local/state/nvim-wip/managed-plugins/start/nvim-autopairs")

require"nvim-autopairs".setup {
  fast_wrap = {
    map = "<C-M-l>",
    highlight = "Search",
  },
}
```

**Comment by fcarvalhopacheco** [comment]
I'm facing similar issues. I am using `lazy.nvim`.

my configuration:

```lua
-- File: lua/custom/plugins/autopairs.lua

return {
  "windwp/nvim-autopairs",
  -- Optional dependency
  dependencies = { 'hrsh7th/nvim-cmp' },
  config = function()
    require("nvim-autopairs").setup {}
    -- If you want to automatically add `(` after selecting a function or method
    local cmp_autopairs = require('nvim-autopairs.completion.cmp')
    local cmp = require('cmp')
    cmp.event:on(
      'confirm_done',
      cmp_autopairs.on_confirm_done()
    )

    local npairs = require("nvim-autopairs")
    local Rule = require('nvim-autopairs.rule')
    -- put this to setup function and press <a-e> to use fast_wrap
    npairs.setup({
      fast_wrap = {},
    })
    -- change default fast_wrap
    npairs.setup({
      fast_wrap = {
        map = '<M-e>',
        chars = { '{', '[', '(', '"', "'" },
        pattern = [=[[%'%"%>%]%)%}%,]]=],
        end_key = '$',
        before_key = 'h',
        after_key = 'l',
        cursor_pos_before = true,
        keys = 'qwertyuiopzxcvbnmasdfghjkl',
        manual_position = true,
        highlight = 'Search',
        highlight_grey = 'Comment'
      },
    })
  end,
}

```

**Comment by kessejones** [comment]
I think this is happening because of the `manual_position` was changed to `true` in commit 1be91cc0289cbfc485b593260dedfcf7feb01580

**Comment by bew** [comment]
Thanks @windwp, looks like the end pair is put at the very end correctly now 👍

> Although I'm not fond of the difference of behavior between the 2 lines.
> 👉 I want that when I wrap to the end of line with `$` hint, it _always_ put the end pair at the very end, without asking to put it before/after the last char.
>
> To that end, I think the `$` hint should be after the last char to show it'll always put end pair at the very end.
> If the line ends with a char matching the pattern there would be another hint for it, that allows to put the end pair before/after.

What do you think about this behavior change suggestion for `$` hint?
