### ISSUE TITLE
Creating a custom tree sitter rule for the angle bracket pair (`<>`) that also escapes does not work

### ISSUE THREAD

**Issue by j-barnak** [windwp/nvim-autopairs#405]
### Description

I am trying to add a treesitter rule that creates the `<>` pair

The only time I **don't** want `<>` to pair is when it's used as a binary expression. By
that, I mean for the bitshift operator (`<<`) and the less than operator (`<`). Here's what I mean

    if (x < y) // Do not pair the `<`
        std::cout << "foo"; // Do not pair the <<

The bitshift operator and less than operator are both binary expressions so I thought
I could encapsulate the pairing with the following

    local npairs = require("nvim-autopairs")
    local Rule = require("nvim-autopairs.rule")
    local ts_conds = require("nvim-autopairs.ts-conds")

    npairs.setup(opts)

    npairs.add_rules({
      Rule("<", ">", "cpp"):with_pair(ts_conds.is_not_ts_node({ "binary_expression" })),
    })

but this doesn't work.

I've also tried to manually add all the instances of where the bracket is used as a pair with

    npairs.add_rules({
      Rule("<", ">", "cpp"):with_pair(
        ts_conds.is_ts_node({ "preproc_include", "template_declaration", "template_argument_list" })
      ),
    })

This works for `preproc_include`, but not `template_declaration`. The AST for templates look like

    (template_declaration) ; [3:1 - 55]
     parameters: (template_parameter_list) ; [3:10 - 21]
      (type_parameter_declaration) ; [3:11 - 20]
       (type_identifier) ; [3:20 - 20]

And this is what it looks like for templated class declarations

    value: (compound_literal_expression) ; [6:23 - 40]
     type: (qualified_identifier) ; [6:23 - 38]
      scope: (namespace_identifier) ; [6:23 - 25]
      name: (template_type) ; [6:28 - 38]
       name: (type_identifier) ; [6:28 - 33]
       arguments: (template_argument_list) ; [6:34 - 38]
        (type_descriptor) ; [6:35 - 37]
         type: (primitive_type) ; [6:35 - 37]

How could I get this rule to work?

### Mapping <cr> bug

1.If you report a bug about indent. Please remember that plugin doesn't do anything about indent.
  It just trigger the indent of your vim config so if you have wrong indent config then it will do wrong indent.
  You can check by select a block of code and press `==`
2. provide result of command `:verbose imap <cr>`.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'windwp/nvim-autopairs',
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('nvim-autopairs').setup()
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing nvim-autopairs and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]

local npairs = require("nvim-autopairs")
local Rule = require("nvim-autopairs.rule")
local ts_conds = require("nvim-autopairs.ts-conds")

npairs.setup(opts)

npairs.add_rules({
  Rule("<", ">", "cpp"):with_pair(ts_conds.is_not_ts_node({ "binary_expression" })),
})
```

**Comment by Sam-programs** [comment]
```lua
-- add <> pairs if not in a statement
npairs.add_rules({
   rule("<", ">", "cpp"):with_pair(ts_conds.is_not_ts_node({ "compound_statement"})),
})

-- add <> if in a template or typing a templated type
npairs.add_rules({
   rule("<", ">", "cpp"):with_pair(ts_conds.is_ts_node({ 
      "translation_unit", -- when writing a template
      "initializer_list", -- when writing a templated type
   })),
})
```
sadly both don't work in cases like this
```cpp
 std::vector<int> a = std::vector<int>{1,2,3};
                      compound_statement-----
```
the second vector won't get pairs
but that cases is rare and am not sure we can do better with treesitter

**Comment by Sam-programs** [comment]
hmm this actually seems like a good idea for cmp completion

**Comment by j-barnak** [comment]
It seems that the suggested doesn't work for for

    std::cout << "foo"; 

Attempting the above will generate

    std::cout  <> "foo";

Additionally, I've been trying to write a rule to pairs `{` and `};` for classes and structs. And I've tried

    npairs.add_rules({
      rule("{", "};", "cpp"):with_pair(
        ts_conds.is_ts_node({ "class_specifier", "type_identifier", "field_declaration_list" })
      ),
    })

And a combination of those 3 nodes and no luck?

**Comment by Sam-programs** [comment]
@j-barnak
for the second issue i use this
```
local cpp_cond = function ()
   local line = vim.api.nvim_get_current_line()
   -- match for() while() functions()
   local pattern = '^.*(.*)'

   if vim.fn.match({ line }, pattern) == 0 then
      return false
   end
end

npairs.add_rules({
   rule("{", "};", "cpp"):with_pair(
   cpp_cond
   ),
})
```
i am trying to figure out a way for the first one we might have to restore to checking if template is on the line rather than using treesitter

**Comment by j-barnak** [comment]
@Sam-programs Thanks! 

> i am trying to figure out a way for the first one we might have to restore to checking if template is on the line rather than using treesitter

I've been scratching my head over this problem for the past few days and I couldn't come up with anything.

Is it possible to just escape the pairs and not complete the pair. For example, with mini.pairs, the following does just that. 

```
require("mini.pairs").map(
  "i",
  "<",
  { action = "open", pair = "<>", neigh_pattern = "\r.", register = { cr = false } }
)

require("mini.pairs").map("i", ">", { action = "close", pair = "<>", register = { cr = false } })
```

**Comment by Sam-programs** [comment]
i don't really understand what the mini example is doing
and i almost got a working one
```lua
local pair_cond = function ()
   local line = vim.api.nvim_get_current_line()
   -- only variable inits and structs/classes need semicolons
   local pattern = '^\\s*template'
   local c_node = ts_utils.get_node_at_cursor():type()
   if vim.fn.match({ line }, pattern) ~= 0 and
      (c_node ~= "initializer_list") 
      then
      return false
   end
end
```
it is just missing global templated variables

**Comment by Sam-programs** [comment]
@ j-barnak 
i just tested the mini example it's only putting the pairs at the start of the line
if that's what u want then this should do
```lua
local pair_cond = function()
   return vim.api.nvim_win_get_cursor(0)[2] == 0
end

npairs.add_rules({
   rule("<", ">", "cpp"):with_pair(
      pair_cond
   ),
})
```

**Comment by Sam-programs** [comment]
@j-barnak

**Comment by j-barnak** [comment]
@Sam-programs 

I was under the impression that the `mini.pairs` snippet just allowed you to escape `<>` pair by pressing `>`.

>  actually it still doesn't work with cout nvm

I also ran into bumps when dealing with the less than operator.

**Comment by Sam-programs** [comment]
@j-barnak 
i think i found something that could be helpful
cmp returns this as the label for vector 
```vector<typename Tp, typename Alloc>```
which has a > at the end
WE COULD CHECK FOR THAT TO ADD THE PAIR!
and for the case of writing a template we could check for a template match

**Comment by Sam-programs** [comment]
```lua
local function template_on_confirm(event)
   local entry = event.entry
   local item = entry:get_completion_item()
   local pairs = '<>'
   local functionsig = item.label
   if functionsig:sub(#functionsig, #functionsig) == '>' or functionsig == ' template' then
      pairs = vim.api.nvim_replace_termcodes(pairs .. "<left>", true, false, true)
      vim.api.nvim_feedkeys(pairs, "n", false)
   end
end
```

**Comment by Sam-programs** [comment]
@j-barnak sorry if the mentions are annoying

**Comment by j-barnak** [comment]
@Sam-programs No worries about the mentions. I appreciate them.

Awesome work. Do you know if it's possible to add a `with_move` to escape the `<>` pair?

I'm currently using `mini.pairs`, but only using

```
require("mini.pairs").map("i", ">", { action = "close", pair = "<>", register = { cr = false } })
```

to escape the `<>` pairing. 

I'm doing this for the `preproc_include` rule

    local rule = require("nvim-autopairs.rule")
    local cond = require("nvim-autopairs.conds")
    local npairs = require("nvim-autopairs")

    npairs.add_rules({
      rule("<", ">", "cpp")
        :with_pair(ts_conds.is_ts_node({ "preproc_include" }))
        :with_move(cond.not_before_regex(">", 1)),
    })

And one last small thing, when you select the snipped for for `#include`, it creates (the `|` represents the cursor)

    `#include<|>`

Is it possible to do generate

    `#include <|> // Note the space

Thanks for everything. Huge help!

**Comment by Sam-programs** [comment]
the `#include` was an accidental side effect lol

**Comment by Sam-programs** [comment]
@j-barnak 
for escaping you can add this rule
```lua
   rule("<", ">", "cpp"):
       with_pair(conds.none()): -- never add the end pair
       with_move(conds.done()), -- move when endpair is pressed
```
and here is a modified version of `template_on_confirm`
that adds a space for include
```lua
local function template_on_confirm(event)
   if not (vim.o.filetype == "c" or vim.o.filetype == "cpp")then
      return
   end
   local entry = event.entry
   local item = entry:get_completion_item()
   local r, c = unpack(vim.api.nvim_win_get_cursor(0))
   local line = vim.api.nvim_get_current_line()
   local pairs = ''
   local functionsig = item.label
   if line:sub(c + 1, c + 1) ~= '>' and
       (functionsig:sub(#functionsig, #functionsig) == '>' or
          functionsig == ' template')
   then
      if functionsig:sub(2, 8) == 'include' then
         pairs = ' '
      end
      pairs = pairs .. '<>'
      pairs = vim.api.nvim_replace_termcodes(pairs .. "<left>", true, false, true)
      vim.api.nvim_feedkeys(pairs, "n", false)
   end
end
```
also you can do 
\`\`\`LANG
\`\`\`
to highlight syntax

i think i should make a pr with something like this it seems really useful

**Comment by Sam-programs** [comment]
hold your horses the first check is failing

**Comment by j-barnak** [comment]
@Sam-programs Awesome stuff! I'll test it in the morning.

And just to clarify, we include `with_pair(conds.none())` for the following snippe

```lua
rule("<", ">", "cpp"):
    with_pair(conds.none())-- never add the end pair
       with_move(conds.done()), -- move when endpair is pressed
```

because `template_on_confirm` is used to complete the pairing.

And `with_move(conds.done())` enables escaping the `<>` pair by typing `>`?

**Comment by Sam-programs** [comment]
yes

**Comment by Sam-programs** [comment]
great...
```cpp
   12 void foo(){
   13    std::vector<int> a;
   14    std::vector<int> b;
   15    std::vector
   16 }        vector<typename Tp, typename Alloc> Class
~              vector(…)                           Constructor
--               NOT A >
```

**Comment by Sam-programs** [comment]
yea this
```lua
   sorting = {
      comparators = {function (entry1,entry2)
         local item1 = entry1.completion_item
         local item2 = entry2.completion_item
         if item1.kind == item2.kind then
            return nil
         end
         if math.max(item1.kind,item2.kind) == item1.kind then 
            return true 
         end 
         return false 
      end}
   },
```
not sure of a nice way to make it fit into autopairs
and i don't suggest using this for now because it might make cmp's results ugly
i am gonna try to find a good range/way to sort them (or yoink cmp's)

**Comment by Sam-programs** [comment]
i think this very unbiased list would work better
```lua
local kind_rates = {
   [kind.Snippet] = 26,
   [kind.Method] = 25,
   [kind.Function] = 24,
   [kind.Class] =  23,
   [kind.Struct] = 22,
   [kind.Interface] = 21,
   [kind.Variable] = 20,
   [kind.Reference] = 19,
   [kind.Constant] = 18,
   [kind.Constructor] = 17,
   [kind.Text] = 16,
}

local function sort_cmp(entry1,entry2)
   local kind1 = entry1.completion_item.kind
   local kind2 = entry2.completion_item.kind
   if kind1 == kind2 then
      return nil
   end
   local rate1 = kind_rates[kind1]
   local rate2 = kind_rates[kind2]
   if rate1 == nil then 
      return false
   end
   if rate2 == nil then 
      return true 
   end
   if rate1 > rate2 then
      return true 
   end
   return false 
end
```
maybe i could take the user's compartors and check if constructors and classes there but that seems a bit shady

**Comment by Sam-programs** [comment]
```lua
local config = require('cmp.config')
local cmp_comparetors = config.get().sorting.comparators

local unpack = unpack or table.unpack
local function cpp_sort_cmp(entry1, entry2)
   local kind1 = entry1.completion_item.kind
   local kind2 = entry2.completion_item.kind
   if vim.o.filetype ~= "cpp" then
      return nil
   end
   if kind1 == kind.Constructor and kind2 == kind.Class then
      return false
   end
   if kind1 == kind.Class and kind2 == kind.Constructor then
      return true
   end
   return nil
end

cmp.setup({
   sorting = {
      comparators = {
         cpp_sort_cmp,
         unpack(cmp_comparetors),
      }
   }
})
```
this seems to work best
sadly i couldn't check if `cpp_sort_cmp` was already in the comparator list
i hope windwp doesn't think of this as too shady

**Comment by Sam-programs** [comment]
after learning how to interact with lsp
i found that this actually gives the template signature when under a templated class
```lua
vim.keymap.set("i", "<C-q>", function()
   vim.lsp.handlers["textDocument/signatureHelp"] = function (_,info)
      print(info.signatures[1].label)
   end
   vim.lsp.buf.signature_help()
end)
```
which would make it possible for the `<>` pairs to work on their own
but i think it's way too overkill tho

**Comment by Sam-programs** [comment]
i need to learn to shut up
this is the most relevant message
https://github.com/windwp/nvim-autopairs/issues/405#issuecomment-1762761811

**Comment by j-barnak** [comment]
Thanks for everything. I'll test [this](https://github.com/windwp/nvim-autopairs/issues/405#issuecomment-1762761811) to see if it works well. I'll also test #407 as well!

Thanks 

>which would make it possible for the <> pairs to work on their own
>but i think it's way too overkill tho
>not gonna stop me for making it in case anyone is curious

That'd be awesome if you got this to work!

**Comment by j-barnak** [comment]
Just having the following:

```lua

local conds = require("nvim-autopairs.conds")
local rule = require("nvim-autopairs.rule")
rule("<", ">", "cpp"):with_pair(conds.none()):with_move(conds.done()) 
```
doesn't seem to work?

**Comment by j-barnak** [comment]
@Sam-programs A small correction. It seems that `unpack` was deprecated in lua 5.4. Changing it to `table.unpack` fixes it.

**Comment by Sam-programs** [comment]
i almost got the function working
just losing my sanity with lua 1 indexing rn

**Comment by Sam-programs** [comment]
https://github.com/windwp/nvim-autopairs/issues/405#issuecomment-1762973584
i am not sure what isn't working it shouldn't place a pair in that case
i haven't done too much testing but this huge snippet should fix everything
```lua
local is_tempalate = function()
   local line = vim.api.nvim_get_current_line()
   local r, c = unpack(vim.api.nvim_win_get_cursor(0))
   if not (vim.o.filetype == "cpp" or vim.o.filetype == "c") then
      line = line:sub(1, c) .. '<' .. line:sub(c + 1)
      vim.api.nvim_set_current_line(line)
      vim.api.nvim_win_set_cursor(0, { r, c + 1 })
      return
   end

   if vim.fn.match({ line }, 'template') == 0 then
      -- c - 1 = 2 chars before the cursor
      line = line:sub(1, c) .. '<>' .. line:sub(c + 1)
      vim.api.nvim_set_current_line(line)
      vim.api.nvim_win_set_cursor(0, { r, c + 1 })
      return
   end

   if vim.fn.match({ line }, '#include') == 0 then
      line = line:sub(1, c) .. '<>' .. line:sub(c + 1)
      if line:sub(c, c) ~=  ' ' then
         line = line:sub(1, c) .. ' ' .. line:sub(c + 1)
         c = c + 1
      end
      vim.api.nvim_set_current_line(line)
      vim.api.nvim_win_set_cursor(0, { r, c + 1 })
      return
   end

   -- c is 1 before the cursor 
   line = line:sub(1, c) .. '<' .. line:sub(c + 1)
   vim.api.nvim_set_current_line(line)
   vim.api.nvim_win_set_cursor(0, { r, c + 1 })
   vim.cmd("redraw")    -- redraw to add the first <
   -- since we added < the lsp can detect it 
   local old_handler = vim.lsp.handlers["textDocument/signatureHelp"]
   vim.lsp.handlers["textDocument/signatureHelp"] = function(_, info)
      if info then
         local functionsig = info.signatures[1].label
         if vim.fn.match({ functionsig }, '^\\w\\+<') == 0 then
            -- c + 1 is after including the openning pair very shady code lol
            vim.api.nvim_set_current_line(line:sub(0, c + 1) .. '>' .. line:sub(c + 2))
         end
      end
   end
   vim.lsp.buf.signature_help()
   vim.lsp.handlers["textDocument/signatureHelp"] = old_handler
end

npairs.add_rules({
   rule("<",">"):
   with_pair(cond.none()):
   with_move(cond.done()):
   use_key('<kPoint>') -- a random key so it doesn't map < 
})

vim.keymap.set("i", "<", is_tempalate)
```

**Comment by Sam-programs** [comment]
@j-barnak

**Comment by Sam-programs** [comment]
> sadly i couldn't check if cpp_sort_cmp was already in the comparator list  
that's also fixed in the pr with a global variable

**Comment by Sam-programs** [comment]
DAMN IT COUT BROKE AGAIN

**Comment by Sam-programs** [comment]
changing the info if statement to check everything fixes it
```lua
if info and info.signatures and info.signatures[1] and info.signatures.label then
```

**Comment by j-barnak** [comment]
Replacing 

```lua
local r, c = unpack(vim.api.nvim_win_get_cursor(0))
```

with

@Sam-programs 

```lua
local r, c = table.unpack(vim.api.nvim_win_get_cursor(0))
```

yields the following error

```
E5108: Error executing lua: /home/jared/.config/nvim/lua/plugins/pair.lua:19: attempt to call upvalue 'unpack' (a nil value)
stack traceback:
        /home/jared/.config/nvim/lua/plugins/pair.lua:19: in function </home/jared/.config/nvim/lua/plugins/pair.lua:17>
```

I opted to switch `unpack` with `table.unpack` because I got an error say that `unpack` was deprecated.

**Comment by j-barnak** [comment]
@Sam-programs 

And just noting,

```lua
npairs.add_rules({
   rule("<",">"):
   with_pair(cond.none()):
   with_move(cond.done()):
   use_key('<kPoint>') -- a random key so it doesn't map < 
})
```

The above doesn't allow you to escape the end pair `>`.

**Comment by Sam-programs** [comment]
oh i didn't notice the that

**Comment by Sam-programs** [comment]
i have no clue why but this works
```lua
npairs.add_rules({
   rule("<",">"):
   with_pair(cond.none()):
   with_move(cond.done()):
   use_key('>') -- a random key so it doesn't map < 
})
```

**Comment by Sam-programs** [comment]
@j-barnak 
use this if u really care about that warning
```lua
local unpack = unpack or table.unpack
```

**Comment by j-barnak** [comment]
With regards to this

```lua
npairs.add_rules({
   rule("<",">"):
   with_pair(cond.none()):
   with_move(cond.done()):
   use_key('>') -- a random key so it doesn't map < 
})
```

I *think* this works because the `move` is triggered when the pair is completed and `use_key` triggers the completion. I'll let you know if this runs into errors.

**Comment by Sam-programs** [comment]
i thought it meant pair start trigger
because that key is used in the completion to add the () pair
https://github.com/windwp/nvim-autopairs/blob/master/lua/nvim-autopairs/completion/handlers.lua#L52

**Comment by j-barnak** [comment]
@Sam-programs

I've done some testing with [this snippet](https://github.com/windwp/nvim-autopairs/issues/405#issuecomment-1762992541) and it's been working great.

Anything you want to add or should I close the issue? Is there anything you want to add or should I wait until #407 gets merged?

**Comment by Sam-programs** [comment]
@j-barnak  good to know that snippet works ,i am curious to why u prefer it over the cmp snippet https://github.com/windwp/nvim-autopairs/issues/405#issuecomment-1762690355
or just why u wanted it because it feels like it's worse than cmp's

**Comment by j-barnak** [comment]
@Sam-programs 

> i am curious to why u prefer it over the cmp snippet

I was under the impression that [this](https://github.com/windwp/nvim-autopairs/issues/405#issuecomment-1762992541) was better

And personally

```lua
local npairs = require("nvim-autopairs")
local cmp = require("cmp")

npairs.setup(opts)

local function template_on_confirm(event)
  if not (vim.o.filetype == "c" or vim.o.filetype == "cpp") then
    return
  end
  local entry = event.entry
  local item = entry:get_completion_item()
  local _, c = unpack(vim.api.nvim_win_get_cursor(0))
  local line = vim.api.nvim_get_current_line()
  local pairs = ""
  local functionsig = item.label
  if
    line:sub(c, c) ~= ">"
    and (functionsig:sub(#functionsig, #functionsig) == ">" or functionsig == " template")
  then
    if functionsig:sub(2, 8) == "include" then
      pairs = " "
    end
    pairs = pairs .. "<>"
    pairs = vim.api.nvim_replace_termcodes(pairs .. "<left>", true, false, true)
    vim.api.nvim_feedkeys(pairs, "n", false)
  end
end

cmp.event:on("confirm_done", template_on_confirm)
```

This didn't work for me.

**Comment by j-barnak** [comment]
@Sam-programs 

> because i have 1 hotkey that moves the cursor 1 column
> alt-l `<A-l>`

Mind sharing this hotkey?

**Comment by Sam-programs** [comment]
@j-barnak https://github.com/windwp/nvim-autopairs/issues/405#issuecomment-1763449711
> ~This didn't work for me~

phew the pr is safe to merge
maybe you were messing the sorter here https://github.com/windwp/nvim-autopairs/issues/405#issuecomment-1762761811
without the sorter it sometimes doesn't add the <> pairs 
add the last `cmp.setup` after your own `cmp.setup`
or you can just wait until the pr gets merged

> Mind sharing this hotkey?

damn you learnt vim properly and didn't use the arrow keys unlike me lol
```lua
vim.keymap.set({ "i", "c" }, "<A-l>", "<right>") -- the c mode is command mode
```

**Comment by j-barnak** [comment]
@Sam-programs Thanks! You might also want to add to your config

```lua
      npairs.add_rules({
        rule("{", "}", "cpp"):with_pair(ts_conds.is_ts_node({ "namespace_definition" })),
      })
```

because

```lua
local cpp_cond = function ()
   local line = vim.api.nvim_get_current_line()
   -- match for() while() functions()
   -- the regex won't work if 'magic' is not set
 
   local pattern = '^.*(.*)'

   if vim.fn.match({ line }, pattern) == 0 then
      return false
   end
end

npairs.add_rules({
   rule("{", "};", "cpp"):with_pair(
   cpp_cond
   ),
})
```

triggers`{};` when you type namespace.

**Comment by Sam-programs** [comment]
thanks @j-barnak 
i actually thought it was required there
i also noticed that the cmp autocomplete doesn't detect static_cast and other kinds of casts
the thing is i am having a hard time making it not conflict with the existing pair adder for functions
i got a work around by making it reverse the cursor position for now
https://github.com/windwp/nvim-autopairs/issues/405#issuecomment-1762690355

u will need to add the template_on_confirm to cmp's events after autopairs for functions
```lua
         cmp.event:on("confirm_done",cmp_autopairs.on_confirm_done())
         cmp.event:on('confirm_done', template_on_confirm)
```
but now template_on_confirm sadly doesn't work on it's own

**Comment by j-barnak** [comment]
@Sam-programs Thanks!

I actually prefer [this](https://github.com/windwp/nvim-autopairs/issues/405#issuecomment-1762992541) variation. How would you make casts work with that rule?

Thank you so much! You've been awesome.

**Comment by Sam-programs** [comment]
i am really not sure how to make it work as i won't have access to cmp's entry
but maybe i could find a lsp method to detect that
i made it look if the last few characters are cast to detect casts tho
[updated](https://github.com/windwp/nvim-autopairs/issues/405#issuecomment-1762992541)

that might conflict with a variable ending with cast but i don't have that much time to read/test the lsp requests for now

**Comment by Sam-programs** [comment]
@j-barnak mention lol

**Comment by j-barnak** [comment]
@Sam-programs That works! My one and last problem is that I when I mix these two

```lua
local cpp_cond = function ()
   local line = vim.api.nvim_get_current_line()
   -- match for() while() functions()
   -- the regex won't work if 'magic' is not set
 
   local pattern = '^.*(.*)'

   if vim.fn.match({ line }, pattern) == 0 then
      return false
   end
end

npairs.add_rules({
   rule("{", "};", "cpp"):with_pair(
   cpp_cond
   ),
})

pairs.add_rules({
  rule("{", "}", "cpp"):with_pair(ts_conds.is_ts_node({ "namespace_identifier" })),
 })
```

The `cpp_cond` rule gets overwritten and no longer works.

**Comment by j-barnak** [comment]
@Sam-programs I also tried this

```
      npairs.add_rules({
        rule("<", ">"):with_pair(cond.none()):with_move(cond.done()):use_key(">"),
        rule("{", "};", { "cpp", "c" }):with_pair(cpp_cond),
        rule("{", "}", "cpp"):with_pair(ts_conds.is_ts_node({ "namespace_identifier" })),
      })
```

**Comment by Sam-programs** [comment]
don't use `ts_conds` it's useless most of the time
it checks the node at the cursor which in insert mode is almost always pointing at the wrong thing
```cpp
translation_unit node
namespace|
```
i matched the line with namespace which should do it
```lua
local cpp_cond = function()
   local line = vim.api.nvim_get_current_line()
   -- match for() while() functions()

   local pattern = '\\m^.*(.*)'

   if vim.fn.match(line, pattern) ~= -1 or
      vim.fn.match(line,"namespace") ~= -1
   then
      return false
   end
end

local npairs = require("nvim-autopairs")
npairs.setup{}
local rule = require("nvim-autopairs.rule")
npairs.add_rules({
   rule("{", "};", { "cpp", "c" }):with_pair(cpp_cond),
})
```

**Comment by j-barnak** [comment]
@Sam-programs Thanks! I really appreciate it. I'm trying to tweak the above line so that it only returns `{};` when the current or above line contains `struct` or `class`. I think it makes a lot more sense considering that's really the only time I want those pairs. I changed `cpp_cond` to `struct_or_class`

I want the default `{` pair to be `{}`, but with

```lua
rule("{", "};", { "cpp", "c" }):with_pair(struct_or_class),
```

It seems to default to `{};` even when `struct_or_class` doesn't return true.

```lua
local function get_relative_line(offset)
  local line = vim.api.nvim_win_get_cursor(0)[1]
  local target = line + offset
  return vim.api.nvim_buf_get_lines(0, target - 1, target, false)[1]
end

local struct_or_class = function()
  local line = get_relative_line(0)
  local previous_line = get_relative_line(-1)

  if vim.fn.match(line, "struct") ~= -1 or vim.fn.match(line, "class") ~= -1 then
    return true
  end

  if vim.fn.match(previous_line, "struct") ~= -1 or vim.fn.match(previous_line, "class") ~= -1 then
    return true
  end
end

local npairs = require("nvim-autopairs")
local  rule = require("nvim-autopairs.rule")
local cond = require("nvim-autopairs.conds")

npairs.setup(opts)

npairs.add_rules({
rule("{", "};", { "cpp", "c" }):with_pair(struct_or_class),
})
```
