### ISSUE TITLE
It crashed when select function or method item in python

### ISSUE THREAD

**Issue by 3Xpl0it3r** [windwp/nvim-autopairs#410]
### Description

It crashed when select function or method item in python

### Mapping <cr> bug

1.If you report a bug about indent. Please remember that plugin doesn't do anything about indent.
  It just trigger the indent of your vim config so if you have wrong indent config then it will do wrong indent.
  You can check by select a block of code and press `==`
2. provide result of command `:verbose imap <cr>`.

### Steps to reproduce

&emsp;like blow when input `fp.readall` ,then press enter key, it crashed
<img width="684" alt="image" src="https://github.com/windwp/nvim-autopairs/assets/62287907/aa85765d-f2e1-4727-bd77-69c0ec6448c6">

&emsp;crash message
<img width="1439" alt="image" src="https://github.com/windwp/nvim-autopairs/assets/62287907/f9544401-4da2-4950-bb0e-a96adb207c9e">

### Minimal config

```Lua
local function config_autopairs(config)
    config.setup({
        check_ts = false,
        ts_config = {
            lua = { "string", "source" },
        },
        disable_filetype = { "TelescopePrompt", "spectre_panel" },
        fast_wrap = {
            map = "<M-e>",
            chars = { "{", "[", "(", '"', "'" },
            pattern = string.gsub([[ [%'%"%)%>%]%)%}%,] ]], "%s+", ""),
            offset = 0,
            end_key = "$",
            keys = "qwertyuiopzxcvbnmasdfghjkl",
            check_comma = true,
            highlight = "PmenuSel",
            highlight_grey = "LineNr",
        },
    })

    local cmp_autopairs = require("nvim-autopairs.completion.cmp")
    local cmp_status_ok, cmp = pcall(require, "cmp")
    if not cmp_status_ok then
        return
    end
    cmp.event:on("confirm_done", cmp_autopairs.on_confirm_done({ map_char = { tex = "" } }))
end
```

**Comment by dvrkoo** [comment]
I'm getting the same issue with python code, to reproduce open a .py file and select a function with default values,  if i remove the cmp support it stops
