### ISSUE TITLE
Escape sequence 

### ISSUE THREAD

**Issue by zach-is-my-name** [windwp/nvim-autopairs#418]
I'm not an effective lua coder so I'm biased, but I don't believe you should have to know lua very much beyond what it takes to get a plugin installed, thus I don't believe the user should have to learn to use rule system simply to disable the plugin for a one-off non-autopair.   

I would like a mapping made available to disable autopair for one press of a pair key.  

To be precise, what I'm humbling requesting is the ability to do this:
```
--lazy.nvim spec file
 return {
    'windwp/nvim-autopairs',
    event = "InsertEnter",
    opts = {}, -- this is equalent to setup({}),
    keys = {
      { "m-E", "<cmd>lua require('nvim-autopairs').escape{}<cr>", desc = "Escape" },
}
```
```

--In editor
 (   ->    ()
 <m-E>(   ->   (
```
I'm envisioning this working like insert mode's `<C-o>`...
 
I've considered the ruleset system in effect and I respect it for people who have the time and ability to configure it.  Unfortunately I don't.  I would just very much like to use the very well-designed default config with a simple option to override the pair assigned key for one press 

Thanks for your work on this, I'm enjoying it very much.

**Comment by windwp** [comment]
vim has a default key to skip remap is ctrl+q or ctrl+v.
