### ISSUE TITLE
Skip Jumping to Next Bracket

### ISSUE THREAD

**Issue by cenk1cenk2** [windwp/nvim-autopairs#42]
Hello @windwp ,

Initially, thank you for maintaining so many beautiful plugins for neovim.

Is there a way to disable the jump mode with a flag that I am missing even though many of the community likes it? 

Current behavior:
```
Before                  Input         After
------------------------------------
((someword|)         )               ((someword)|
```
The one I wish for:
```
Before                   Input         After
------------------------------------
((someword |)         )               ((someword)|)
```

**Comment by windwp** [comment]
hi if you want to remove jump for square bracket you can use

```
npairs.remove_rule(''(")

```
then add the rule you want. 

you can check file lua/nvim-autopairs/rules/basic.lua and remove condition move_right

if you want to disable all jump mode for all rule  npairs.clear_rules and add rule again

**Comment by cenk1cenk2** [comment]
oh thank you for the reply. I guess I missed this one will check oit immediately. very grateful.

**Comment by windwp** [comment]
Hi i just add a global option to disable move right for all rule
``` lua
setup({
enable_moveright = false
})
```

**Comment by cenk1cenk2** [comment]
That is just amazing news. I can not thank you enough. Appriciate the time you took into this.
