### ISSUE TITLE
Do not use global variables (`MPairs`)

### ISSUE THREAD

**Issue by JosefLitos** [windwp/nvim-autopairs#425]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when my global namespace gets cluttered with unnecessary variables.

**Describe the solution you'd like**
Since compe is long archived and nothing else uses that global var, just remove https://github.com/windwp/nvim-autopairs/blob/master/lua/nvim-autopairs.lua#L662

**Comment by bew** [comment]
You mean
https://github.com/windwp/nvim-autopairs/blob/096d0baecc34f6c5d8a6dd25851e9d5ad338209b/lua/nvim-autopairs.lua#L663

**Comment by JosefLitos** [comment]
yes, it seems I misclicked when selecting the line.
