### ISSUE TITLE
Lua module not found

### ISSUE THREAD

**Issue by patreeceeo** [windwp/nvim-autopairs#428]
### Description

when I include these lines in my rc file 

```
lua << EOF
require("nvim-autopairs").setup {}
EOF
```

And start neovim I get an error that the lua module couldn't be found. If I do not include those lines then the plugin apparently does nothing, it's as if I don't have it installed at all.

I'm using neovim 0.9.5, still using vimscript for my RC file, and I installed the plugin via Plug.

Thanks!

still using vimscript

### Mapping <cr> bug

1.If you report a bug about indent. Please remember that plugin doesn't do anything about indent.
  It just trigger the indent of your vim config so if you have wrong indent config then it will do wrong indent.
  You can check by select a block of code and press `==`
2. provide result of command `:verbose imap <cr>`.

### Steps to reproduce

Pretty simple. I added those setup lines to the very top of my RC file so nothing else should be interfering, then restarted neovim.

### Minimal config

```Lua
vim.cmd.source("~/.config/nvim/init.vim")

-- init.vim:
call plug#begin('~/.config/nvim/plugged')
Plug 'windwp/nvim-autopairs'

lua << EOF
require("nvim-autopairs").setup {}
EOF
call plug#end()
```

**Comment by windwp** [comment]
maybe move that setup line to after  plug#end()
