### ISSUE TITLE
The plugin requires tree-sitter

### ISSUE THREAD

**Issue by Shatur95** [windwp/nvim-autopairs#43]
If Treesitter is not installed, then the plugin gives an error:

![изображение](https://user-images.githubusercontent.com/22453358/115766704-eff03300-a3b0-11eb-9d1b-fd431216ce79.png)

Is it possible to turn this dependency into optional? I have a minimal configuration that allows me to use Neovim to edit text fields in browser (using [Firenvim](https://github.com/glacambre/firenvim)) and do not need Treesitter for it.

**Comment by windwp** [comment]
I fix it
