### ISSUE TITLE
Neovim freezes completely when triggering this plugin 

### ISSUE THREAD

**Issue by richin13** [windwp/nvim-autopairs#430]
### Description

Commit https://github.com/windwp/nvim-autopairs/commit/2e8a10c5fc0dcaf8296a5f1a7077efcd37065cc8 introduced a bug where triggering the plugin completely freezes neovim

### Mapping <cr> bug

1.If you report a bug about indent. Please remember that plugin doesn't do anything about indent.
  It just trigger the indent of your vim config so if you have wrong indent config then it will do wrong indent.
  You can check by select a block of code and press `==`
2. provide result of command `:verbose imap <cr>`.

### Steps to reproduce

Pull the latest version, then do:

`Word(|)`

or 

```
public function foo()
{<ENTER>
```

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'windwp/nvim-autopairs',
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('nvim-autopairs').setup()
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing nvim-autopairs and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by windwp** [comment]
what is your neovim version?

**Comment by JosefLitos** [comment]
I tried with 0.8.3, 0.9.2 and 0.9.5, all worked (I downgraded only neovim). Though I just guessed the filetype to use (js). Since the editor freezes or crashes, I would assume this is an issue of neovim, not this plugin, since it behaves differently between neovim versions.

**Comment by sandersantema** [comment]
This is also happening on the latest neovim master, which is https://github.com/neovim/neovim/commit/cc15ba212c7992c3f3aae8b90962862572b21e83 at the time of writing. It seems to happen for any pair which autopair is configured for, it can be reproduced as follows:

1. type a pair for which autopair is configured e.g. `{}`
2. press enter
3. neovim hangs

If anything is inserted between the pair before pressing enter neovim does not hang.

**Comment by sandersantema** [comment]
> There was an nvim PR that was about issues with requiring/using plugins with dashed names which is what probably causes this issue.

Although I've got no knowledge of that particular issue this seems unlikely to me, seeing as I've got the following plugins with dashes in their names installed which cause no error:
`cmp-buffer, cmp-dap, cmp-nvim-lsp, cmp-nvim-lsp-signature-help, cmp-omni, cmp-path, cmp-vimtex, haskell-tools.nvim, haskell-vim, kmonad-vim, null-ls-embedded, null-ls.nvim, nvim-cmp, nvim-dap, nvim-dap-python, nvim-dap-ui, nvim-lspconfig, nvim-treesitter, nvim-web-devicons, todo-comments.nvim, vim-commentary, vim-cool, vim-dadbod, vim-dadbod-completion, vim-dadbod-ui, vim-endwise, vim-eunuch, vim-just, vim-mma, vim-obsession, vim-rsi, vim-sandwich, vim-startuptime, vim-tmux-navigator, vim-unimpaired, vim-visual-increment, which-key.nvim`

**Comment by sandersantema** [comment]
This [line](https://github.com/windwp/nvim-autopairs/blob/2e8a10c5fc0dcaf8296a5f1a7077efcd37065cc8/lua/nvim-autopairs.lua#L584) seems to cause the error.

Specifically the inner function call `rule:get_map_cr({ rule = rule, line = line, color = col, bufnr = bufnr })` as `return utils.esc('<cr>')` for example doesn't cause a hang.

**Comment by JosefLitos** [comment]
I read about this hyphen issue in nvim-treesitter-textobjects#343, but never experienced it myself. It could be related to neovim#17209, but that's over 2 years old by now.

**Comment by richin13** [comment]
I'm on `v0.10.0-dev-2341+g929e1b7f1`

**Comment by stancl** [comment]
I've just updated to 0.9.5 and the bug still persists. Tested it inside/outside tmux, in different terminal emulators in the unlikely case that this could have any effect (considering that it's difficult for some people to reproduce), but no, it happens for me regardless of how I run neovim.

**Comment by richin13** [comment]
> I've just updated to 0.9.5 and the bug still persists. Tested it inside/outside tmux, in different terminal emulators in the unlikely case that this could have any effect (considering that it's difficult for some people to reproduce), but no, it happens for me regardless of how I run neovim.

Do you happen to use this too https://github.com/tpope/vim-endwise? Just realized combining this plugin and `vim-endwise` causes the freeze for me 💀

**Comment by richin13** [comment]
> > There was an nvim PR that was about issues with requiring/using plugins with dashed names which is what probably causes this issue.
> 
> Although I've got no knowledge of that particular issue this seems unlikely to me, seeing as I've got the following plugins with dashes in their names installed which cause no error: `cmp-buffer, cmp-dap, cmp-nvim-lsp, cmp-nvim-lsp-signature-help, cmp-omni, cmp-path, cmp-vimtex, haskell-tools.nvim, haskell-vim, kmonad-vim, null-ls-embedded, null-ls.nvim, nvim-cmp, nvim-dap, nvim-dap-python, nvim-dap-ui, nvim-lspconfig, nvim-treesitter, nvim-web-devicons, todo-comments.nvim, vim-commentary, vim-cool, vim-dadbod, vim-dadbod-completion, vim-dadbod-ui, vim-endwise, vim-eunuch, vim-just, vim-mma, vim-obsession, vim-rsi, vim-sandwich, vim-startuptime, vim-tmux-navigator, vim-unimpaired, vim-visual-increment, which-key.nvim`
> 
> EDIT: glancing over the commit in question I think there might be some interplay of the dashed name stuff I'm not aware of, which makes me think my thought of the cause not being related to it might be wrong.

Looks like you also have vim-endwise 👀

**Comment by stancl** [comment]
I do not, but I was thinking if some combination of plugins could be the cause here.

This should be my full plugin list:
```
LuaSnip bufdelete.nvim bufferline.nvim cmp-nvim-lsp cmp-nvim-lsp-signature-help cmp-path
cmp_luasnip github-nvim-theme gitsigns.nvim lspkind-nvim lualine.nvim mason-lspconfig.nvim
mason-null-ls.nvim mason.nvim neoscroll.nvim none-ls.nvim nvim-autopairs nvim-cmp
nvim-lspconfig nvim-tree.lua nvim-treesitter nvim-treesitter-textobjects nvim-ts-context-commentstring nvim-web-devicons
packer.nvim phpactor (not loaded) plenary.nvim rustaceanvim schemastore.nvim splitjoin.vim
telescope-fzf-native.nvim telescope-live-grep-args.nvim telescope.nvim tree-sitter-astro typescript-tools.nvim vim-commentary
vim-eunuch vim-floaterm vim-fugitive vim-heritage vim-lastplace vim-pasta
vim-polyglot vim-repeat vim-rhubarb vim-rooter vim-sleuth vim-surround
vim-test vim-textobj-user vim-textobj-xmlattr vim-tmux-navigator vim-unimpaired vim-visual-multi vim-visual-star-search
```

**Comment by richin13** [comment]
> I do not, but I was thinking if some combination of plugins could be the cause here.
> 
> This should be my full plugin list:
> 
> ```
> LuaSnip bufdelete.nvim bufferline.nvim cmp-nvim-lsp cmp-nvim-lsp-signature-help cmp-path
> cmp_luasnip github-nvim-theme gitsigns.nvim lspkind-nvim lualine.nvim mason-lspconfig.nvim
> mason-null-ls.nvim mason.nvim neoscroll.nvim none-ls.nvim nvim-autopairs nvim-cmp
> nvim-lspconfig nvim-tree.lua nvim-treesitter nvim-treesitter-textobjects nvim-ts-context-commentstring nvim-web-devicons
> packer.nvim phpactor (not loaded) plenary.nvim rustaceanvim schemastore.nvim splitjoin.vim
> telescope-fzf-native.nvim telescope-live-grep-args.nvim telescope.nvim tree-sitter-astro typescript-tools.nvim vim-commentary
> vim-eunuch vim-floaterm vim-fugitive vim-heritage vim-lastplace vim-pasta
> vim-polyglot vim-repeat vim-rhubarb vim-rooter vim-sleuth vim-surround
> vim-test vim-textobj-user vim-textobj-xmlattr vim-tmux-navigator vim-unimpaired vim-visual-multi vim-visual-star-search
> ```

That's most likely the case, I started disabling them all by groups until the issue stopped and then enabled them back again until I found it was `vim-endwise`

**Comment by stancl** [comment]
And since I don't use that plugin, but also encounter the issue, it seems that the change in the last commit has introduced some general compatibility issues, for instance with `vim-endwise` as well as some (so far unknown) plugin(s) that I'm using?

The above list is (reformatted) output of `:PackerStatus`, so I think it should be all plugins that I use.

**Comment by richin13** [comment]
Thank you @windwp ! Works like a charm now 💯
