### ISSUE TITLE
Functionality to disable default pair in certain situations

### ISSUE THREAD

**Issue by echasnovski** [windwp/nvim-autopairs#44]
I've read both documentation and some plugin code, but couldn't find the way to disable a default pair in certain situation.

For example, my use case is to disable adding second `"` inside '.vim' files when it is intended to be a comment string (for example, when there is only white space to the left of the first `"`). I even tried "more simple" approach to completely disable `"`-`"` pair in '.vim' files, but couldn't figure out a way to do that.

My first impression was to use this: `npairs.add_rules({Rule('"', '', 'vim')})`. It didn't work, although it works if I try to add new pair (for example, with `npairs.add_rules({Rule('^', '^', 'vim')})`).

**Comment by windwp** [comment]
you need to remove a default rule first.

```
npair.remove_rule('"')
```

you get a default rule of " on file
lua/nvim-autopairs/rules/basic.lua

then add more condition to check filetype  vim.


``` lua
Rule('"",'"')
......
  :with_pair(function() 
    if vim.bo.filetype == 'vim' then
       return false
   end
  )
```

**Comment by windwp** [comment]
Hi  i just add a new function get_rule
you can do this to modify default rule without remove it
``` lua
npairs.get_rule('"')
 :with_pair(function() 
    if vim.bo.filetype == 'vim' then
       return false
   end
```

**Comment by echasnovski** [comment]
With #47 merged, this might be considered solved. Thanks!
