### ISSUE TITLE
Adding spacing rules?

### ISSUE THREAD

**Issue by DarwinSenior** [windwp/nvim-autopairs#45]
Do you think it is suitable to add the following rules to basic.lua?

```lua
Rule(' ', ' '):with_pair(function (opts)
  local pair = opts.line:sub(opts.col, opts.col+2)
  return vim.tbl_contains({'()', '[]', '{}'}, pair)
end)
```

So we have the following
before | insert | after
---------|---------|--------
`(\|)` | `( \|)` | `( \| )`
`{\|}` | `{ \|}` | `{ \| }`
`[\|]` | `[ \|]` | `[ \| ]`

**Comment by windwp** [comment]
Nice idea.

**Comment by zetashift** [comment]
Currently using this! I really like it for JS imports, but is it correct this snippet doesn't include nested brackets? E.g.

```
{ | }      -- works fine, but now add in another `{`
{ {|} }    -- alright so far, now if we press `space` again:
{ { |} }  -- didn't auto-space it in :(
```

**Comment by windwp** [comment]
````
Rule(' ', ' '):with_pair(function (opts)
  local pair = opts.line:sub(opts.col, opts.col+2)   -- change to +1
  return vim.tbl_contains({'()', '[]', '{}'}, pair)
end)

```

**Comment by zetashift** [comment]
Thank you and thank you for this great plugin!!

**Comment by rebuilt** [comment]
Thanks!
