### ISSUE TITLE
How to get indentation too?

### ISSUE THREAD

**Issue by gitpubber** [windwp/nvim-autopairs#46]
I am newbie to this plugin. So, without nvim-autopairs,it works like this.

    int functionname() {
        |

with , nvim-autopairs , i get this,

    int functionname() {
    |}

I wanted this.

    int functionname() {
        |
    }

Please help me. I want closing brace to be on next line

**Comment by windwp** [comment]
check readme about mapping <cr>.

if it still not working  download your language pack from plugin or enable treesitter indent

https://github.com/windwp/nvim-autopairs/issues/24
