### ISSUE TITLE
Auto center feature request

### ISSUE THREAD

**Issue by LZDQ** [windwp/nvim-autopairs#460]
I switched from [jiangmiao/auto-pairs](https://github.com/jiangmiao/auto-pairs). Now I miss the feature of the original plugin: automatically center the current line (zz) when inserting a new pair of curly brackets and hit enter if the current line is not within 1/3 range of the screen.

I tried to map  `<CR>` myself but somehow the script doesn't work. I checked the source code, while using expr `"v:lua.require'nvim-autopairs'.completion_confirm()"` works, calling it from lua `require('nvim-autopairs').autopairs_cr()` does nothing and I don't know why. Now I cannot call it from lua and I can't write a custom script.

Anyone help me write a script or add this feature please

**Comment by windwp** [comment]
I think you want to modify that mapping. currently it don't have way to do that for all rule
maybe you can use function `replace_map_cr`  to modify it but it only work on one specify rule.

https://github.com/windwp/nvim-autopairs/blob/c15de7e7981f1111642e7e53799e1211d4606cb9/lua/nvim-autopairs/rule.lua#L117

**Comment by LZDQ** [comment]
Thanks for your reply. I figured out how to setup my custom `<CR>` now. I should use `vim.api.nvim_feedkeys` to feed the escaped return sequence of `autopairs_cr` (wrapped by `completion_confirm`).

```lua
-- vim.api.nvim_set_keymap('i', '<CR>', "v:lua.require'nvim-autopairs'.completion_confirm()", { expr = true, noremap = true })
vim.keymap.set('i', '<CR>', function()
	-- autopairs
	vim.api.nvim_feedkeys(autopairs.completion_confirm(), 'n', false)

	-- center if not within range
	local total_lines = vim.api.nvim_win_get_height(0)
	local current_line = vim.fn.winline()
	local l = 0
	local r = math.floor(total_lines * 2 / 3)

	if current_line < l or current_line > r then
		-- Center the current line
		vim.cmd('normal! zz')
	end
end, { noremap = true })

```
