### ISSUE TITLE
Alternative to closetag?

### ISSUE THREAD

**Issue by Mte90** [windwp/nvim-autopairs#48]
Reading the readme to me is not clear if support html as example.
Right now I use https://github.com/docunext/closetag.vim but I am not sure if this plugin can be an alternative (of course this one support also other things).

Maybe a language list of supported so I don't need to check all the rules available if are good for the one I use it?

**Comment by windwp** [comment]
https://github.com/windwp/nvim-ts-autotag
Try this it is better than closetag

**Comment by Mte90** [comment]
Thanks!
