### ISSUE TITLE
Pairs associated to more than a single character

### ISSUE THREAD

**Issue by coxackie** [windwp/nvim-autopairs#5]
First of all, thanks for creating this nifty plugin.

 I am trying to set up the pair `['``'] = "''"`. These is how `LaTeX` understands double quotation. The pairing partially works, but instead of getting ``|'' as it should, I get ``'|'. The cursor enters between the second single quotes. This may be due to the previous default pairing `["'"] = "'"`, but I would hope that autopairs is smarter than that.

 On the same topic, for LaTeX purposes I would also like to setup paring like `\(` is paired to `\)` - this is math mode. I tried `['\\('] = '\\)'`, it is does not seem to work. The single space does not work either. Any ideas there?

**Comment by windwp** [comment]
sorry about that my plugin is not support 2 character in pair. I should add this to readme.

I want to keep my plugin simple and minimal. 
Currently i can't find a good way to do that.

**Comment by coxackie** [comment]
Ok, I understand that. Let's say then that I just set up the pair ['`'] = "'" - this way, I can press twice `` in a row and it in fact gives me ''. No problem. But, here is some weirdness.

 With only one press of `, I get `|', and pressing ' takes me out `'|. All good. 

Now, if I press ``, I get ``|''. If I press ', I would expect I go to ``'|', and that one more press of ' would take me to ``''|. Instead, when I am here ``|'' and I press ' I get ``'|'', and then consecutive pressing ' takes me out of the interior; but now there are three ticks ``'''| that will remain. I thought this is related to the fact that the mapping ["'"] = "'" is also there, but when I removed it it got worse: it would just add further ticks inside the snip, without ever trying to escape.

 I would expect to just exit from the last pairing made. Do you think this is something that can be addressed? Can the plugin know the nesting nature of the pairings?

**Comment by windwp** [comment]
Hi  
the move cursor function is only work with pairs have same character and currently it only support pair with " or '.
even if i try to add your character ` then it still not working like you want .
first  when you type 
``` 
` => `<cursor>' 
then if you type ` it will move out side to and it not will add a second pairs like you want
`<cursor>' => `'<cursor>

```

``` lua
                  ['`'] = "'",
                  ["'"] = "'",
```
some tricky to mix about 2 pairs is not a right solution is support a pairs with 2 character .



https://user-images.githubusercontent.com/7578110/104533034-24cb4c00-5644-11eb-8b2e-a98ff733d77f.mp4

why you not use a snippet for this case. you can add a snippet to jump to a middle then press tab to jump out side.

I use vsnippet but i think you can use ultisnippet.

**Comment by coxackie** [comment]
ok, thanks a lot, I will take your advice and use snippets. Closing this.
