### ISSUE TITLE
Endwise rules incorrect indents

### ISSUE THREAD

**Issue by jonatan-branting** [windwp/nvim-autopairs#50]
There seems to be an issue with indent-levels for endwise-rules:

Example rules: 
```
npairs.clear_rules()
npairs.add_rules({
  endwise('then$', 'end', 'lua', nil)
})
```
Before: 
![image](https://user-images.githubusercontent.com/985954/116937267-468b2600-ac69-11eb-91ce-4517abf96d8b.png)

After:
![image](https://user-images.githubusercontent.com/985954/116937298-5440ab80-ac69-11eb-8493-e14cffce7212.png)

It seems to consistently indent the matching `end` one level too little.

**Comment by rebuilt** [comment]
I can't solve your problem but I'm curious about your endwise rules.  Can I see your config?  I've been trying to get endwise to work without success.

**Comment by windwp** [comment]
@jonatan-branting  hi i update this to fix indent.

@rebuilt  
you can try  lua endwise config with treesitter


``` lua
require('nvim-treesitter.configs').setup {
    autopairs = {enable = true}
}
npairs.setup({
    check_ts = true
})
npairs.add_rules(require('nvim-autopairs.rules.endwise-lua'))


```
