### ISSUE TITLE
dot command doesn't repeat the pairs

### ISSUE THREAD

**Issue by argapost** [windwp/nvim-autopairs#51]
When I am in insert mode, and I write something which has some pairs: `(test)`

And then press the `.` command to repeat. It will only repeat what is inside the pair: `test` without the parenthesis.

Is this the desired behaviour? Have I messed up something in my config? Thanks in advance.

**Comment by windwp** [comment]
currently it is not support repeat.

**Comment by argapost** [comment]
Ok, thanks!
