### ISSUE TITLE
Must refresh the buffer for multi-character pairs to function correctly

### ISSUE THREAD

**Issue by Joakker** [windwp/nvim-autopairs#52]
When trying to use multi-character pairs, such as \`\`\` in markdown, out of the box the rules don't work at all, but when calling `:lua require'nvim-autopairs'.on_attach()` or simply `:edit` , *then* the the rules start to work correctly. This, however, isn't ideal, and I'm not really sure how it can be solved.

**Comment by windwp** [comment]
how do you open that file?
can you get a latest version and test again?

**Comment by Joakker** [comment]
Ok, with the latest version, it seems to work correctly, except in the very first buffer you open. To illustrate

* Fire up `nvim a.md b.md`
* Type \`\`\` in `a.md`, doesn't work
* Change to `b.md`
* Type \`\`\` in `b.md`, works like a charm

Might be something to do with my config, or the timing for the plugin being loaded

**Comment by Joakker** [comment]
I should also mention that refreshing the buffer for `a.md` also activates the plugin

**Comment by YorickPeterse** [comment]
@Joakker Perhaps this is a problem with your configuration. For example, multi-pair expansion works fine for me with the list of steps from https://github.com/windwp/nvim-autopairs/issues/52#issuecomment-836067910. Reducing this down to an example vim config that reproduces the issue would be helpful :smiley:

**Comment by Joakker** [comment]
Ok, I found the offending plugin and disabled it. It's working now :smiley:

For the sake of completion, here's an init.vim that works
```lua
require 'packer'.startup(function()
  use {
    'windwp/nvim-autopairs',
    config = function()
      require 'nvim-autopairs'.setup()
    end,
  }
end)
```

```lua
require 'packer'.startup(function()
  use {
    'windwp/nvim-autopairs',
    config = function()
      require 'nvim-autopairs'.setup()
    end,
  }
  use 'kyazdani/nvim-tree.lua'
end)
```
