### ISSUE TITLE
Plugin failed to load with minium vimrc

### ISSUE THREAD

**Issue by ray-x** [windwp/nvim-autopairs#53]
A minium vimrc
```vim
call plug#begin('~/.vim/plugged')
Plug 'windwp/nvim-autopairs'
call plug#end()

lua <<EOF
-- require('nvim-autopairs').setup(). -- commented out because I want to load it when first time in insert mode
EOF
```

But if I run `lua require('nvim-autopairs').setup()` manually after nvim loaded,  the plugin does not work correctly, there are no errors, but if I type `(`, it does not auto pair.
If I remove comments in this line: `-- require('nvim-autopairs').setup()` it works fine.
It also can not manually loaded with

```vim
packadd nvim-autopairs
lua require('nvim-autopairs').setup()
```
There are no errors, simply does not do the job

With packer, it also has some trouble to load if I use lazy loading and specify either `keys` or `event` to lazyloading the plugin.

**Comment by windwp** [comment]
```
packadd nvim-autopairs
lua require('nvim-autopairs').setup()
```
I don't use packer but this is the code I use to run my plugin on my config.

currently plugin mapping key on BufferEnter event  after that It will cache the buffer and don't remap key on buffer anymore. 

So you do that lazyload on insert enter event  or key event that event happen after BufferEnter then it will not mapping key.

A latest version have some rule specify per file types then I don't want to use a global mapping to all buffer.

**Comment by windwp** [comment]
can you get a latest version and test again

**Comment by ray-x** [comment]
In that case, is there an API I can use to map the key to the current buffer?
e.g.  ` require('nvim-autopairs').attach(bufnr)`

**Comment by windwp** [comment]
I just update a new version it wiil call mapping funtion on setup.

**Comment by ray-x** [comment]
Tested, works fine. It means the plugin can be loaded after insert event
