### ISSUE TITLE
Newline inside pairs

### ISSUE THREAD

**Issue by agentfire170** [windwp/nvim-autopairs#54]
It would be very nice if there was an option to let the carriage return space things out properly for stuff like functions, etc. For instance, pressing enter in
```cpp
int main() {|}
```
would yield
```cpp
int main() {
    |
}
```
where `|` is the location of the cursor. Thanks for your work on this plugin!

**Comment by windwp** [comment]
check readme you need to mapping `<cr`> on insert mode.
my plugin is not do this because it have many auto complete plugin and it have a different syntax

**Comment by agentfire170** [comment]
What if I don't use either of those autocomplete plugins (or any at all)? Is there still a way for me to have this functionality by mapping something using this plugin? Sorry, I'm a bit new to Lua so I'm not entirely sure how I would do it.

**Comment by windwp** [comment]
```
local remap = vim.api.nvim_set_keymap
local npairs = require('nvim-autopairs')

-- skip it, if you use another global object
_G.MUtils= {}

MUtils.completion_confirm=function()
  if vim.fn.pumvisible() ~= 0  then
      return npairs.esc("<cr>")
  else
    return npairs.autopairs_cr()
  end
end


remap('i' , '<CR>','v:lua.MUtils.completion_confirm()', {expr = true , noremap = true})

```
use it

**Comment by agentfire170** [comment]
Thank you so much, this works perfectly
