### ISSUE TITLE
`disable_filetypes` not working

### ISSUE THREAD

**Issue by numToStr** [windwp/nvim-autopairs#55]
I just noticed that the pairs are appearing inside the telescope prompt even if they are disabled. I am using the plugin with default options.

https://user-images.githubusercontent.com/24727447/118355090-da26f580-b58b-11eb-8ce1-c9ebd3157169.mp4

**Comment by windwp** [comment]
Can you get a latest version and test again.

**Comment by numToStr** [comment]
Just checked and i think it's fixed. No pairs appearing in telescope :)
