### ISSUE TITLE
Bracket expansion only on <CR>

### ISSUE THREAD

**Issue by minhduc0711** [windwp/nvim-autopairs#58]
Hi, I wonder if it is possible to make this plugin expand pairs only on `<CR>`, similar to https://github.com/rstacruz/vim-closer?

![](https://raw.githubusercontent.com/rstacruz/vim-closer/gh-pages/closer.gif)

**Comment by windwp** [comment]
yes . please check read me in bottom.
it similar to function endwise.
but i think you need to write a custom rule for that.
the rule api is very flexible.

**Comment by minhduc0711** [comment]
Thanks, I suppose I can do something like
```
npairs.add_rules({
    endwise('{$', '}', 'c', nil)
})
```

**Comment by windwp** [comment]
i see in a demo of vimcloser it have a feature to close multiple bracket. `});` 

you can do that with replace_endpair function but it need some code to check that
