### ISSUE TITLE
Help with configuration

### ISSUE THREAD

**Issue by Araly** [windwp/nvim-autopairs#61]
Hello,

I'm having an issue that is quite annoying and I don't know how to solve it. This is what happens:
```go
update(set|))
// input: (
update(set(|))
// input: )
update(set()|)
// input: backspace
update(set(|)
//input: backspace
update(set|
```
autopairs is constantly eating my closing brackets, and I don't know why, and I don't know how to configure it so it doesn't do that. Note that the count of the parens is not always supposed to make sense, in the example I included a closing parens that pairs with an opening parens earlier in a previous line (as maybe that's relevant with how the plugin counts).

What I'd want is that when I open a parens, it also inserts the closing parens, especially if the next parens in the line is already paired with an opening one.

Here's an example of a good behavior I'd like
```go
update(set|))
// input: (
update(set(|)))
```

and 

```go
update(set()|))
// input: backspace
update(set|))
```
or
```go
update(set()|))
// input: backspace
update(set(|))
// input: backspace
update(set|))
```

Let me know if that doesn't make sense, or if this maybe isn't the plugin to do this with

**Comment by windwp** [comment]
get a latest version
```
npairs.setup({
    enable_check_bracket_line = false
})
```
 you can set that to do that

**Comment by Araly** [comment]
nice, that solved most of my issues, thanks
