### ISSUE TITLE
Not working as intended with `|foobar` examples

### ISSUE THREAD

**Issue by blackadress** [windwp/nvim-autopairs#62]
Did this with minimal config, only calling autopairs with:
`require('nvim-autopairs').setup()`

| Before    | Input | Expected    | Actual      |
|-----------|-------|-------------|-------------|
| \|foobar  | (     | (\|)foobar  | (\|foobar  |
| \|.foobar | (     | (\|).foobar | (\|.foobar |
| \|+foobar | (     | (\|)+foobar | (\|+foobar |

Neovim version:
`NVIM v0.5.0-dev+1367-g27c616d68
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3`

nvim-autopairs version: 
`b581620 (current)`

**Comment by windwp** [comment]
it have an option ignored_next_char 
default value is 
```
local ignored_next_char = string.gsub([[ [%w%%%'%[%"%.] ]],"%s+", "")
-- mean word % '  " [ . 
 ```
