### ISSUE TITLE
Jump to the next closed parenthesis instead of inserting a new one 

### ISSUE THREAD

**Issue by 6cdh** [windwp/nvim-autopairs#64]
Hi, good plugin. Thanks for your work.

Current

```
Before        Input         After
------------------------------------
( | )         )             ( )| )
```

I wish

```
Before        Input         After
------------------------------------
( | )         )             (  )|
```

How can I get this behavior?

**Comment by windwp** [comment]
what is your setup function ?
that feature already have if you use a default setup.

**Comment by 6cdh** [comment]
```lua
-- plugins.lua
use {'windwp/nvim-autopairs', config = function() require 'pairs' end}

-- pairs.lua
local npairs = require 'nvim-autopairs'
local Rule = require 'nvim-autopairs.rule'

npairs.setup()

npairs.add_rules {
    Rule(' ', ' '):with_pair(function(opts)
        local pair = opts.line:sub(opts.col, opts.col + 1)
        return vim.tbl_contains({'()', '[]', '{}'}, pair)
    end)
}
```

**Comment by 6cdh** [comment]
My nvim version

```
NVIM v0.5.0-dev+1374-g7d4f890aa
Build type: Release
LuaJIT 2.0.5
```

I use the latest plugin.

**Comment by windwp** [comment]
I didn't check that space
you can update plugin and use this rule
``` lua
    Rule('( ',' )')
        :with_pair(function() return false end)
        :with_move(function() return true end)
        :use_key(")")
```

**Comment by 6cdh** [comment]
Perfect! Thanks.

**Comment by Monklite** [comment]
> I didn't check that space
> you can update plugin and use this rule
> 
> ```lua
> npairs.add_rules {
>     Rule(' ', ' '):with_pair(function(opts)
>         local pair = opts.line:sub(opts.col, opts.col + 1)
>         return vim.tbl_contains({'()', '[]', '{}'}, pair)
>     end),
>     Rule('( ',' )')
>         :with_pair(function() return false end)
>         :with_move(function() return true end)
>         :use_key(")")
> 
> }
> ```

This works; however, it jumps to the next closed bracket even with the spacebar. Ideally (in my opinion) only using the closed bracket should make the jump since if a space is used within the brackets at all, it makes the jump when I don't want it to. Does that make sense?
