### ISSUE TITLE
indent with autopairs

### ISSUE THREAD

**Issue by timsofteng** [windwp/nvim-autopairs#66]
Have can I achieve indent with autopairs same to webstorm's one?

https://user-images.githubusercontent.com/51912173/121688769-80531600-cacc-11eb-9b81-75f7df168db2.mp4

**Comment by windwp** [comment]
https://github.com/windwp/nvim-autopairs#mapping-cr
you need to mapping <CR> on insert mode

**Comment by windwp** [comment]
you need to call a setup function first.

**Comment by timsofteng** [comment]
Doesn't work for `.vue` file:


https://user-images.githubusercontent.com/51912173/121787531-3868e780-cbcf-11eb-914d-962e72f43b52.mp4

**Comment by windwp** [comment]
you need setup treesitter indent

**Comment by timsofteng** [comment]
> you need setup treesitter indent

I've added `indent` option to treesitter config.
Still doesn't work as expected.

**Comment by windwp** [comment]
run :set indentexpr?
:set indentmethod?
to check it is correct setting

**Comment by timsofteng** [comment]
> run :set indentexpr?
> :set indentmethod?
> to check it is correct setting

`:set indetexpr?` prints correct result
![image](https://user-images.githubusercontent.com/51912173/121802744-b1575600-cc46-11eb-8d4b-083a51405246.png)

`set indentmethod?` prints `Uknown option`

**Comment by windwp** [comment]
i think you are have correct setting i don't know what happen with vue but the tsx it should working.

my config treesiter don't working with svetle.


my plugin only add a pair and new line the indent is handle by vim

**Comment by timsofteng** [comment]
> i think you are have correct setting i don't know what happen with vue but the tsx it should working.
> 
> my config treesiter don't working with svetle.
> 
> my plugin only add a pair and new line the indent is handle by vim

I'm sorry. There is no `indentexpr` for vue. I've checked just indent for tsx.
I'll open issue in treesitter repo.

BTW, is it possible to add just simple option to activaite identation in your plugin instead of may lines of code? 
somethidg like
`indent_on_enter = { enable = true }`
To get rid of code from user's config.

**Comment by windwp** [comment]
No i can't handle indent for all filetype :) and you still need treesitter or any language pack to add that method on indentexpr .

**Comment by timsofteng** [comment]
> No i can't handle indent for all filetype :) and you still need treesitter or any language pack to add that method on indentexpr .

I mean could you just wrap this config 

`local remap = vim.api.nvim_set_keymap
local npairs = require('nvim-autopairs')

-- skip it, if you use another global object
_G.MUtils= {}

MUtils.completion_confirm=function()
  if vim.fn.pumvisible() ~= 0  then
      return npairs.esc("<cr>")
  else
    return npairs.autopairs_cr()
  end
end


remap('i' , '<CR>','v:lua.MUtils.completion_confirm()', {expr = true , noremap = true})`

to this simple option
`indent_on_enter = { enable = true }`

**Comment by windwp** [comment]
yes i can but it have 2 lua completion engine and 3 or 4 vim complete engine need to mapping <cr> too.
even me i have a some special on my mapping <cr>.

**Comment by bartoszmaka** [comment]
> Doesn't work for `.vue` file:
> 
>  Peek.2021-06-12.22-39.mp4 
> Have same issue in `.ts` files as well.
> 
> P.s I've invoke `prettier` in the end of the video

This behaves as if you had indentation set to 4 spaces. Is `tabstop`, `shiftwidth` and `softtabstop` set to 2?

**Comment by timsofteng** [comment]
> yes i can but it have 2 lua completion engine and 3 or 4 vim complete engine need to mapping too.
> even me i have a some special on my mapping .

How about
`indent_on_enter = { enable = true, method = some_method }`
?

**Comment by timsofteng** [comment]
> > Doesn't work for `.vue` file:
> > Peek.2021-06-12.22-39.mp4
> > Have same issue in `.ts` files as well.
> > P.s I've invoke `prettier` in the end of the video
> 
> This behaves as if you had indentation set to 4 spaces. Is `tabstop`, `shiftwidth` and `softtabstop` set to 2?

This is all of my tab options:
![image](https://user-images.githubusercontent.com/51912173/121873575-2f7f2f80-cd0f-11eb-8f8f-22cff6647256.png)

**Comment by timsofteng** [comment]
The issue unfortunately still exists.

**Comment by ouuan** [comment]
Using https://github.com/leafOfTree/vim-vue-plugin solves this problem for me.
