### ISSUE TITLE
auto brackets with autocomplete selection

### ISSUE THREAD

**Issue by Trid-collab** [windwp/nvim-autopairs#69]
I am using autopairs for the past one month when I moved by init.vim to init.lua. Its a great plugin. I am trying to move from Vvs-code to nvim
I am using it with nvim-compe for autocomplete. Is it possible to enable the autopairs automatically when I say select a function from my auto complete with the cursor in the middle of the brackets and not triggering of the auto brackets when say I have selected a module from my autocomplete. 

I am attaching a gif to show what I mean. 
![● demo py - pivot - Visual Studio Code - Insiders 2021-06-21 15-09-37](https://user-images.githubusercontent.com/61322708/122743555-b8184580-d2a4-11eb-886f-48293cc2dc66.gif)

**Comment by windwp** [comment]
hi i know this feature plugin completion--nvim have that
It will trigger an autopair when completion item kind is a function but nvim-compe doesn't have that. You should make an issue on nvim-compe
