### ISSUE TITLE
Print Message "You need to install treesitter"

### ISSUE THREAD

**Issue by varunjayaraman** [windwp/nvim-autopairs#72]
Hey, thank you so much for the great work on this plugin. It's fast and works quite seamlessly. I just had one question: I seem to be getting a print message whenever i open up nvim saying "you need to install treesitter". Treesitter is of course already installed (i use `packer.nvim`). Even after running `:PackerSync` and reloading, I still get this message.

I checked the code and I see [where the error is coming from](https://github.com/windwp/nvim-autopairs/blob/7ff2f721cde8923fc694c1cd7a39de62587c8197/lua/nvim-autopairs.lua#L53) and I am confused why [this line](https://github.com/windwp/nvim-autopairs/blob/7ff2f721cde8923fc694c1cd7a39de62587c8197/lua/nvim-autopairs.lua#L49) is not returning `ok` for me. Any ideas?

This is the file where i configure `nvim-autopairs`:

```lua
local npairs = require('nvim-autopairs')
local Rule = require('nvim-autopairs.rule')

-- skip it, if you use another global object
_G.MUtils= {}

vim.g.completion_confirm_key = ""
MUtils.completion_confirm=function()
  if vim.fn.pumvisible() ~= 0  then
    if vim.fn.complete_info()["selected"] ~= -1 then
      return vim.fn["compe#confirm"](npairs.esc("<cr>"))
    else
      return npairs.esc("<cr>")
    end
  else
    return npairs.autopairs_cr()
  end
end


require("nvim-autopairs.completion.compe").setup({
  map_cr = true, --  map <CR> on insert mode
  map_complete = true -- it will auto insert `(` after select function or method item
})

npairs.setup({
    check_ts = true,
    ts_config = {
        lua = {'string'},-- it will not add pair on that treesitter node
        javascript = {'template_string'},
        java = false,-- don't check treesitter on java
    }
})
```

**Comment by windwp** [comment]
I check and it work for me maybe It is a problem with your packet manager You need to sure that treesitter load before then call autopairs setup.

and you don't need that code
```
-- skip it, if you use another global object
_G.MUtils= {}

vim.g.completion_confirm_key = ""
MUtils.completion_confirm=function()
  if vim.fn.pumvisible() ~= 0  then
    if vim.fn.complete_info()["selected"] ~= -1 then
      return vim.fn["compe#confirm"](npairs.esc("<cr>"))
    else
      return npairs.esc("<cr>")
    end
  else
    return npairs.autopairs_cr()
  end
end
```
it is useless if you already call  
```lua

require("nvim-autopairs.completion.compe").setup({
  map_cr = true, --  map <CR> on insert mode
  map_complete = true -- it will auto insert `(` after select function or method item
})
```

**Comment by varunjayaraman** [comment]
Alright thanks. I've gone ahead and removed it. I'm still getting the print message. Here is how i load my packer plugins:

```lua
local execute = vim.api.nvim_command
local fn = vim.fn

local install_path = fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'

if fn.empty(fn.glob(install_path)) > 0 then
  fn.system({'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path})
  execute 'packadd packer.nvim'
end

local packer_ok, packer = pcall(require, "packer")
if not packer_ok then
  print "Packer is not loaded, exiting..."
end

packer.startup(function()
  use {"wbthomason/packer.nvim"}
  use { "kyazdani42/nvim-web-devicons" }
  use{
    "glepnir/galaxyline.nvim",
    requires = {{'glepnir/zephyr-nvim'}},
    config = function()
      require("plugins.statusline")
    end,
  }

  use {
    "nvim-treesitter/nvim-treesitter",
    run = ":TSUpdate",
    event = "BufRead",
    config = function()
      require('plugins.treesitter').config()
    end
  }

  use {
    "hrsh7th/nvim-compe",
    config = require("plugins.compe").config
  }

  use "folke/lua-dev.nvim"

  use{
    "neovim/nvim-lspconfig",
    config = function()
      require("plugins.lsp")
    end,
  }

  use 'kabouzeid/nvim-lspinstall'
  use{"glepnir/lspsaga.nvim"}
  use {
    "windwp/nvim-autopairs",
    config = function() require'plugins.autopairs' end,
    after = {"nvim-treesitter"}
  }
  use {"folke/which-key.nvim"}
end)
```

The `after = {"nvim-treesitter"}` is something i added recently, and I still get the error message. I'm not sure what else I can do to make sure treesitter has loaded before. Any ideas?

**Comment by varunjayaraman** [comment]
Ah I figured it out! `treesitter` is configured to load on the event `BufRead`. Once i comment that out it works. But do you know why treesitter would not have loaded because i am reading a buffer when i load a file. So `treesitter` should have loaded for `autopairs`

**Comment by windwp** [comment]
maybe you can add autopairs lazyload too on event InsertEnter.

you can add this on top of plugins.autopairs.lua
`vim.cmd('packadd nvim-treesitter')`

**Comment by varunjayaraman** [comment]
Alright i no longer get the error, you can safely close this issue. thanks for the help
