### ISSUE TITLE
Can you say how to install it in the readme file?

### ISSUE THREAD

**Issue by 3301n** [windwp/nvim-autopairs#73]

**Comment by rebuilt** [comment]
This is how you might install using Packer.  

```
 use {
        "windwp/nvim-autopairs",
        config = function()
            YOUR_CONFIGURATION_HERE_OR_REQUIRED_EXTERNAL_CONFIG_FILE
        end
    }
```

**Comment by fuelen** [comment]
New wave of people after neovim 0.5 release here.

I've added this line
```
use "windwp/nvim-autopairs"
```
and I expect this plugin to work out-of-the-box with default settings for at least primitive cases, like () {}, etc, but it doesn't.

**Comment by rebuilt** [comment]
@fuelen 

You have to call the setup function

```
require('nvim-autopairs').setup()
```

You'll also have to tell it how to interact with the autocomplete plugin you're using.

**Comment by fuelen** [comment]
Yes, now I have a working setup. Thank you!

**Comment by windwp** [comment]
For a new people using a neovim 0.5 
some good resource
https://github.com/nanotee/nvim-lua-guide
https://github.com/rockerBOO/awesome-neovim

lua plugin usually call setup function because they don't  want to get config from vim.g.____

**Comment by azazazgwerbv** [comment]
how can i install it without a package manager? i tried putting it into .local/share/nvim/site/pack and added the directory to runtimepath but it didn't work
