### ISSUE TITLE
Error with compe integration: "attempt to index field 'config' (a nil value)

### ISSUE THREAD

**Issue by Monklite** [windwp/nvim-autopairs#75]
I've been working on setting this up and when I seem to attempt integrating it with compe, I get "attempt to index field 'config' (a nil value).  Below is my current configuration for nvim-autopairs residing in `init.vim`.  

```lua
require('nvim-autopairs.completion.compe').setup({
  disable_filetype = { "TelescopePrompt" , "vim" },
  enable_check_bracket_line = true,
  map_cr = true,
  map_complete = true,
})


--- Auto-space rules
local npairs = require'nvim-autopairs'
local Rule   = require'nvim-autopairs.rule'

npairs.add_rules {
  Rule(' ', ' ')
    :with_pair(function (opts)
      local pair = opts.line:sub(opts.col, opts.col + 1)
      return vim.tbl_contains({ '()', '[]', '{}' }, pair)
    end),
}

```

and here is my config file for compe to add some more context for the issue. If it matters, both of these snippets reside in `init.vim`.

```lua
require'compe'.setup {
  enabled = true;
  autocomplete = true;
  debug = false;
  min_length = 1;
  preselect = 'enable';
  throttle_time = 80;
  source_timeout = 200;
  incomplete_delay = 400;
  max_abbr_width = 100;
  max_kind_width = 100;
  max_menu_width = 100;
  documentation = false;

  source = {
    path = true;
    buffer = true;
    calc = true;
    vsnip = true;
    nvim_lsp = true;
    nvim_lua = true;
    spell = true;
    tags = true;
    snippets_nvim = true;
    treesitter = true;
  };
}
local t = function(str)
  return vim.api.nvim_replace_termcodes(str, true, true, true)
end

local check_back_space = function()
    local col = vim.fn.col('.') - 1
    if col == 0 or vim.fn.getline('.'):sub(col, col):match('%s') then
        return true
    else
        return false
    end
end
```  

**EDIT:**  

I reformatted the nvim-autopairs configuration as such:
```lua
require('nvim-autopairs').setup({
  disable_filetype = { "TelescopePrompt" , "vim" },
  enable_check_bracket_line = true,
})

require("nvim-autopairs.completion.compe").setup({
  map_cr = true, --  map <CR> on insert mode
  map_complete = true -- it will auto insert `(` after select function or method item
})

--- Auto-space rules
local npairs = require'nvim-autopairs'
local Rule   = require'nvim-autopairs.rule'

npairs.add_rules {
  Rule(' ', ' ')
    :with_pair(function (opts)
      local pair = opts.line:sub(opts.col, opts.col + 1)
      return vim.tbl_contains({ '()', '[]', '{}' }, pair)
    end),
}
```

The problem now, testing with a cpp file, is that the cursor does not get indented.  

```cpp
// What happens
int main() {|}

int main() {
|
}

// What is expected
int main() {|}
    |
}
```

Also, it is worth noting that indent for treesitter is enabled.

**EDIT 2:**  

I disabled the cpp filetype for treesitter indenting and it appears to indent properly now, this looks like it's not an issue with nvim-autopairs honestly. My bad!

**Comment by windwp** [comment]
the indent of treesitter is not work well in some language if your filetype already have an indent you can keep using the old method.
Is that issue  with compe still happen?

**Comment by Monklite** [comment]
> the indent of treesitter is not work well in some language if your filetype already have an indent you can keep using the old method.
> Is that issue with compe still happen?

For the time being, I have disabled treesitter indentation for cpp and python files, this seems to fix the behavior. I will close out the issue as this appears to be a treesitter issue not relevant to nvim-autopairs.
