### ISSUE TITLE
Errorrunning  config  nvim-autopairs 

### ISSUE THREAD

**Issue by siduck76** [windwp/nvim-autopairs#76]
Hi there! I configured autopairs to autoinsert parenthesis on function complete , but since I lazy load nvim-compe it doesnt work 

error : 

![image](https://user-images.githubusercontent.com/59060246/124506142-a7a9b400-dde8-11eb-835e-76a7f5de912e.png)

nvim-compe is loaded at InsertEnter , I tried loading nvim-autopairs after nvim-compe but doesnt work . My config : 

![image](https://user-images.githubusercontent.com/59060246/124506216-d031ae00-dde8-11eb-85c4-ed75a9c556cb.png)

**Comment by windwp** [comment]
you can put that 
require("nvim-autopairs.completion.compe").setup({map_cr = true, map_complete = true})
on your compe.config function

or add  `vim.cmd("packadd nvim-compe") before call a setup function`

**Comment by siduck76** [comment]
@windwp its fixed now :D 

https://github.com/wbthomason/packer.nvim/issues/448#issuecomment-874291775
