### ISSUE TITLE
`add_rule` example in wiki has wrong call signature

### ISSUE THREAD

**Issue by tbung** [windwp/nvim-autopairs#77]
`add_rule` already wraps its arguments in a table and passes it to `add_rules`, so the example in the README
```lua
local Rule = require('nvim-autopairs.rule')
local npairs = require('nvim-autopairs')

npairs.add_rule({
    Rule("$$","$$","tex")
})
```
should either use `add_rules` as well or drop the brackets.

Thank you!

**Comment by windwp** [comment]
Thank i fix that
