### ISSUE TITLE
Problem with rule allowing for spaces between parentheses

### ISSUE THREAD

**Issue by Monklite** [windwp/nvim-autopairs#78]
I use the following rule to allow for spaces between parenthesis:

```lua
local npairs = require'nvim-autopairs'
local Rule   = require'nvim-autopairs.rule'

npairs.add_rules {
  Rule(' ', ' ')
    :with_pair(function (opts)
      local pair = opts.line:sub(opts.col, opts.col + 1)
      return vim.tbl_contains({ '()', '[]', '{}' }, pair)
    end),
  Rule('( ',' )')
        :with_pair(function() return false end)
        :with_move(function() return true end)
        :use_key(")")
}
```

This allows for the behavior of:
| Before | Insert | After
| --------- | -------- | -------- |
| `(\|)`      | `space` | `( \| )` |
| `( \| )`    | `)`      | `( )\|` |

This works; however, the behavior involving pressing the `)` key (row two of the table) also works using the `space` key again; for example, if I use a space at any point in the parentheses after the initial space looking like `( | )`, then it will go to the end of the `)` character, which isn't ideal.  

How could this be fixed by modifying the rule some more?

**Comment by windwp** [comment]
```lua 
  Rule(' ', ' '):with_pair(function(opts)
        local pair = opts.line:sub(opts.col, opts.col + 1)
        return vim.tbl_contains({ '()', '[]', '{}' }, pair)
    end),
    Rule('( ', ' )')
        :with_pair(function() return false end)
        :with_move(function(opts)
            if opts.prev_char == ' )' then
                return true
            end
            return false
        end)
        :use_key(')'),
```

**Comment by Monklite** [comment]
> ```lua
> Rule(' ', ' '):with_pair(function(opts)
>       local pair = opts.line:sub(opts.col, opts.col + 1)
>       return vim.tbl_contains({ '()', '[]', '{}' }, pair)
>   end),
>   Rule('( ', ' )')
>       :with_pair(function() return false end)
>       :with_move(function(opts)
>           if opts.prev_char == ' )' then
>               return true
>           end
>           return false
>       end)
>       :use_key(')'),
> ```

That works; however, it breaks when typing anything in the parentheses. If I do an extra space and then type `)`, it will go to the end, but otherwise doesn't behave that way. 

| Before | Insert | After
| --------- | -------- | -------- |
| `( Foobar\| )`    | `)`      | `( foobar)\| )` |

I appreciate your help by the way despite this not being an urgent issue. I like the project!

**Comment by windwp** [comment]
```lua
  Rule(' ', ' '):with_pair(function(opts)
        local pair = opts.line:sub(opts.col, opts.col + 1)
        return vim.tbl_contains({ '()', '[]', '{}' }, pair)
    end),
    Rule('( ', ' )')
        :with_pair(function() return false end)
        :with_move(function(opts)
            return opts.prev_char:match('.%)') ~= nil
        end)
        :use_key(')'),
```
i like to create some custom rule like that ;)

**Comment by Monklite** [comment]
> ```lua
>   Rule('( ', ' )')
>       :with_pair(function() return false end)
>       :with_move(function(opts)
>           return opts.prev_char:match('.%)') ~= nil
>       end)
>       :use_key(')'),
> ```

It works! Thank you so much. I can update the rules section of the docs if you want, the original rule I posted was from there.

**Comment by windwp** [comment]
do it if you want  thank :)

**Comment by Monklite** [comment]
> do it if you want thank :)

Just did. Thanks again.

**Comment by stasjok** [comment]
I don't know if it's useful for somebody, but I rewrote it like this:
```lua
local npairs = require'nvim-autopairs'
local Rule = require'nvim-autopairs.rule'
local cond = require'nvim-autopairs.conds'

npairs.add_rules {
  Rule(' ', ' ')
    :with_pair(function (opts)
      local pair = opts.line:sub(opts.col, opts.col + 1)
      return vim.tbl_contains({ '()', '[]', '{}' }, pair)
    end),
  Rule('', ' )')
    :with_pair(cond.none())
    :with_del(cond.none())
    :with_move(function(opts) return opts.char == ')' end)
    :use_key(')'),
  Rule('', ' }')
    :with_pair(cond.none())
    :with_del(cond.none())
    :with_move(function(opts) return opts.char == '}' end)
    :use_key('}'),
  Rule('', ' ]')
    :with_pair(cond.none())
    :with_del(cond.none())
    :with_move(function(opts) return opts.char == ']' end)
    :use_key(']')
```
This move function simpler/faster. Also when deleting inside pairs, it first remove spaces, then pairs (not both at the same time).

What I still miss is: I want only one space inside `( )|` after moving.

**Comment by windwp** [comment]
@stasjok nice.
 Can you add it on wiki but don't delete the old solution

**Comment by stasjok** [comment]
@windwp I've added it to wiki, but I also disabled `<CR>` for this rules.
Also we need to add `:with_move` condition for `(' ', ' ')`, because now it triggered not only in pairs.
I wanted to add something like:
```lua
:with_del(cond.after_regex_check(' [])}]'), 2)
:with_del(cond.before_regex_check('[({[] '), 2)
```
But it turned out that [can_del](https://github.com/windwp/nvim-autopairs/blob/b0bbe8d9089cbb045fd15d217ac5a5ec0f4f5066/lua/nvim-autopairs.lua#L223) doesn't add `col` parameter, so many rules from `nvim-autopairs.conds` (which uses `opts.col` for substring extraction) doesn't work. It is probably a bug. But right now I can probably write matching function manually (I just thought that it's better to use stock functions).

**Comment by windwp** [comment]
i understand the problem is on with-pairs it will add the keypress to a line text but in  with-del it doesn't add key because it is a special key. so the opt col is not correct for that

**Comment by stasjok** [comment]
I don't quite understand what you mean. But anyway, I've added condition for `(' ', ' ')`.

My final version, I hope:

```lua
local npairs = require'nvim-autopairs'
local Rule = require'nvim-autopairs.rule'
local cond = require'nvim-autopairs.conds'

npairs.add_rules {
  Rule(' ', ' ')
    :with_pair(function(opts)
      local pair = opts.line:sub(opts.col, opts.col + 1)
      return vim.tbl_contains({ '()', '{}', '[]' }, pair)
    end)
    :with_move(cond.none())
    :with_cr(cond.none())
    :with_del(function(opts)
      local col = vim.api.nvim_win_get_cursor(0)[2]
      local context = opts.line:sub(col - 1, col + 2)
      return vim.tbl_contains({ '(  )', '{  }', '[  ]' }, context)
    end),
  Rule('', ' )')
    :with_pair(cond.none())
    :with_move(function(opts) return opts.char == ')' end)
    :with_cr(cond.none())
    :with_del(cond.none())
    :use_key(')'),
  Rule('', ' }')
    :with_pair(cond.none())
    :with_move(function(opts) return opts.char == '}' end)
    :with_cr(cond.none())
    :with_del(cond.none())
    :use_key('}'),
  Rule('', ' ]')
    :with_pair(cond.none())
    :with_move(function(opts) return opts.char == ']' end)
    :with_cr(cond.none())
    :with_del(cond.none())
    :use_key(']'),
}
```
Now a pair of spaces (`(' ', ' ')`) works only only inside other pairs and only for those cases: `(|) -> ( | )` (press space) and `( | ) -> (|)` (press backspace). Other pairs like `'', ' }'` works only for jumping out of pair through space.
