### ISSUE TITLE
cannot disable autopairs inside treesitter comment nodes, but all other treesitter-based autopair rules work

### ISSUE THREAD

**Issue by dajohans** [windwp/nvim-autopairs#81]
First of all, thank you so much for creating an autopair plugin that connects to treesitter! I love the added intelligence I can get for my autopairs with treesitter.

But there is one thing that I haven't been able to sort out regarding nvim-autopairs and nvim-treesitter. I generally want to turn of autopairs inside strings of text and inside comments. I have managed to turn autopairs off inside strings in c, c++ and python but I'm not able to turn off autopair inside comments in any of the three languages. I'm using the playground plugin to find the treesitter names for the nodes.

I have been able to add other autopair rules based on treesitter nodes and that works just fine. I've tried a few weird rules to create pairs in various treesitter c++ nodes and it worked just fine. So nvim-autopairs and nvim-treesitter seems to work together nicely for everything I've tried except for disabling all autopairs inside treesitter comment nodes.

Any ideas for what I might have done wrong? Or have I stumbled upon a bug?

I'm not sure what's considered the best way to add a minimal init.vim to a github issue, so I'll add it as a quote:
```viml
call plug#begin('~/.config/nvim/plugged')
Plug 'nvim-treesitter/nvim-treesitter'
Plug 'nvim-treesitter/playground'
Plug 'windwp/nvim-autopairs'
call plug#end()
lua << EOF
ts_config = require('nvim-treesitter.configs')
ts_config.setup{
	ensure_installed = "maintained",
	autopairs = {enable = true}
}
ap_config = require('nvim-autopairs')
ap_config.setup({
	check_ts = true,
	ts_config = {
		cpp = {'string_literal', 'comment'},
		c = {'string_literal', 'comment'},
		python = {'string', 'comment'}
	}
})
EOF
```

EDIT: put the init.vim code in a code block instead of quote. I'm new to github so didn't know how to create code blocks.
EDIT2: Now I learned how to put highlighting in the codeblock so I added that.

**Comment by dajohans** [comment]
```
call plug#begin('~/.config/nvim/plugged')
Plug 'nvim-treesitter/nvim-treesitter'
Plug 'nvim-treesitter/playground'
Plug 'windwp/nvim-autopairs'
call plug#end()
lua << EOF
ts_config = require('nvim-treesitter.configs')
ts_config.setup{
	ensure_installed = "maintained",
	autopairs = {enable = true}
}
ap_config = require('nvim-autopairs')
ap_config.setup({
	check_ts = true,
	ts_config = {
		cpp = {'string_literal', 'comment'},
		c = {'string_literal', 'comment'},
		python = {'string', 'comment'}
	}
})
EOF


```

**Comment by windwp** [comment]
can you give a sample of c or python code

**Comment by dajohans** [comment]
In the below piece of c code, I can create autopairs everywhere except inside the string and I use the init.vim from above. I again verified with playground that treesitter has the nodes with the names from the init.vim.
```
/* Auto generation of pairs still work here */
int main(){
	char x[] = "Autogeneration of pairs doesn't work here";
	return 0;
}
```

**Comment by windwp** [comment]
c = {'string_literal', 'comment', 'source'},
you need to add source  that playground don't display inject language  in c comment it inject another parser of document language.

**Comment by dajohans** [comment]
Thank you very much! That seems to solve the issue perfectly. Now it works just as expected! Thanks a lot!

Feel free to close this issue, unless you want it to be visible for others who might stumble upon the same situation.
