### ISSUE TITLE
Odd inconsistency in auto generation of pairs

### ISSUE THREAD

**Issue by dajohans** [windwp/nvim-autopairs#82]
I've noticed something which seems like an odd(as in: I don't think this is supposed to happen) inconsistency in the auto generation of pairs.

If I am in a place where I haven't disabled nvim-autopairs then autopairing is still disabled if there is text to the right of the cursor and this makes sense. If I have text to the left of the cursor then autopairing works(this makes sense) except for the pair `''`. So `foo(` automatically becomes `foo()` and `foo"` becomes `foo""` but `foo'` doesn't automatically become `foo''`. If instead I have whitespace to the left of the cursor then `'` becomes `''` automatically. Is this supposed to happen?

I'm using the same init.vim that I used in another recent issue:
```vim
call plug#begin('~/.config/nvim/plugged')
Plug 'nvim-treesitter/nvim-treesitter'
Plug 'nvim-treesitter/playground'
Plug 'windwp/nvim-autopairs'
call plug#end()
lua << EOF
ts_config = require('nvim-treesitter.configs')
ts_config.setup{
	ensure_installed = "maintained",
	autopairs = {enable = true}
}
ap_config = require('nvim-autopairs')
ap_config.setup({
	check_ts = true,
	ts_config = {
		cpp = {'string_literal', 'comment'},
		c = {'string_literal', 'comment'},
		python = {'string', 'comment'}
	}
})
EOF
```

**Comment by windwp** [comment]
it is normal because  English language  use  single quote inside text sample  `doesn't  or didn't `

**Comment by dajohans** [comment]
You're right, it now makes a lot more sense than I originally thought!
