### ISSUE TITLE
close function completion on open parenthesis 

### ISSUE THREAD

**Issue by gjeusel** [windwp/nvim-autopairs#84]
### Question
I would like to automagically close the completion menu when opening a parenthesis, so I can then have completion for variable in signature.
I have not found any info on it, is it doable ?

Current behaviour:
![image](https://user-images.githubusercontent.com/16243660/126288549-d3c04d71-b4eb-4584-b94e-79209d97c317.png)

Expected behaviour:
![image](https://user-images.githubusercontent.com/16243660/126288655-644c6eeb-53dd-4391-a0bb-30a6b9fccf6a.png)

### Investigated

I tried remaping the "(" in insert mode like follow:

```lua
-- Fix behaviour of completion not closing on (
_G.control_open_parenthesis_close_complete = function()
  if vim.fn.pumvisible() == 1 then
    vim.api.nvim_exec([[call compe#close()]], false)
    return t("(")
  else
    return t("(")
  end
end
vim.api.nvim_set_keymap("i", "(", "v:lua.control_open_parenthesis_close_complete()", mapopts)
```

Without any success.

**Comment by windwp** [comment]
```
require("nvim-autopairs.completion.compe").setup({
  map_cr = true, --  map <CR> on insert mode
  map_complete = true -- it will auto insert `(` after select function or method item
})
```
are you using this code above ?

**Comment by gjeusel** [comment]
Woops !! Sorry, I'm closing this issue, I wanted to open it on nvim-compe !
(I reproduced when disabling nvim-autopairs)
