### ISSUE TITLE
no indentation for () [] 

### ISSUE THREAD

**Issue by ChrisTsou** [windwp/nvim-autopairs#85]
with compe, 
after `<cr>` on { i get 
```
{
     |
}
```
but on ( and [ i get  
```
(
|
)
```
is that intended?  how can i change it?

**Comment by windwp** [comment]
check readme my plugin don't handle indent .you should use treesitter indent  if it still not work you can download a plugin support indent of your filetype

**Comment by windwp** [comment]
#66
