### ISSUE TITLE
Condition does not work properly, and proposal on endwise

### ISSUE THREAD

**Issue by dakennguyen** [windwp/nvim-autopairs#86]
```lua
    Rule('def%s.+$', 'end', 'ruby')
        :use_regex(true)
        :end_wise(cond.not_after_regex_check('.'))
```
I have this rule, and it works if `:end_wise(cond.done())`, but not with the condition above. 

I did some quick look and apparently the reason is `opts.col` in this line https://github.com/windwp/nvim-autopairs/blob/master/lua/nvim-autopairs/conds.lua#L115 returns nil, hence making error when we try to ` + 1` it. 

When I  replace `opts.col` with this line it works perfectly.
```lua
local _, col = unpack(vim.api.nvim_win_get_cursor(bufnr or 0))
```

Btw, could you consider  `cond.not_after_regex_check('.')` to be a default condition for endwise? I think it makes more sense to just apply endwise, if our cursor is at the end of line

**Comment by windwp** [comment]
hi 
on function `not_after_regex_check` it adds +1 because it uses on `with_pairs` function and that function add your keypress to  line text. but on endwise a keypress is `<enter>` then it will not add to line text.

I think you can write a new condition is_end_of_line and compare a string length with opts.cols

**Comment by dakennguyen** [comment]
Hi. The problem is not `+1` tho, the problem is on `<enter>`, the value of `opts.col` is always nil, so I couldn't do any check. Even if I write this:
```lua
cond.is_end_of_line = function()
    return function(opts)
        log.debug('is_end_of_line')
        if string.len(opts.line) == opts.col then
            return true
        end

        return false
    end
end
```
`:with_pair(cond.is_end_of_line())` -- works
`:end_wise(cond.is_end_of_line())`-- doesn't work

**Comment by windwp** [comment]
use print(vim.inspect(opts)) it have a flag check_endwise_ts

**Comment by windwp** [comment]
I think it have error on main function  i will try to correct the opt.col to make it work on `endwise`

**Comment by dakennguyen** [comment]
Thank you!

**Comment by windwp** [comment]
hi i update the opt.col so you can use another condition in endwise function
i add a function is_endline on endwise rule too.

**Comment by dakennguyen** [comment]
If after cursor, there is any space, `is_end_line` still returns true. 
![test](https://user-images.githubusercontent.com/18320285/126796607-fa6fd045-e040-4f1a-b555-dbc36db2e56c.gif)

**Comment by windwp** [comment]
my mistake i fix it

**Comment by dakennguyen** [comment]
It works perfectly! Thank you very much for your work
