### ISSUE TITLE
Consider inspecting `buftype` for disabling this plugin

### ISSUE THREAD

**Issue by stellarhoof** [windwp/nvim-autopairs#89]
There are many buffer types for which this plugin does not make any sense to have enabled. `:h buftype` for the list.

**Comment by windwp** [comment]
can you specify what buff type you want to disable.

all most bufftype on vim is use when you cannot modifiable .

**Comment by stellarhoof** [comment]
Probably these make sense by defaut: `help`, `nofile`, `nowrite`, `quickfix`, `terminal`, `prompt`. And let the user override them?

**Comment by windwp** [comment]
if you have an issue you can call a global disable() function on that bufftype.

 PR is welcome

**Comment by stellarhoof** [comment]
If `disable` deactivates the plugin globally it won't work since this is really a buffer specific thing. I'll take a look at the code later.
