### ISSUE TITLE
Error: Invalid buffer id

### ISSUE THREAD

**Issue by Peterkmoss** [windwp/nvim-autopairs#90]
I keep getting an error in some specific cases, though I can't figure out exactly what cases...

In certain files I get `E5108: Error executing lua ...packer/start/nvim-autopairs/lua/nvim-autopairs/utils.lua:102: Invalid buffer id: 21` when typing anything related to something for an autopair - OR when using backspace.

After the error it will just write a `0` where my cursor is.

Any idea what could be the cause of this?

**Comment by Peterkmoss** [comment]
Seems to have fixed itself after a reinstall of my whole config. 

No idea why, but probably some file still lingering around after changing a lot of things.

**Comment by Peterkmoss** [comment]
I figured out the exact issue!

To anyone else experiencing this issue it's most likely due to a view-file that you are loading, which will try to restore local keybinds, which uses buffernumbers and such. You can prevent your view-files from saving these by removing `options` from your `viewoptions` option in vim.

E.g.

```vimscript
set viewoptions="folds,cursor"
```

**Comment by yyancy** [comment]
@Peterkmoss Thanks!! It saved me a lot of time to solve this problem!!
