### ISSUE TITLE
enabling map_cr in nvim-compe is appending v:lua.MPairs.completion_confirm() in the buffer

### ISSUE THREAD

**Issue by accidentalprogrammer** [windwp/nvim-autopairs#93]
I don't know what I am doing wrong, if anyone can please help me out it would  be great.
for some reason when I am enabling map_cr option in autopairs for nvim-compe is appends 
`v:lua.MPairs.completion_confirm()` 
in the buffer instead of performing that action in the typescript and text file. It is working fine in lua.
These are my mappings for nvim-compe
`│ vim.api.nvim_set_keymap("i", "<C-Space>", "compe#complete()", { noremap = true, silent = true, expr = true })
│ vim.api.nvim_set_keymap("i", "<C-e>", "compe#close('<C-e>')", { noremap = true, silent = true, expr = true })
│ vim.api.nvim_set_keymap("i", "<C-f>", "compe#scroll({ 'delta': +4 })", { noremap = true, silent = true, expr = true })
│ vim.api.nvim_set_keymap("i", "<C-d>", "compe#scroll({ 'delta': -4 })", { noremap = true, silent = true, expr = true })`

and following is in my nvim-autopairs setup
`│ local npairs = require('nvim-autopairs')
H local Rule = require('nvim-autopairs.rule')     ■ Unused local `Rule`.
│
│ npairs.setup({
│   disable_filetype = { "TelescopePrompt" , "vim" },
│   check_ts = true,
│     ts_config = {
│       lua = {'string'},-- it will not add pair on that treesitter node
│       javascript = {'template_string'},
│       java = false,-- don't check treesitter on java
│   }
│ })
│
│
│ require('nvim-treesitter.configs').setup {
│     autopairs = {enable = true}
│ }
│ require("nvim-autopairs.completion.compe").setup({
│   map_cr = true, --  map <CR> on insert mode
│   map_complete = true -- it will auto insert `(` after select function or method item
│ })`

I have not checked for other filetypes yet but that is happening for ts and txt files.

**Comment by windwp** [comment]
sorry i can reproduce ite

**Comment by accidentalprogrammer** [comment]
No problem
I am somewhat new to nvim and lua both so if you have any idea what could cause it please let me know and I'll try to debug it more tonight.
Thanks

**Comment by windwp** [comment]
can you give your init.lua config

**Comment by accidentalprogrammer** [comment]
[nvim_configs.zip](https://github.com/windwp/nvim-autopairs/files/6915111/nvim_configs.zip)
Hi these are my current configs 
I commented out other plugins just to be sure some config in other file was not messing with it but its still behaving same.
Thanks for your help.
Let me know what I can do.

**Comment by windwp** [comment]
i  just try and your config is working  when i press enter

**Comment by accidentalprogrammer** [comment]
Man I guess something's messed up in my setup. I'll clean out everything and try once again from scratch. Anyway thanks for the help and awesome plugin.
You can close this issue, I just opened it because I didn't know where to ask for help.

**Comment by dinhmai74** [comment]
same issue here, are you resolve this @accidentalprogrammer ?

**Comment by rschenk** [comment]
I had this problem, which led me to this closed ticket. I eventually solved it, and it has nothing to do with autopairs itself. For me, the culprit was another plugin that had also mapped `<cr>`. That other plugin was written in vimscript and attempted to take all previous mappings on `<cr>` and string-concatenate them with their new mapping. Removing that other plugin fixed this issue.

For posterity, that other plugin was rstacruz/vim-closer which does a similar thing to autopairs. I'd installed it when evaluating the two and forgot to uninstall it. Here's the [line](https://github.com/rstacruz/vim-closer/blob/26bba80f4d987f12141da522d69aa1fa4aff4436/autoload/closer.vim#L22) that caused this bug.

**Comment by accidentalprogrammer** [comment]
Thanks for giving your input

**Comment by Redari-Es** [comment]
> I had this problem, which led me to this closed ticket. I eventually solved it, and it has nothing to do with autopairs itself. For me, the culprit was another plugin that had also mapped `<cr>`. That other plugin was written in vimscript and attempted to take all previous mappings on `<cr>` and string-concatenate them with their new mapping. Removing that other plugin fixed this issue.
> 
> For posterity, that other plugin was rstacruz/vim-closer which does a similar thing to autopairs. I'd installed it when evaluating the two and forgot to uninstall it. Here's the [line](https://github.com/rstacruz/vim-closer/blob/26bba80f4d987f12141da522d69aa1fa4aff4436/autoload/closer.vim#L22) that caused this bug.

Nice bro, check all the day, find you're right,same as you
