### ISSUE TITLE
Option to not map backtick

### ISSUE THREAD

**Issue by sassanh** [windwp/nvim-autopairs#96]
As far as I see the rule for backtick is hardcoded in `rules/basic.lua`, can we have the option to not map backtick?

**Comment by rebuilt** [comment]
Is removing the rule not enough?

```
 require('nvim-autopairs').remove_rule('`')  -- remove rule for `
 require('nvim-autopairs').clear_rules() -- clear all rules
```

**Comment by sassanh** [comment]
Thanks!

**Comment by sassanh** [comment]
There is one problem with this approach, I can't `remove_rule` before calling `.setup` and therefor ``imap ` `` is already done when I remove the rule. Weird thing is it randomly works (I guess there is a race condition for who maps later, my `init.lua` or `nvim-autopairs`)
It would be nice if it was possible to remove the rule before calling setup

**Comment by sassanh** [comment]
Currently I'm doing this:
```
      require'nvim-autopairs'.setup({
        fast_wrap = {
          pattern = string.gsub([[ [%'%"%)%>%]%)%}%,%s] ]], '%s+', ''),
        },
        check_ts = true,
      })
      require'nvim-autopairs'.add_rules(require('nvim-autopairs.rules.endwise-lua'))
      require'nvim-autopairs'.add_rules(require('nvim-autopairs.rules.endwise-ruby'))
      require'nvim-autopairs'.remove_rule('`')
      require'nvim-autopairs'.remove_rule('```')
      require'nvim-autopairs'.remove_rule('```.*$')
      vim.api.nvim_del_keymap('i', '`')
      vim.api.nvim_set_keymap('i', '`', '<c-\\><c-n>', {noremap = true})
```
Which is a hack, I would like to removing `del_keymap` and `set_keymap` here and stick with the single `set_keymap` I have in my `init.lua`

**Comment by windwp** [comment]
because some user  use lazy load plugin so i need to force mapping on setup function. but  it only happen on the first  buffer
currently you can use a remove key map. 
i still do the same thing like that inside a remove_rule when i fix it

**Comment by windwp** [comment]
I fixed it
