### ISSUE TITLE
Exclude a specific filetypes

### ISSUE THREAD

**Issue by tani** [windwp/nvim-autopairs#97]
Thank you for the cool plugin! I use this plugin in LISP code.
In LISP code, quote `'` is not a paired character. Thus, I write the following code in my `init.lua`.

```lua
pairs.remove_rule("'")↲
pairs.add_rule(
  rule("'", "'")↲
    :with_pair(cond.not_before_regex_check("%w"))↲
    :with_pair(function(_)↲
        return vim.bo.filetype ~= "lisp" and vim.bo.filetype ~= "scheme"↲
    end)
)
```

I propose a new condition like `exclude_filetypes({"lisp"})`.
Would you like to add this condition to `lua/nvim-autopairs/conds.lua`?

**Comment by windwp** [comment]
Ok, I think it will be useful to other people.
if you can make a PR will be nice.

it should return false when it is wrong
https://github.com/windwp/nvim-autopairs/blob/055e3f6c5f643792f8f9b7308129a4c24b04d711/lua/nvim-autopairs/conds.lua#L7
so if you change the order of condition it will be still correct
Thank.
