### ISSUE TITLE
Backspace and pair keys broken

### ISSUE THREAD

**Issue by joesitton** [windwp/nvim-autopairs#99]
I'm getting errors after running a recent `:PlugUpdate` and it seems to be reporting something broke in this repo although I'm not entirely sure if it is (or isn't) also related to nvim-treesitter.

On backspace:
```
E5108: Error executing lua ...vim/.plugins/nvim-autopairs/lua/nvim-autopairs/utils.lua:127: bad argument #1 to 'text_sub_char' (string expected, got nil)
```

On ", (, {, etc.
```
E5108: Error executing lua ...nfig/nvim/.plugins/nvim-autopairs/lua/nvim-autopairs.lua:329: attempt to index local 'line' (a nil value)
```

**Comment by windwp** [comment]
sorry I just run update all plugins and can reproduce of this 
so please provide minimal init.vim and step to reproduce it.
thank

**Comment by dhruvinsh** [comment]
I am having a same issue, upon pressing `backspace` or square bracket `[` it says,
```
E5108: Error executing lua ...k/packer/opt/nvim-autopairs/lua/nvim-autopairs/utils.lua:127: bad argument #1 to 'text_sub_char' (string expected, got nil)
E5108: Error executing lua ...k/packer/opt/nvim-autopairs/lua/nvim-autopairs/utils.lua:127: bad argument #1 to 'text_sub_char' (string expected, got nil)
```

I will try to have minimal setup done for it.
